codeunit 10894 "Create Post Code FR"
{
    InherentEntitlements = X;
    InherentPermissions = X;

    trigger OnRun()
    var
        ContosoPostCodeFR: Codeunit "Contoso Post Code FR";
        CreateCountryRegion: Codeunit "Create Country/Region";
    begin
        ContosoPostCodeFR.InsertPostCode('02200', VenizelLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('10000', TroyesLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('11000', CarcassonneLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('12000', RodezLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('13000', MarseilleLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('13200', ArlesLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('14000', CaenLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('15000', AurillacLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('16000', AngoulemeLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('17000', LaRochelleLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('18000', BourgesLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('19000', TulleLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('21000', DijonLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('22000', StBrieucLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('23000', GueretLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('24000', PerigueuxLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('25000', BesanconLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('26000', ValenceLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('27000', EvreuxLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('28000', ChartresLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('28100', ChartresLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('28200', ChartresLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('28300', ChartresLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('29000', QuimperLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('29200', BrestLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('30000', NimesLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('31000', ToulouseLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('32000', AuchLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('33000', BordeauxLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('34000', MontpellierLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('35000', RennesLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('36000', ChateaurouxLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('37000', ToursLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('38000', GrenobleLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('39000', LonsleSaunierLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('40000', MontdeMarsanLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('41000', BloisLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('42000', StEtienneLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('43000', LePuyLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('44000', NantesLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('44450', LaChapellebasseMerLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('45100', OlivetLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('46000', CahorsLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('47000', AgenLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('48000', MendeLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('49000', AngersLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('50000', StLoLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('50670', CasselLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('51000', ChalonssurMarneLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('52000', ChaumontLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('53000', LavalLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('53100', LavalLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('53200', LavalLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('53300', LavalLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('54000', NancyLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('55000', BarleDucLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('56000', VannesLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('57000', MetzLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('58000', NeversLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('59000', LilleLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('60000', BeauvaisLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('61000', AlenocnLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('62000', ArrasLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('63000', ClermontFerrandLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('64000', PauLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('65000', TarbesLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('66000', PerpignanLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('67000', StrasbourgLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('67200', StrasbourgLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('67550', VendenheimLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('68000', ColmarLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('69000', LyonLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('69001', LyonLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('69002', LyonLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('69006', LyonLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('70000', VesoulLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('71000', MaconLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('72000', LeMansLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('73000', ChamberyLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('74000', AnnecyLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('75000', ParisLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('75001', ParisLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('75002', ParisLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('75003', ParisLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('75004', ParisLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('75005', ParisLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('75006', ParisLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('75007', ParisLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('75008', ParisLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('75009', ParisLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('75010', ParisLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('75011', ParisLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('75012', ParisLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('75013', ParisLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('75014', ParisLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('75015', ParisLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('75016', ParisLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('75017', ParisLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('75018', ParisLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('75019', ParisLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('75020', ParisLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('76000', RouenLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('77000', MelunLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('77450', EsblyLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('78000', VersaillesLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('78370', PlaisirLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('79000', NiortLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('80000', AmiensLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('81000', AlbiLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('82000', MontaubanLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('83000', ToulonLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('83250', LaLondelesMauresLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('84000', AvignonLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('85000', LaRochesurYonLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('86000', PoitiersLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('87000', LimogesLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('88100', EpinalLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('89000', AuxerreLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('89100', AuxerreLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('89200', AuxerreLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('89300', AuxerreLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('90000', BelfortLbl, CreateCountryRegion.FR());
        ContosoPostCodeFR.InsertPostCode('GB-B27 4KT', BirminghamLbl, CreateCountryRegion.GB());
        ContosoPostCodeFR.InsertPostCode('GB-B31 2AL', BirminghamLbl, CreateCountryRegion.GB());
        ContosoPostCodeFR.InsertPostCode('GB-B32 4TF', SparkhillBirminghamLbl, CreateCountryRegion.GB());
        ContosoPostCodeFR.InsertPostCode('GB-B68 5TT', BromsgroveLbl, CreateCountryRegion.GB());
        ContosoPostCodeFR.InsertPostCode('GB-BA24 6KS', BathLbl, CreateCountryRegion.GB());
        ContosoPostCodeFR.InsertPostCode('GB-BR1 2ES', BromleyLbl, CreateCountryRegion.GB());
        ContosoPostCodeFR.InsertPostCode('GB-BS3 6KL', BristolLbl, CreateCountryRegion.GB());
        ContosoPostCodeFR.InsertPostCode('GB-CB3 7GG', CambridgeLbl, CreateCountryRegion.GB());
        ContosoPostCodeFR.InsertPostCode('GB-CF22 1XU', CardiffLbl, CreateCountryRegion.GB());
        ContosoPostCodeFR.InsertPostCode('GB-CT6 21ND', HytheLbl, CreateCountryRegion.GB());
        ContosoPostCodeFR.InsertPostCode('GB-CV6 1GY', CoventryLbl, CreateCountryRegion.GB());
        ContosoPostCodeFR.InsertPostCode('GB-DA5 3EF', SidcupLbl, CreateCountryRegion.GB());
        ContosoPostCodeFR.InsertPostCode('GB-DY5 4DJ', DudleyLbl, CreateCountryRegion.GB());
        ContosoPostCodeFR.InsertPostCode('GB-E12 5TG', EdinburghLbl, CreateCountryRegion.GB());
        ContosoPostCodeFR.InsertPostCode('GB-EH16 8JS', EdinburghLbl, CreateCountryRegion.GB());
        ContosoPostCodeFR.InsertPostCode('GB-GL1 9HM', GloucesterLbl, CreateCountryRegion.GB());
        ContosoPostCodeFR.InsertPostCode('GB-GL78 5TT', CheltenhamLbl, CreateCountryRegion.GB());
        ContosoPostCodeFR.InsertPostCode('GB-GU3 2SE', GuildfordLbl, CreateCountryRegion.GB());
        ContosoPostCodeFR.InsertPostCode('GB-GU7 5GT', GuildfordLbl, CreateCountryRegion.GB());
        ContosoPostCodeFR.InsertPostCode('GB-HG1 7YW', RiponLbl, CreateCountryRegion.GB());
        ContosoPostCodeFR.InsertPostCode('GB-HP43 2AY', TringLbl, CreateCountryRegion.GB());
        ContosoPostCodeFR.InsertPostCode('GB-IB7 7VN', GainsboroughLbl, CreateCountryRegion.GB());
        ContosoPostCodeFR.InsertPostCode('GB-L18 6SA', LiverpoolLbl, CreateCountryRegion.GB());
        ContosoPostCodeFR.InsertPostCode('GB-LE16 7YH', LeicesterLbl, CreateCountryRegion.GB());
        ContosoPostCodeFR.InsertPostCode('GB-LL6 5GB', RhylLbl, CreateCountryRegion.GB());
        ContosoPostCodeFR.InsertPostCode('GB-LN23 6GS', LincolnLbl, CreateCountryRegion.GB());
        ContosoPostCodeFR.InsertPostCode('GB-LU3 4FY', LutonLbl, CreateCountryRegion.GB());
        ContosoPostCodeFR.InsertPostCode('GB-M61 2YG', ManchesterLbl, CreateCountryRegion.GB());
        ContosoPostCodeFR.InsertPostCode('GB-ME5 6RL', MaidstoneLbl, CreateCountryRegion.GB());
        ContosoPostCodeFR.InsertPostCode('GB-MK21 7GG', BletchleyLbl, CreateCountryRegion.GB());
        ContosoPostCodeFR.InsertPostCode('GB-MK41 5AE', BedfordLbl, CreateCountryRegion.GB());
        ContosoPostCodeFR.InsertPostCode('GB-MO2 4RT', ManchesterLbl, CreateCountryRegion.GB());
        ContosoPostCodeFR.InsertPostCode('GB-N12 5XY', LondonLbl, CreateCountryRegion.GB());
        ContosoPostCodeFR.InsertPostCode('GB-N16 34Z', LondonLbl, CreateCountryRegion.GB());
        ContosoPostCodeFR.InsertPostCode('GB-NE21 3YG', NewcastleLbl, CreateCountryRegion.GB());
        ContosoPostCodeFR.InsertPostCode('GB-NP5 6GH', NewportLbl, CreateCountryRegion.GB());
        ContosoPostCodeFR.InsertPostCode('GB-OX16 0UA', CheddingtonLbl, CreateCountryRegion.GB());
        ContosoPostCodeFR.InsertPostCode('GB-PE17 4RN', CambridgeLbl, CreateCountryRegion.GB());
        ContosoPostCodeFR.InsertPostCode('GB-PE21 3TG', PeterboroughLbl, CreateCountryRegion.GB());
        ContosoPostCodeFR.InsertPostCode('GB-PE23 5IK', KingsLynnLbl, CreateCountryRegion.GB());
        ContosoPostCodeFR.InsertPostCode('GB-PL14 5GB', PlymouthLbl, CreateCountryRegion.GB());
        ContosoPostCodeFR.InsertPostCode('GB-PO21 6HG', SouthseaPortsmouthLbl, CreateCountryRegion.GB());
        ContosoPostCodeFR.InsertPostCode('GB-PO7 2HI', PortsmouthLbl, CreateCountryRegion.GB());
        ContosoPostCodeFR.InsertPostCode('GB-SA1 2HS', SwanseaLbl, CreateCountryRegion.GB());
        ContosoPostCodeFR.InsertPostCode('GB-SA3 7HI', StratfordLbl, CreateCountryRegion.GB());
        ContosoPostCodeFR.InsertPostCode('GB-SK21 5DL', MacclesfieldLbl, CreateCountryRegion.GB());
        ContosoPostCodeFR.InsertPostCode('GB-TA3 4FD', NewquayLbl, CreateCountryRegion.GB());
        ContosoPostCodeFR.InsertPostCode('GB-TN27 6YD', AshfordLbl, CreateCountryRegion.GB());
        ContosoPostCodeFR.InsertPostCode('GB-TQ17 8HB', BrixhamLbl, CreateCountryRegion.GB());
        ContosoPostCodeFR.InsertPostCode('GB-W1 3AL', LondonLbl, CreateCountryRegion.GB());
        ContosoPostCodeFR.InsertPostCode('GB-W2 8HG', LondonLbl, CreateCountryRegion.GB());
        ContosoPostCodeFR.InsertPostCode('GB-WC1 2GS', WestEndLaneLbl, CreateCountryRegion.GB());
        ContosoPostCodeFR.InsertPostCode('GB-WC1 3DG', LondonLbl, CreateCountryRegion.GB());
        ContosoPostCodeFR.InsertPostCode('GB-WD1 6YG', WatfordLbl, CreateCountryRegion.GB());
        ContosoPostCodeFR.InsertPostCode('GB-WD2 4RG', WatfordLbl, CreateCountryRegion.GB());
        ContosoPostCodeFR.InsertPostCode('GB-WD6 8UY', BorehamwoodLbl, CreateCountryRegion.GB());
        ContosoPostCodeFR.InsertPostCode('GB-WD6 9HY', BorehamwoodLbl, CreateCountryRegion.GB());
    end;

    var
        VenizelLbl: Label 'Venizel', MaxLength = 30;
        TroyesLbl: Label 'Troyes', MaxLength = 30;
        CarcassonneLbl: Label 'Carcassonne', MaxLength = 30;
        RodezLbl: Label 'Rodez', MaxLength = 30;
        MarseilleLbl: Label 'Marseille', MaxLength = 30;
        ArlesLbl: Label 'Arles', MaxLength = 30;
        CaenLbl: Label 'Caen', MaxLength = 30;
        AurillacLbl: Label 'Aurillac', MaxLength = 30;
        AngoulemeLbl: Label 'Angoulème', MaxLength = 30;
        LaRochelleLbl: Label 'La Rochelle', MaxLength = 30;
        BourgesLbl: Label 'Bourges', MaxLength = 30;
        TulleLbl: Label 'Tulle', MaxLength = 30;
        DijonLbl: Label 'Dijon', MaxLength = 30;
        StBrieucLbl: Label 'St.-Brieuc', MaxLength = 30;
        GueretLbl: Label 'Guéret', MaxLength = 30;
        PerigueuxLbl: Label 'Périgueux', MaxLength = 30;
        BesanconLbl: Label 'Besançon', MaxLength = 30;
        ValenceLbl: Label 'Valence', MaxLength = 30;
        EvreuxLbl: Label 'Evreux', MaxLength = 30;
        ChartresLbl: Label 'Chartres', MaxLength = 30;
        QuimperLbl: Label 'Quimper', MaxLength = 30;
        BrestLbl: Label 'Brest', MaxLength = 30;
        NimesLbl: Label 'Nîmes', MaxLength = 30;
        ToulouseLbl: Label 'Toulouse', MaxLength = 30;
        AuchLbl: Label 'Auch', MaxLength = 30;
        BordeauxLbl: Label 'Bordeaux', MaxLength = 30;
        MontpellierLbl: Label 'Montpellier', MaxLength = 30;
        RennesLbl: Label 'Rennes', MaxLength = 30;
        ChateaurouxLbl: Label 'Châteauroux', MaxLength = 30;
        ToursLbl: Label 'Tours', MaxLength = 30;
        GrenobleLbl: Label 'Grenoble', MaxLength = 30;
        LonsleSaunierLbl: Label 'Lons-le-Saunier', MaxLength = 30;
        MontdeMarsanLbl: Label 'Mont-de-Marsan', MaxLength = 30;
        BloisLbl: Label 'Blois', MaxLength = 30;
        StEtienneLbl: Label 'St.-Etienne', MaxLength = 30;
        LePuyLbl: Label 'Le Puy', MaxLength = 30;
        NantesLbl: Label 'Nantes', MaxLength = 30;
        LaChapellebasseMerLbl: Label 'La Chapelle basse Mer', MaxLength = 30;
        OlivetLbl: Label 'Olivet', MaxLength = 30;
        CahorsLbl: Label 'Cahors', MaxLength = 30;
        AgenLbl: Label 'Agen', MaxLength = 30;
        MendeLbl: Label 'Mende', MaxLength = 30;
        AngersLbl: Label 'Angers', MaxLength = 30;
        StLoLbl: Label 'St.-Lo', MaxLength = 30;
        CasselLbl: Label 'Cassel', MaxLength = 30;
        ChalonssurMarneLbl: Label 'Châlons-sur-Marne', MaxLength = 30;
        ChaumontLbl: Label 'Chaumont', MaxLength = 30;
        LavalLbl: Label 'Laval', MaxLength = 30;
        NancyLbl: Label 'Nancy', MaxLength = 30;
        BarleDucLbl: Label 'Bar-le-Duc', MaxLength = 30;
        VannesLbl: Label 'Vannes', MaxLength = 30;
        MetzLbl: Label 'Metz', MaxLength = 30;
        NeversLbl: Label 'Nevers', MaxLength = 30;
        LilleLbl: Label 'Lille', MaxLength = 30;
        BeauvaisLbl: Label 'Beauvais', MaxLength = 30;
        AlenocnLbl: Label 'Alençon', MaxLength = 30;
        ArrasLbl: Label 'Arras', MaxLength = 30;
        ClermontFerrandLbl: Label 'Clermont-Ferrand', MaxLength = 30;
        PauLbl: Label 'Pau', MaxLength = 30;
        TarbesLbl: Label 'Tarbes', MaxLength = 30;
        PerpignanLbl: Label 'Perpignan', MaxLength = 30;
        StrasbourgLbl: Label 'Strasbourg', MaxLength = 30;
        VendenheimLbl: Label 'Vendenheim', MaxLength = 30;
        ColmarLbl: Label 'Colmar', MaxLength = 30;
        LyonLbl: Label 'Lyon', MaxLength = 30;
        VesoulLbl: Label 'Vesoul', MaxLength = 30;
        MaconLbl: Label 'Mâcon', MaxLength = 30;
        LeMansLbl: Label 'Le Mans', MaxLength = 30;
        ChamberyLbl: Label 'Chambéry', MaxLength = 30;
        AnnecyLbl: Label 'Annecy', MaxLength = 30;
        ParisLbl: Label 'Paris', MaxLength = 30;
        RouenLbl: Label 'Rouen', MaxLength = 30;
        MelunLbl: Label 'Melun', MaxLength = 30;
        EsblyLbl: Label 'Esbly', MaxLength = 30;
        VersaillesLbl: Label 'Versailles', MaxLength = 30;
        PlaisirLbl: Label 'Plaisir', MaxLength = 30;
        NiortLbl: Label 'Niort', MaxLength = 30;
        AmiensLbl: Label 'Amiens', MaxLength = 30;
        AlbiLbl: Label 'Albi', MaxLength = 30;
        MontaubanLbl: Label 'Montauban', MaxLength = 30;
        ToulonLbl: Label 'Toulon', MaxLength = 30;
        LaLondelesMauresLbl: Label 'La Londe les Maures', MaxLength = 30;
        AvignonLbl: Label 'Avignon', MaxLength = 30;
        LaRochesurYonLbl: Label 'La Roche-sur-Yon', MaxLength = 30;
        PoitiersLbl: Label 'Poitiers', MaxLength = 30;
        LimogesLbl: Label 'Limoges', MaxLength = 30;
        EpinalLbl: Label 'Epinal', MaxLength = 30;
        AuxerreLbl: Label 'Auxerre', MaxLength = 30;
        BelfortLbl: Label 'Belfort', MaxLength = 30;
        BirminghamLbl: Label 'Birmingham', MaxLength = 30;
        SparkhillBirminghamLbl: Label 'Sparkhill, Birmingham', MaxLength = 30;
        BromsgroveLbl: Label 'Bromsgrove', MaxLength = 30;
        BathLbl: Label 'Bath', MaxLength = 30;
        BromleyLbl: Label 'Bromley', MaxLength = 30;
        BristolLbl: Label 'Bristol', MaxLength = 30;
        CardiffLbl: Label 'Cardiff', MaxLength = 30;
        HytheLbl: Label 'Hythe', MaxLength = 30;
        CoventryLbl: Label 'Coventry', MaxLength = 30;
        SidcupLbl: Label 'Sidcup', MaxLength = 30;
        DudleyLbl: Label 'Dudley', MaxLength = 30;
        EdinburghLbl: Label 'Edinburgh', MaxLength = 30;
        GloucesterLbl: Label 'Gloucester', MaxLength = 30;
        CheltenhamLbl: Label 'Cheltenham', MaxLength = 30;
        GuildfordLbl: Label 'Guildford', MaxLength = 30;
        RiponLbl: Label 'Ripon', MaxLength = 30;
        TringLbl: Label 'Tring', MaxLength = 30;
        GainsboroughLbl: Label 'Gainsborough', MaxLength = 30;
        LiverpoolLbl: Label 'Liverpool', MaxLength = 30;
        LeicesterLbl: Label 'Leicester', MaxLength = 30;
        RhylLbl: Label 'Rhyl', MaxLength = 30;
        LincolnLbl: Label 'Lincoln', MaxLength = 30;
        LutonLbl: Label 'Luton', MaxLength = 30;
        ManchesterLbl: Label 'Manchester', MaxLength = 30;
        MaidstoneLbl: Label 'Maidstone', MaxLength = 30;
        BletchleyLbl: Label 'Bletchley', MaxLength = 30;
        BedfordLbl: Label 'Bedford', MaxLength = 30;
        NewcastleLbl: Label 'Newcastle', MaxLength = 30;
        NewportLbl: Label 'Newport', MaxLength = 30;
        CheddingtonLbl: Label 'Cheddington', MaxLength = 30;
        CambridgeLbl: Label 'Cambridge', MaxLength = 30;
        PeterboroughLbl: Label 'Peterborough', MaxLength = 30;
        KingsLynnLbl: Label 'Kings Lynn', MaxLength = 30;
        PlymouthLbl: Label 'Plymouth', MaxLength = 30;
        SouthseaPortsmouthLbl: Label 'Southsea, Portsmouth', MaxLength = 30;
        PortsmouthLbl: Label 'Portsmouth', MaxLength = 30;
        SwanseaLbl: Label 'Swansea', MaxLength = 30;
        StratfordLbl: Label 'Stratford', MaxLength = 30;
        MacclesfieldLbl: Label 'Macclesfield', MaxLength = 30;
        NewquayLbl: Label 'Newquay', MaxLength = 30;
        AshfordLbl: Label 'Ashford', MaxLength = 30;
        BrixhamLbl: Label 'Brixham', MaxLength = 30;
        WestEndLaneLbl: Label 'West End Lane', MaxLength = 30;
        LondonLbl: Label 'London', MaxLength = 30;
        WatfordLbl: Label 'Watford', MaxLength = 30;
        BorehamwoodLbl: Label 'Borehamwood', MaxLength = 30;
}