name: Create an extensibility request
description: Create an event request, request for external or other extensibility request, Microsoft should process
type: 'Task'
body:
  - type: markdown
    attributes:
      value: |
        Thanks for submitting an extensibility request.

        ⚠️⚠️ Before you start ⚠️⚠️
        Before you create a new issue, please check the following:
        🔎 Search the existing issues to avoid a duplicate.
  - type: textarea
    id: describe-the-request
    attributes:
      label: Describe the request
      description: Provide a clear, concise description of what you need. Tell us what you want to address.
      placeholder: Describe the extensibility request
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Explain the benefits of what you’re requesting. Help us assess the best way to fulfil your need.
      placeholder: Explain the benefits
    validations:
      required: true
