name: Create an extensibility request
description: Create an event request, request for external or other extensibility request, Microsoft should process
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this extensibility request form. 

        ⚠️⚠️ BEFORE WE GET STARTED ⚠️⚠️
        Before you create a new issue, please check the following:
        🔎 Search existing issues to avoid creating duplicates.
  - type: textarea
    id: describe-the-request
    attributes:
      label: Describe the request
      description: A clear and concise description of what the extensibility request is, which you want Microsoft to address
      placeholder: Describe the extensibility request
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Explain why you need this request to be fulfilled. This will help Microsoft assess, if your request could get solved in other ways
      placeholder: Explain why you need this request
    validations:
      required: true