codeunit 5695 "Create VAT Reg. No. Format"
{
    InherentEntitlements = X;
    InherentPermissions = X;

    trigger OnRun()
    var
        CreateCountryRegion: Codeunit "Create Country/Region";
        ContosoCountryOrRegion: Codeunit "Contoso Country Or Region";
    begin
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.AT(), 10000, ATFormatLbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.BE(), 10000, BEFormatLbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.BE(), 20000, BEFormat1Lbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.BE(), 30000, BEFormat2Lbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.BE(), 40000, BEFormat3Lbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.BE(), 50000, BEFormat4Lbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.BE(), 60000, BEFormat5Lbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.BE(), 70000, BEFormat6Lbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.BG(), 10000, BGFormatLbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.BG(), 20000, BGFormat1Lbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.CH(), 10000, CHFormatLbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.CH(), 20000, CHFormat1Lbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.CH(), 30000, CHFormat2Lbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.CH(), 40000, CHFormat3Lbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.CY(), 10000, CYFormatLbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.CY(), 20000, CYFormat1Lbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.CZ(), 10000, CZFormatLbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.CZ(), 20000, CZFormat1Lbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.CZ(), 30000, CZFormat2Lbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.DE(), 10000, DEFormatLbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.DE(), 20000, DEFormat1Lbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.DK(), 10000, DKFormatLbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.DK(), 20000, DKFormat1Lbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.EE(), 10000, EEFormatLbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.EE(), 20000, EEFormat1Lbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.ES(), 10000, ESFormatLbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.ES(), 20000, ESFormat1Lbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.ES(), 30000, ESFormat2Lbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.ES(), 40000, ESFormat3Lbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.ES(), 50000, ESFormat4Lbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.ES(), 60000, ESFormat5Lbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.ES(), 70000, ESFormat6Lbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.ES(), 80000, ESFormat7Lbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.ES(), 90000, ESFormat8Lbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.ES(), 100000, ESFormat9Lbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.ES(), 110000, ESFormat10Lbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.ES(), 120000, ESFormat11Lbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.ES(), 130000, ESFormat12Lbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.ES(), 140000, ESFormat13Lbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.ES(), 150000, ESFormat14Lbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.FR(), 10000, FRFormatLbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.FR(), 20000, FRFormat1Lbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.GB(), 10000, GBFormatLbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.GB(), 20000, GBFormat1Lbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.GB(), 30000, GBFormat2Lbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.GB(), 40000, GBFormat3Lbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.GB(), 50000, GBFormat4Lbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.GB(), 60000, GBFormat5Lbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.HR(), 10000, HRFormatLbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.HU(), 10000, HUFormatLbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.HU(), 20000, HUFormat1Lbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.LT(), 10000, LTFormatLbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.LT(), 20000, LTFormat1Lbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.LT(), 30000, LTFormat2Lbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.LT(), 40000, LTFormat3Lbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.LU(), 10000, LUFormatLbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.LU(), 20000, LUFormat1Lbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.LV(), 10000, LVFormatLbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.LV(), 20000, LVFormat1Lbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.MT(), 10000, MTFormatLbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.MT(), 20000, MTFormat1Lbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.NL(), 10000, NLFormatLbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.NL(), 20000, NLFormat1Lbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.NO(), 10000, NOFormatLbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.NO(), 20000, NOFormat1Lbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.NO(), 30000, NOFormat2Lbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.NO(), 40000, NOFormat3Lbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.PL(), 10000, PLFormatLbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.PL(), 20000, PLFormat1Lbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.RO(), 10000, ROFormatLbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.SE(), 10000, SEFormatLbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.SE(), 20000, SEFormat1Lbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.SG(), 10000, SGFormatLbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.SI(), 10000, SIFormatLbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.SI(), 20000, SIFormat1Lbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.SK(), 10000, SKFormatLbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.SK(), 20000, SKFormat1Lbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.SK(), 30000, SKFormat2Lbl);
        ContosoCountryOrRegion.InsertVATRegNoFormat(CreateCountryRegion.SK(), 40000, SKFormat3Lbl);
    end;

    var
        ATFormatLbl: Label 'ATU########', MaxLength = 20, Locked = true;
        BEFormatLbl: Label 'BE#########', MaxLength = 20, Locked = true;
        BEFormat1Lbl: Label 'BE #########', MaxLength = 20, Locked = true;
        BEFormat2Lbl: Label 'BE ###.###.###', MaxLength = 20, Locked = true;
        BEFormat3Lbl: Label 'BE ### ### ###', MaxLength = 20, Locked = true;
        BEFormat4Lbl: Label '#########', MaxLength = 20, Locked = true;
        BEFormat5Lbl: Label '###.###.###', MaxLength = 20, Locked = true;
        BEFormat6Lbl: Label '### ### ###', MaxLength = 20, Locked = true;
        BGFormatLbl: Label 'BG##########', MaxLength = 20, Locked = true;
        BGFormat1Lbl: Label 'BG#########', MaxLength = 20, Locked = true;
        CHFormatLbl: Label 'CHE-###.###.###MWST', MaxLength = 20, Locked = true;
        CHFormat1Lbl: Label 'CHE-###.###.### TVA', MaxLength = 20, Locked = true;
        CHFormat2Lbl: Label 'CHE-###.###.### IVA', MaxLength = 20, Locked = true;
        CHFormat3Lbl: Label '### ###', MaxLength = 20, Locked = true;
        CYFormatLbl: Label 'CY########@', MaxLength = 20, Locked = true;
        CYFormat1Lbl: Label '########@', MaxLength = 20, Locked = true;
        CZFormatLbl: Label 'CZ########', MaxLength = 20, Locked = true;
        CZFormat1Lbl: Label 'CZ#########', MaxLength = 20, Locked = true;
        CZFormat2Lbl: Label 'CZ##########', MaxLength = 20, Locked = true;
        DEFormatLbl: Label 'DE#########', MaxLength = 20, Locked = true;
        DEFormat1Lbl: Label '#########', MaxLength = 20, Locked = true;
        DKFormatLbl: Label 'DK########', MaxLength = 20, Locked = true;
        DKFormat1Lbl: Label '########', MaxLength = 20, Locked = true;
        EEFormatLbl: Label 'EE#########', MaxLength = 20, Locked = true;
        EEFormat1Lbl: Label '#########', MaxLength = 20, Locked = true;
        ESFormatLbl: Label 'ES########@', MaxLength = 20, Locked = true;
        ESFormat1Lbl: Label '########@', MaxLength = 20, Locked = true;
        ESFormat2Lbl: Label 'ES@########', MaxLength = 20, Locked = true;
        ESFormat3Lbl: Label '@########', MaxLength = 20, Locked = true;
        ESFormat4Lbl: Label 'ES@#######@', MaxLength = 20, Locked = true;
        ESFormat5Lbl: Label '@#######@', MaxLength = 20, Locked = true;
        ESFormat6Lbl: Label '@########@', MaxLength = 20, Locked = true;
        ESFormat7Lbl: Label '@######@', MaxLength = 20, Locked = true;
        ESFormat8Lbl: Label '@#####@', MaxLength = 20, Locked = true;
        ESFormat9Lbl: Label '#######@', MaxLength = 20, Locked = true;
        ESFormat10Lbl: Label '######@', MaxLength = 20, Locked = true;
        ESFormat11Lbl: Label '#####@', MaxLength = 20, Locked = true;
        ESFormat12Lbl: Label '@#######', MaxLength = 20, Locked = true;
        ESFormat13Lbl: Label '@######', MaxLength = 20, Locked = true;
        ESFormat14Lbl: Label '@#####', MaxLength = 20, Locked = true;
        FRFormatLbl: Label 'FR###########', MaxLength = 20, Locked = true;
        FRFormat1Lbl: Label '###########', MaxLength = 20, Locked = true;
        GBFormatLbl: Label 'GB#########', MaxLength = 20, Locked = true;
        GBFormat1Lbl: Label 'GB###-####-##', MaxLength = 20, Locked = true;
        GBFormat2Lbl: Label 'GB### #### ##', MaxLength = 20, Locked = true;
        GBFormat3Lbl: Label '###-####-##', MaxLength = 20, Locked = true;
        GBFormat4Lbl: Label '### #### ##', MaxLength = 20, Locked = true;
        GBFormat5Lbl: Label '#########', MaxLength = 20, Locked = true;
        HRFormatLbl: Label 'HR###########', MaxLength = 20, Locked = true;
        HUFormatLbl: Label 'HU########', MaxLength = 20, Locked = true;
        HUFormat1Lbl: Label '########', MaxLength = 20, Locked = true;
        LTFormatLbl: Label 'LT#########', MaxLength = 20, Locked = true;
        LTFormat1Lbl: Label 'LT############', MaxLength = 20, Locked = true;
        LTFormat2Lbl: Label '#########', MaxLength = 20, Locked = true;
        LTFormat3Lbl: Label '############', MaxLength = 20, Locked = true;
        LUFormatLbl: Label 'LU########', MaxLength = 20, Locked = true;
        LUFormat1Lbl: Label '########', MaxLength = 20, Locked = true;
        LVFormatLbl: Label 'LV###########', MaxLength = 20, Locked = true;
        LVFormat1Lbl: Label '###########', MaxLength = 20, Locked = true;
        MTFormatLbl: Label 'MT########', MaxLength = 20, Locked = true;
        MTFormat1Lbl: Label '########', MaxLength = 20, Locked = true;
        NLFormatLbl: Label 'NL#########B##', MaxLength = 20, Locked = true;
        NLFormat1Lbl: Label '#########B##', MaxLength = 20, Locked = true;
        NOFormatLbl: Label 'NO ### ### ### MVA', MaxLength = 20, Locked = true;
        NOFormat1Lbl: Label '### ### ### MVA', MaxLength = 20, Locked = true;
        NOFormat2Lbl: Label 'NO ### ### ###', MaxLength = 20, Locked = true;
        NOFormat3Lbl: Label '#########', MaxLength = 20, Locked = true;
        PLFormatLbl: Label 'PL##########', MaxLength = 20, Locked = true;
        PLFormat1Lbl: Label '##########', MaxLength = 20, Locked = true;
        ROFormatLbl: Label 'RO##########', MaxLength = 20, Locked = true;
        SEFormatLbl: Label 'SE##########01', Comment = 'SE##########01 is the VAT Reg. No Format', MaxLength = 20, Locked = true;
        SEFormat1Lbl: Label '##########01', Comment = '##########01 is the VAT Reg. No Format', MaxLength = 20, Locked = true;
        SGFormatLbl: Label '##-#######-?', MaxLength = 20, Locked = true;
        SIFormatLbl: Label 'SI########', MaxLength = 20, Locked = true;
        SIFormat1Lbl: Label '########', MaxLength = 20, Locked = true;
        SKFormatLbl: Label 'SK#########', MaxLength = 20, Locked = true;
        SKFormat1Lbl: Label 'SK##########', MaxLength = 20, Locked = true;
        SKFormat2Lbl: Label '#########', MaxLength = 20, Locked = true;
        SKFormat3Lbl: Label '##########', MaxLength = 20, Locked = true;
}