# Security tools

name: 1.0.$(Year:yy)$(DayOfYear).$(Rev:r) # This is the build number

trigger: none
schedules:
- cron: "0 0 * * *"
  displayName: Daily at midnight
  branches:
    include:
    - main

pool:
  name: dynamics-bc-managed-xl

resources:
  repositories:
  - repository: PipelineTemplates
    type: git
    name: Infrastructure-PipelineTemplates
    ref: master

variables:
- template: corext-bootstrap-variables.yml@PipelineTemplates
- template: security-tools-full-variables.yml@PipelineTemplates
- name: OutputPath
  value: $(Pipeline.Workspace)\out
- name: SourcePath  
  value: $(Build.SourcesDirectory)
  readonly: true
- name: PackagesPath
  value: $(Build.ArtifactStagingDirectory)\packages
  readonly: true
- name: runCodesignValidationInjection
  value: false


jobs:
- job: default_job
  displayName: Run security tools
  timeoutInMinutes: 480
  steps:
  - checkout: self
    fetchTags: 'true'
  - powershell: |
      $gitTag = git describe --tags --match "builds/*" --abbrev=0
      $buildNumber = $gitTag -replace 'builds/', ''
      Write-Host "##vso[build.updatebuildnumber]$buildNumber"
      Write-Host "Build Number is now: $(Build.BuildNumber)"
  - task: DownloadPackage@1
    inputs:
      feed: '/DynamicsSMBPackages'
      definition: 'microsoft-ALAppExtensions-Modules-preview'
      version: $(Build.BuildNumber)
      downloadPath: $(OutputPath)
  - template: security-tools-full.yml@PipelineTemplates
    parameters:
      OutputPath: $(OutputPath)
      SourcePath: $(SourcePath)
      BuildCommand: Powershell.exe -NonInteractive "cd $(Build.SourcesDirectory); .\build.ps1 -ALGoProject 'Test Stability Tools'"
      GdnSuppressFile: $(Build.SourcesDirectory)\.azuredevops\security-tools.gdnsuppress
      ExcludeSecurityTools:
      - Semmle # Not applicable (AL not supported)
      - CodeSignValidation # Not applicable yet (Code is not signed on Github) 
      IncludeOfficialBuildTools:
      - ComponentGovernance