# Security tools

name: 1.0.$(Year:yy)$(DayOfYear).$(Rev:r) # This is the build number

trigger: none
schedules:
- cron: "0 0 * * *"
  displayName: Daily at midnight
  branches:
    include:
    - main

pool:
  name: dynamics-bc-managed-xl

steps:
- task: securedevelopmentteam.vss-secure-development-tools.build-task-credscan.CredScan@3
  displayName: 'Security Tools - Run CredScan'

- task: securedevelopmentteam.vss-secure-development-tools.build-task-policheck.PoliCheck@2
  displayName: 'Security Tools - Run PoliCheck'
  inputs:
    targetType: F
    targetArgument: $(Build.SourcesDirectory)
    SOMEnabled: true

# TODO: AntiMalware 

# TODO: Component Governance (Should this be run?)