# Security tools

name: 1.0.$(Year:yy)$(DayOfYear).$(Rev:r) # This is the build number

trigger: none
schedules:
- cron: "0 0 * * *"
  displayName: Daily at midnight
  branches:
    include:
    - main

pool:
  name: dynamics-bc-managed-xl

resources:
  repositories:
  - repository: PipelineTemplates
    type: git
    name: Infrastructure-PipelineTemplates
    ref: master

variables:
- template: corext-bootstrap-variables.yml@PipelineTemplates
- template: security-tools-full-variables.yml@PipelineTemplates
- name: OutputPath # Path where the build output from NAV-OfficialBuild is downloaded. It needs to be outside of the enlistment.
  value: $(Pipeline.Workspace)\out
- name: SourcePath
  value: $(Build.SourcesDirectory)
  readonly: true
- name: PackagesPath
  value: $(Build.ArtifactStagingDirectory)\packages
  readonly: true
- name: runCodesignValidationInjection
  value: false


jobs:
- job: default_job
  displayName: Run security tools
  timeoutInMinutes: 480
  steps:
  - template: get-sources.yml@PipelineTemplates
    parameters:
      fetchTags: false
  - template: security-tools-full.yml@PipelineTemplates
    parameters:
      OutputPath: $(OutputPath)
      SourcePath: $(SourcePath)
      BuildCommand: 'Powershell.exe -NonInteractive "cd $(Build.SourcesDirectory)"'
      ExcludeSecurityTools:
      - Semmle # Not applicable
      - CodeSignValidation
      IncludeOfficialBuildTools:
      - ComponentGovernance
      ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
        TSA: true
        TSAIncludeTools: 'PoliCheck'
