namespace Microsoft.Sustainability;

using Microsoft.API.V1;
using Microsoft.Sustainability.Account;
using Microsoft.Sustainability.Calculation;
using Microsoft.Sustainability.CBAM;
using Microsoft.Sustainability.Certificate;
using Microsoft.Sustainability.CRM;
using Microsoft.Sustainability.Emission;
using Microsoft.Sustainability.Energy;
using Microsoft.Sustainability.EPR;
using Microsoft.Sustainability.ESGReporting;
using Microsoft.Sustainability.ExciseTax;
using Microsoft.Sustainability.FinancialReporting;
using Microsoft.Sustainability.Journal;
using Microsoft.Sustainability.Ledger;
using Microsoft.Sustainability.Manufacturing;
using Microsoft.Sustainability.Posting;
using Microsoft.Sustainability.Reports;
using Microsoft.Sustainability.RoleCenters;
using Microsoft.Sustainability.Scorecard;
using Microsoft.Sustainability.Setup;
using Microsoft.Sustainability.Workflow;

permissionset 6210 "Sustainability - Objects"
{
    Caption = 'Sustainability - Objects';
    Access = Internal;
    Assignable = false;

    Permissions =
        table "Sustainability Account" = X,
        table "Sustain. Account Category" = X,
        table "Sustain. Account Subcategory" = X,
        table "Sustainability Jnl. Template" = X,
        table "Sustainability Jnl. Batch" = X,
        table "Sustainability Jnl. Line" = X,
        table "Sustainability Ledger Entry" = X,
        table "Sustainability Value Entry" = X,
        table "Sustainability Setup" = X,
        table "Emission Fee" = X,
        table "Sust. Account (Analysis View)" = X,
        table "Sust. Certificate Area" = X,
        table "Sust. Certificate Standard" = X,
        table "Sustainability Certificate" = X,
        table "Sustainability Cue" = X,
        table "Sustainability Goal" = X,
        table "Sustainability Goal Cue" = X,
        table "Sustainability Scorecard" = X,
        table "Sustainability Energy Source" = X,
        table "Sust. ESG Reporting Template" = X,
        table "Sust. ESG Reporting Name" = X,
        table "Sust. ESG Reporting Line" = X,
        table "Sust. Posted ESG Report Header" = X,
        table "Sust. Posted ESG Report Line" = X,
        table "Sust. Assessment" = X,
        table "Sust. Assessment Req. Fact" = X,
        table "Sust. Assessment Requirement" = X,
        table "Sust. Concept" = X,
        table "Sust. ESG Fact" = X,
        table "Sust. ESG Reporting Unit" = X,
        table "Sust. ESG Standard" = X,
        table "Sust. Item Emission Buffer" = X,
        table "Sust. Range Period" = X,
        table "Sust. Requirement Concept" = X,
        table "Sust. Standard" = X,
        table "Sust. Standard Requirement" = X,
        table "Sust. Unit" = X,
        table "Sust. Excise Jnl. Line" = X,
        table "Sust. Excise Journal Batch" = X,
        table "Sust. Excise Journal Template" = X,
        table "Sust. Excise Taxes Trans. Log" = X,
        table "Sust. Item Mat. Comp. Header" = X,
        table "Sust. Item Mat. Comp. Line" = X,
        table "Sustainability Carbon Pricing" = X,
        table "Sustainability EPR Material" = X,
        table "Sust. ESG Concept" = X,
        table "Sust. ESG Range Period" = X,
        table "Sust. ESG Requirement Concept" = X,
        table "Sust. ESG Standard Requirement" = X,
        table "Sustainability Disclaimer" = X,
        page "Chart of Sustain. Accounts" = X,
        page "Collect Amount from G/L Entry" = X,
        page "G/L Accounts Subform" = X,
        page "Sustainability Account Card" = X,
        page "Sustain. Account Categories" = X,
        page "Sustain. Category FactBox" = X,
        page "Sustain. Subcategory FactBox" = X,
        page "Sustainability Account List" = X,
        page "Sustain. Account Subcategories" = X,
        page "Sustainability Jnl. Templates" = X,
        page "Sustainability Jnl. Temp. List" = X,
        page "Sustainability Jnl. Batches" = X,
        page "Sustainability Journal" = X,
        page "Recurring Sustainability Jnl." = X,
        page "Sustainability Ledger Entries" = X,
        page "Sustainability Value Entries" = X,
        page "Sustainability Setup" = X,
        page "Sustain. Jnl. Errors Factbox" = X,
        page "Sustainability Accounts" = X,
        page "Sust. Account Categories" = X,
        page "Sust. Acc. Subcategory" = X,
        page "Sustainability Journal Line" = X,
        page "Sustainability Ledg. Entries" = X,
        page "Emission Fees" = X,
        page "Emission Scope Ratio Chart" = X,
        page "Headline Sustainability RC" = X,
        page "Sust. Accs. (Analysis View)" = X,
        page "Sust. Certificate Areas" = X,
        page "Sust. Certificate Card" = X,
        page "Sust. Certificate Standards" = X,
        page "Sustainability Activities" = X,
        page "Sustainability Certificates" = X,
        page "Sustainability Goal Cue" = X,
        page "Sustainability Goals" = X,
        page "Sustainability Manager RC" = X,
        page "Sustainability Scorecard" = X,
        page "Sustainability Scorecards" = X,
        page "Sustainability Energy Sources" = X,
        page "Sust. ESG Report. Aggregation" = X,
        page "Sust. ESG Reporting Names" = X,
        page "Sust. ESG Reporting Prev. Line" = X,
        page "Sust. ESG Reporting Preview" = X,
        page "Sust. ESG Reporting Templates" = X,
        page "Sust. ESG Reporting Tmpl. List" = X,
        page "Sust. Posted ESG Report" = X,
        page "Sust. Posted ESG Reports" = X,
        page "Sust. Posted ESG Report Sub." = X,
        page "Sust. Assessment List" = X,
        page "Sust. Assessment Req. List" = X,
        page "Sust. ESG Fact List" = X,
        page "Sust. ESG Reporting Lines" = X,
        page "Sust. ESG Reporting Units" = X,
        page "Sust. ESG Standards" = X,
        page "Sust. ESG Unit List" = X,
        page "Sust. Posted ESG Report Lines" = X,
        page "Sust. Standard List" = X,
        page "CH4 Emission Ratio Chart" = X,
        page "CO2e Emission Ratio Chart" = X,
        page "N2O Emission Ratio Chart" = X,
        page "Sust. Excise Jnl. Batches" = X,
        page "Sust. Excise Jnl. Temp. List" = X,
        page "Sust. Excise Jnl. Templates" = X,
        page "Sust. Excise Taxes Trans. Logs" = X,
        page "Sust. Item Mat. Comp. Factbox" = X,
        page "Sust. Item Mat. Comp. Lines" = X,
        page "Sust. Item Mat. Comp. List" = X,
        page "Sust. Item Mat. Composition" = X,
        page "Sustainability Carbon Pricing" = X,
        page "Sustainability EPR Materials" = X,
        page "Sustainability Excise Journal" = X,
        page "Waste Intensity Ratio Chart" = X,
        page "Water Intensity Bar Chart" = X,
        page "Water Intensity Ratio Chart" = X,
        page "Water Type Intensity Bar Chart" = X,
        page "Sust. Concept List" = X,
        page "Sust. ESG Concepts" = X,
        page "Sust. ESG Range Periods" = X,
        page "Sust. ESG Requirement Concepts" = X,
        page "Sust. ESG Std. Requirements" = X,
        page "Sust. Range Period List" = X,
        page "Sust. Requirement Concept List" = X,
        page "Sust. Std. Requirement List" = X,
        page "Sustainability Disclaimer" = X,
        codeunit "Sustainability Account Mgt." = X,
        codeunit "Sustainability Journal Mgt." = X,
        codeunit "Sustainability Jnl.-Post" = X,
        codeunit "Sustainability Recur Jnl.-Post" = X,
        codeunit "Sustainability Post Mgt" = X,
        codeunit "Sustainability Jnl.-Check" = X,
        codeunit "Sustainability Calculation" = X,
        codeunit "Sustainability Calc. Mgt." = X,
        codeunit "Sustain. Jnl. Errors Mgt." = X,
        codeunit "Check Sust. Jnl. Line. Backgr." = X,
        codeunit "Acc. Sch. Line Mgmt. Helper" = X,
        codeunit "Acc. Schedule Line Subscribers" = X,
        codeunit "Analysis View Entry Subscriber" = X,
        codeunit AnalysisViewEntryToSustEntries = X,
        codeunit "Compute Sust. Goal Cue" = X,
        codeunit "Install Sustainability Setup" = X,
        codeunit "RC Headline Page Sust." = X,
        codeunit "Sust. Acc. Analysis View Mgt." = X,
        codeunit "Sust. Certificate Subscribers" = X,
        codeunit "Sust. Preview Post Instance" = X,
        codeunit "Sust. Preview Post. Subscriber" = X,
        codeunit "Sust. Preview Posting Handler" = X,
        codeunit "Sustainability Chart Mgmt." = X,
        codeunit "Sust. CaptionClass Mgt" = X,
        codeunit "Sust. ESG Reporting Helper Mgt" = X,
        codeunit "Sust. ESG Reporting Post. Mgt" = X,
        codeunit "Sust. ESG Reporting Management" = X,
        codeunit "Sust. Approvals Mgmt." = X,
        codeunit "Sust. Excise Cal. Mgt" = X,
        codeunit "Sust. Excise Jnl.-Check" = X,
        codeunit "Sust. Excise Jnl.-Post" = X,
        codeunit "Sust. Excise Journal Mgt." = X,
        codeunit "Sust. Item Mat. Comp.-Copy" = X,
        codeunit "Sust. Workflow Event Handling" = X,
        codeunit "Sustainability Excise Post Mgt" = X,
        report "Emission By Category" = X,
        report "Emission Per Facility" = X,
        report "Total Emissions" = X,
        report "Batch Update Carbon Emission" = X,
        report "Sust. Calculate CO2e" = X,
        report "Sust. Item Calculate CO2e" = X,
        report "Sust. Prod. BOM Calculate CO2e" = X,
        report "Sust. Resource Calculate CO2e" = X,
        report "Sust. Routing Calculate CO2e" = X,
        report "Sust. CSRD Preparation" = X,
        report "Sust. Track Item of Concern" = X;
}