// ------------------------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// ------------------------------------------------------------------------------------------------

PermissionSet 219 "System Application - Objects"
{
    Access = Internal;
    Assignable = false;

    IncludedPermissionSets = "Advanced Settings - Objects",
                             "Auto Format - Objects",
                             "Azure AD Graph - Objects",
                             "Azure AD Licensing - Objects",
                             "Azure AD Plan - Objects",
                             "Azure AD Tenant - Objects",
                             "Azure AD User - Objects",
                             "AAD User Management - Objects",
                             "Azure Blob S. API - Objects",
                             "Azure Key Vault - Objects",
                             "Az. Storage S. Auth. - Objects",
                             "Barcode - Objects",
                             "Base64 Convert - Objects",
                             "BLOB Storage - Objects",
                             "Business Chart - Objects",
                             "Camera and Media - Objects",
                             "Caption Class - Objects",
                             "Client Type Mgt. - Objects",
                             "Confirm Management - Objects",
                             "Cryptography Mgt. - Objects",
                             "Cues and KPIs - Objects",
                             "Data Archive - Objects",
                             "Data Classification - Objects",
                             "Data Compression - Objects",
                             "Date-Time Dialog - Objects",
                             "Default Role Center - Objects",
                             "Device - Objects",
                             "Document Sharing - Objects",
                             "Edit in Excel - Objects",
                             "Email - Objects",
                             "Encoding - Objects",
                             "Environment Info. - Objects",
                             "Extension Management - Objects",
                             "Feature Key - Objects",
                             "Field Selection - Objects",
                             "Filter Tokens - Objects",
                             "Geolocation - Objects",
                             "Guided Experience - Objects",
                             "Headlines - Objects",
                             "Image - Objects",
                             "Language - Objects",
                             "Math - Objects",
                             "Navigation Bar Subs. - Objects",
                             "OAuth - Objects",
                             "OAuth2 - Objects",
                             "Object Selection - Objects",
                             "Page Summary Provider - Obj.",
                             "Password - Objects",
                             "Performance Profiler - Objects",
                             "Printer Management - Objects",
                             "Record Link Management - Obj.",
                             "Recurrence Schedule - Objects",
                             "Regex - Objects",
                             "Retention Policy - Objects",
#if not CLEAN20
                             "Sandbox Cleanup - Objects",
#endif
                             "Environment Cleanup - Objects",
                             "Satisfaction Survey - Objects",
                             "Secrets - Objects",
                             "System Initialization - Obj.",
                             "Table Information - Objects",
                             "Telemetry - Objects",
                             "Tenant License State - Objects",
                             "Time Zone Selection - Objects",
                             "Translation - Objects",
                             "Upgrade Tags - Objects",
                             "URI - Objects",
                             "User Login Times - Objects",
                             "User Permissions - Objects",
                             "User Selection - Objects",
                             "User Settings - Objects",
                             "Video - Objects",
                             "Web Service Management - Obj.",
                             "Word Templates - Objects",
                             "XML Validation - Objects",
                             "XmlWriter - Objects";
}
