namespace Microsoft.DataMigration.GP.HistoricalData;

permissionset 40900 "GP Historical Trx."
{
    Assignable = true;
    Access = Public;
    Caption = 'GP Historical Transactions';
    Permissions = page "Hist. Gen. Journal Lines" = X,
        page "Hist. G/L Account List" = X,
        page "Hist. Inventory Trx." = X,
        page "Hist. Inventory Trx. Headers" = X,
        page "Hist. Inventory Trx. Lines" = X,
        page "Hist. Payables Document" = X,
        page "Hist. Payables Documents" = X,
        page "Hist. Purchase Recv." = X,
        page "Hist. Purchase Recv. Headers" = X,
        page "Hist. Purchase Recv. Lines" = X,
        page "Hist. Receivables Document" = X,
        page "Hist. Receivables Documents" = X,
        page "Hist. Sales Trx." = X,
        page "Hist. Sales Trx. Headers" = X,
        page "Hist. Sales Trx. Lines" = X,
        page "Hist. Migration Step Status" = X,
        page "Hist. Payables Apply" = X,
        page "Hist. Payables Apply List" = X,
        page "Hist. Payables Document List" = X,
        page "Hist. Receivables Apply" = X,
        page "Hist. Receivables Apply List" = X,
        page "Hist. Recv. Document List" = X,
        tabledata "Hist. G/L Account" = RIMD,
        tabledata "Hist. Gen. Journal Line" = RIMD,
        tabledata "Hist. Inventory Trx. Header" = RIMD,
        tabledata "Hist. Inventory Trx. Line" = RIMD,
        tabledata "Hist. Invt. Trx. SerialLot" = RIMD,
        tabledata "Hist. Migration Current Status" = RIMD,
        tabledata "Hist. Migration Step Status" = RIMD,
        tabledata "Hist. Payables Apply" = RIMD,
        tabledata "Hist. Payables Document" = RIMD,
        tabledata "Hist. Purchase Recv. Header" = RIMD,
        tabledata "Hist. Purchase Recv. Line" = RIMD,
        tabledata "Hist. Receivables Apply" = RIMD,
        tabledata "Hist. Receivables Document" = RIMD,
        tabledata "Hist. Recv. Trx. SerialLot" = RIMD,
        tabledata "Hist. Sales Trx. Header" = RIMD,
        tabledata "Hist. Sales Trx. Line" = RIMD,
        table "Hist. G/L Account" = X,
        table "Hist. Gen. Journal Line" = X,
        table "Hist. Inventory Trx. Header" = X,
        table "Hist. Inventory Trx. Line" = X,
        table "Hist. Invt. Trx. SerialLot" = X,
        table "Hist. Migration Current Status" = X,
        table "Hist. Migration Step Status" = X,
        table "Hist. Payables Apply" = X,
        table "Hist. Payables Document" = X,
        table "Hist. Purchase Recv. Header" = X,
        table "Hist. Purchase Recv. Line" = X,
        table "Hist. Receivables Apply" = X,
        table "Hist. Receivables Document" = X,
        table "Hist. Recv. Trx. SerialLot" = X,
        table "Hist. Sales Trx. Header" = X,
        table "Hist. Sales Trx. Line" = X,
        codeunit "Hist. Migration Status Mgmt." = X,
        codeunit "Hist. Page Navigation Handler" = X,
        page "Hist. Invt. Trx. SerialLot" = X,
        page "Hist. Invt. Trx. SerlLot. List" = X,
        page "Hist. Recv. Trx. SerialLot" = X,
        page "Hist. Recv. Trx. SerlLot. List" = X;
}