codeunit 5253 "Create Post Code"
{
    InherentEntitlements = X;
    InherentPermissions = X;

    // TODO: MS
    // Discuss it
    // Maybe a service provide a better list of post codes?
    // This can be the same for now, then we convert to a list later.

    // Keep as it is for now
    // Wael

    trigger OnRun()
    var
    begin
        InsertData('AT-1100', 'Wien', 'WIEN', 'AT', '', '');
        InsertData('AT-1230', 'Wien', 'WIEN', 'AT', '', '');
        InsertData('AT-2355', 'Wr. Neudorf', 'WR. NEUDORF', 'AT', '', '');
        InsertData('AT-4810', 'Gmunden', 'GMUNDEN', 'AT', '', '');
        InsertData('AT-5730', 'Mittersill', 'MITTERSILL', 'AT', '', '');
        InsertData('AT-8850', 'Murau', 'MURAU', 'AT', '', '');
        InsertData('AU-2000', 'Sydney, NSW', 'SYDNEY, NSW', 'AU', '', '');
        InsertData('AU-2500', 'Wollongong, NSW', 'WOLLONGONG, NSW', 'AU', '', '');
        InsertData('AU-3000', 'Melbourne, VIC', 'MELBOURNE, VIC', 'AU', '', '');
        InsertData('AU-4000', 'Brisbane, QLD', 'BRISBANE, QLD', 'AU', '', '');
        InsertData('AU-6800', 'Perth, WA', 'PERTH, WA', 'AU', '', '');
        InsertData('AU-7178', 'Murdunna, TAS', 'MURDUNNA, TAS', 'AU', '', '');
        InsertData('B27 4KT', 'Birmingham', 'BIRMINGHAM', 'GB', '', '');
        InsertData('B31 2AL', 'Birmingham', 'BIRMINGHAM', 'GB', '', '');
        InsertData('B32 4TF', 'Sparkhill, Birmingham', 'SPARKHILL, BIRMINGHAM', 'GB', '', '');
        InsertData('B68 5TT', 'Bromsgrove', 'BROMSGROVE', 'GB', '', '');
        InsertData('BA24 6KS', 'Bath', 'BATH', 'GB', '', '');
        InsertData('BE-1851', 'Humbeek', 'HUMBEEK', 'BE', '', '');
        InsertData('BE-2050', 'Antwerpen', 'ANTWERPEN', 'BE', '', '');
        InsertData('BE-2200', 'Herentals', 'HERENTALS', 'BE', '', '');
        InsertData('BE-2800', 'Mechelen', 'MECHELEN', 'BE', '', '');
        InsertData('BE-3000', 'Leuven', 'LEUVEN', 'BE', '', '');
        InsertData('BE-8500', 'Kortrijk', 'KORTRIJK', 'BE', '', '');
        InsertData('BG-1000', 'Sofia', 'SOFIA', 'BG', '', '');
        InsertData('BG-2500', 'Kustendil', 'KUSTENDIL', 'BG', '', '');
        InsertData('BG-2700', 'Blagoevgrad', 'BLAGOEVGRAD', 'BG', '', '');
        InsertData('BG-4000', 'Plovdiv', 'PLOVDIV', 'BG', '', '');
        InsertData('BG-8700', 'Elhovo', 'ELHOVO', 'BG', '', '');
        InsertData('BG-9000', 'Varna', 'VARNA', 'BG', '', '');
        InsertData('BR 05428-002', 'Sao Paulo SP', 'SAO PAULO SP', 'BR', '', '');
        InsertData('BR 22291-040', 'Rio de Janeiro RJ', 'RIO DE JANEIRO RJ', 'BR', '', '');
        InsertData('BR 51021-040', 'Recife PE', 'RECIFE PE', 'BR', '', '');
        InsertData('BR 70710-926', 'Brasilia DF', 'BRASILIA DF', 'BR', '', '');
        InsertData('BR 80020-290', 'Curitiba PR', 'CURITIBA PR', 'BR', '', '');
        InsertData('BR 90040-130', 'Porto Alegre RS', 'PORTO ALEGRE RS', 'BR', '', '');
        InsertData('BR1 2ES', 'Bromley', 'BROMLEY', 'GB', '', '');
        InsertData('BS3 6KL', 'Bristol', 'BRISTOL', 'GB', '', '');
        InsertData('CA-MB R0M 0N0', 'Elkhorn', 'ELKHORN', 'CA', '', '');
        InsertData('CA-ON L6J 3J3', 'Oakville', 'OAKVILLE', 'CA', '', '');
        InsertData('CA-ON M5E 1G5', 'Toronto', 'TORONTO', 'CA', '', '');
        InsertData('CA-ON N6B 1V7', 'London', 'LONDON', 'CA', '', '');
        InsertData('CA-ON P7A 4K8', 'Thunder Bay', 'THUNDER BAY', 'CA', '', '');
        InsertData('CA-ON P7B 5E2', 'Thunder Bay', 'THUNDER BAY', 'CA', '', '');
        InsertData('CB1 2FB', 'Cambridge', 'CAMBRIDGE', 'GB', '', '');
        InsertData('CB3 7GG', 'Cambridge', 'CAMBRIDGE', 'GB', '', '');
        InsertData('CF22 1XU', 'Cardiff', 'CARDIFF', 'GB', '', '');
        InsertData('CH-4133', 'Pratteln', 'PRATTELN', 'CH', '', '');
        InsertData('CH-6005', 'Luzern', 'LUZERN', 'CH', '', '');
        InsertData('CH-6343', 'Rotkreuz', 'ROTKREUZ', 'CH', '', '');
        InsertData('CH-6405', 'Immensee', 'IMMENSEE', 'CH', '', '');
        InsertData('CH-8152', 'Glattbrugg', 'GLATTBRUGG', 'CH', '', '');
        InsertData('CH-8200', 'Schaffhausen', 'SCHAFFHAUSEN', 'CH', '', '');
        InsertData('CT6 21ND', 'Hythe', 'HYTHE', 'GB', '', '');
        InsertData('CV6 1GY', 'Coventry', 'COVENTRY', 'GB', '', '');
        InsertData('CV9 3QN', 'Atherstone', 'ATHERSTONE', 'GB', '', '');
        InsertData('CZ-669 02', 'Znojmo', 'ZNOJMO', 'CZ', '', '');
        InsertData('CZ-678 01', 'Blansko', 'BLANSKO', 'CZ', '', '');
        InsertData('CZ-687 71', 'Bojkovice', 'BOJKOVICE', 'CZ', '', '');
        InsertData('CZ-696 42', 'Vracov', 'VRACOV', 'CZ', '', '');
        InsertData('CZ-697 01', 'Kyjov', 'KYJOV', 'CZ', '', '');
        InsertData('CZ-779 00', 'Olomouch', 'OLOMOUCH', 'CZ', '', '');
        InsertData('DA5 3EF', 'Sidcup', 'SIDCUP', 'GB', '', '');
        InsertData('DE-20097', 'Hamburg', 'HAMBURG', 'DE', '', '');
        InsertData('DE-22417', 'Hamburg 36', 'HAMBURG 36', 'DE', '', '');
        InsertData('DE-40593', 'Dusseldorf', 'DUSSELDORF', 'DE', '', '');
        InsertData('DE-60320', 'Frankfurt/Main', 'FRANKFURT/MAIN', 'DE', '', '');
        InsertData('DE-72800', 'Eningen', 'ENINGEN', 'DE', '', '');
        InsertData('DE-80807', 'Munchen', 'MUNCHEN', 'DE', '', '');
        InsertData('DE-80997', 'Munchen', 'MUNCHEN', 'DE', '', '');
        InsertData('DE-86899', 'Landsberg am Lech', 'LANDSBERG AM LECH', 'DE', '', '');
        InsertData('DK-2100', 'Copenhagen', 'COPENHAGEN', 'DK', '', '');
        InsertData('DK-2950', 'Vedbaek', 'VEDBAEK', 'DK', '', '');
        InsertData('DK-4600', 'Koge', 'KOGE', 'DK', '', '');
        InsertData('DK-5000', 'Odense C', 'ODENSE C', 'DK', '', '');
        InsertData('DK-5800', 'Nyborg', 'NYBORG', 'DK', '', '');
        InsertData('DK-8000', 'Arhus C', 'ARHUS C', 'DK', '', '');
        InsertData('DK-8200', 'Arhus N', 'ARHUS N', 'DK', '', '');
        InsertData('DK-9000', 'Alborg', 'ALBORG', 'DK', '', '');
        InsertData('DY5 4DJ', 'Dudley', 'DUDLEY', 'GB', '', '');
        InsertData('DZ-05400', 'BARIKA', 'BARIKA', 'DZ', '', '');
        InsertData('DZ-16000', 'ALGIERS', 'ALGIERS', 'DZ', '', '');
        InsertData('DZ-16012', 'ALGIERS', 'ALGIERS', 'DZ', '', '');
        InsertData('DZ-16027', 'ALGIERS', 'ALGIERS', 'DZ', '', '');
        InsertData('DZ-21000', 'MOSTAGANCU', 'MOSTAGANCU', 'DZ', '', '');
        InsertData('DZ-40000', 'KHENCHE', 'KHENCHE', 'DZ', '', '');
        InsertData('E12 5TG', 'Edinburgh', 'EDINBURGH', 'GB', '', '');
        InsertData('EC2A 3JL', 'London', 'LONDON', 'GB', '', '');
        InsertData('EE-10127', 'Tallinn', 'TALLINN', 'EE', '', '');
        InsertData('EE-20607', 'Narva', 'NARVA', 'EE', '', '');
        InsertData('EE-44313', 'Rakvere', 'RAKVERE', 'EE', '', '');
        InsertData('EE-45109', 'Tapa', 'TAPA', 'EE', '', '');
        InsertData('EE-49603', 'Mustvee', 'MUSTVEE', 'EE', '', '');
        InsertData('EE-76806', 'Paldiski', 'PALDISKI', 'EE', '', '');
        InsertData('EH1 3EG', 'Edinburgh', 'EDINBURGH', 'GB', '', '');
        InsertData('EH16 8JS', 'Edinburgh', 'EDINBURGH', 'GB', '', '');
        InsertData('EL-106 75', 'Athens', 'ATHENS', 'EL', '', '');
        InsertData('EL-106 82', 'Athens', 'ATHENS', 'EL', '', '');
        InsertData('EL-185 40', 'Piraeus', 'PIRAEUS', 'EL', '', '');
        InsertData('EL-546 35', 'Thessaloniki', 'THESSALONIKI', 'EL', '', '');
        InsertData('EL-731 33', 'Chania', 'CHANIA', 'EL', '', '');
        InsertData('EL-851 03', 'Kolymbia', 'KOLYMBIA', 'EL', '', '');
        InsertData('ES-03003', 'Alicante', 'ALICANTE', 'ES', '', '');
        InsertData('ES-07001', 'Palma Mallorca', 'PALMA MALLORCA', 'ES', '', '');
        InsertData('ES-08010', 'Barcelona', 'BARCELONA', 'ES', '', '');
        InsertData('ES-10003', 'Caceres', 'CACERES', 'ES', '', '');
        InsertData('ES-28003', 'Madrid', 'MADRID', 'ES', '', '');
        InsertData('ES-36004', 'Pontevedra', 'PONTEVEDRA', 'ES', '', '');
        InsertData('ES-37001', 'Salamanca', 'SALAMANCA', 'ES', '', '');
        InsertData('ES-41006', 'Sevilla', 'SEVILLA', 'ES', '', '');
        InsertData('ES-46007', 'Valencia', 'VALENCIA', 'ES', '', '');
        InsertData('ES-47002', 'Valladolid', 'VALLADOLID', 'ES', '', '');
        InsertData('ES-50001', 'Zaragoza', 'ZARAGOZA', 'ES', '', '');
        InsertData('FI-00100', 'Helsinki', 'HELSINKI', 'FI', '', '');
        InsertData('FI-00101', 'Helsinki', 'HELSINKI', 'FI', '', '');
        InsertData('FI-00260', 'Helsinki', 'HELSINKI', 'FI', '', '');
        InsertData('FI-01800', 'Klaukkala', 'KLAUKKALA', 'FI', '', '');
        InsertData('FI-05400', 'Jokela', 'JOKELA', 'FI', '', '');
        InsertData('FI-88900', 'Kuhmo', 'KUHMO', 'FI', '', '');
        InsertData('FR-44450', 'LA CHAPELLE BASSE MER', 'LA CHAPELLE BASSE MER', 'FR', '', '');
        InsertData('FR-50670', 'CASSEL', 'CASSEL', 'FR', '', '');
        InsertData('FR-75000', 'PARIS', 'PARIS', 'FR', '', '');
        InsertData('FR-77450', 'ESBLY', 'ESBLY', 'FR', '', '');
        InsertData('FR-78370', 'PLAISIR', 'PLAISIR', 'FR', '', '');
        InsertData('FR-83250', 'LA LONDE LES MAURES', 'LA LONDE LES MAURES', 'FR', '', '');
        InsertData('GL1 9HM', 'Gloucester', 'GLOUCESTER', 'GB', '', '');
        InsertData('GL50 1TY', 'Cheltenham', 'CHELTENHAM', 'GB', '', '');
        InsertData('GL78 5TT', 'Cheltenham', 'CHELTENHAM', 'GB', '', '');
        InsertData('GU2 7XH', 'Guildford', 'GUILDFORD', 'GB', '', '');
        InsertData('GU2 7YQ', 'Guildford', 'GUILDFORD', 'GB', '', '');
        InsertData('GU3 2SE', 'Guildford', 'GUILDFORD', 'GB', '', '');
        InsertData('GU52 8DY', 'Fleet', 'FLEET', 'GB', '', '');
        InsertData('GU7 5GT', 'Guildford', 'GUILDFORD', 'GB', '', '');
        InsertData('HG1 7YW', 'Ripon', 'RIPON', 'GB', '', '');
        InsertData('HP43 2AY', 'Tring', 'TRING', 'GB', '', '');
        InsertData('HR-10000', 'Zagreb', 'ZAGREB', 'HR', '', '');
        InsertData('HR-20000', 'Dubrovnik', 'DUBROVNIK', 'HR', '', '');
        InsertData('HR-21000', 'Split', 'SPLIT', 'HR', '', '');
        InsertData('HR-22000', 'Sibenik', 'SIBENIK', 'HR', '', '');
        InsertData('HR-43000', 'Bjelovar', 'BJELOVAR', 'HR', '', '');
        InsertData('HR-52210', 'Rovinj', 'ROVINJ', 'HR', '', '');
        InsertData('HU-1107', 'Budapest', 'BUDAPEST', 'HU', '', '');
        InsertData('HU-1161', 'Budapest', 'BUDAPEST', 'HU', '', '');
        InsertData('HU-1204', 'Budapest', 'BUDAPEST', 'HU', '', '');
        InsertData('HU-2500', 'Esztergom', 'ESZTERGOM', 'HU', '', '');
        InsertData('HU-3258', 'Tarnalelesz', 'TARNALELESZ', 'HU', '', '');
        InsertData('HU-3325', 'Noszvaj', 'NOSZVAJ', 'HU', '', '');
        InsertData('IB7 7VN', 'Gainsborough', 'GAINSBOROUGH', 'GB', '', '');
        InsertData('ID-10310', 'Jakarta', 'JAKARTA', 'ID', '', '');
        InsertData('ID-10440', 'Jakarta', 'JAKARTA', 'ID', '', '');
        InsertData('ID-11470', 'Jakarta', 'JAKARTA', 'ID', '', '');
        InsertData('ID-15156', 'Tangerang', 'TANGERANG', 'ID', '', '');
        InsertData('ID-40135', 'Bandung', 'BANDUNG', 'ID', '', '');
        InsertData('ID-60172', 'Surabaya', 'SURABAYA', 'ID', '', '');
        InsertData('IN-110002', 'Delhi', 'DELHI', 'IN', '', '');
        InsertData('IN-400001', 'Mumbai', 'MUMBAI', 'IN', '', '');
        InsertData('IN-440001', 'Nagpur', 'NAGPUR', 'IN', '', '');
        InsertData('IN-560001', 'Bengaluru', 'BENGALURU', 'IN', '', '');
        InsertData('IN-600001', 'Chennai', 'CHENNAI', 'IN', '', '');
        InsertData('IN-700001', 'Kolkata', 'KOLKATA', 'IN', '', '');
        InsertData('IS-101', 'Reykjavik', 'REYKJAVIK', 'IS', '', '');
        InsertData('IS-108', 'Reykjavik', 'REYKJAVIK', 'IS', '', '');
        InsertData('IS-112', 'Reykjavik', 'REYKJAVIK', 'IS', '', '');
        InsertData('IS-200', 'Kopavogur', 'KOPAVOGUR', 'IS', '', '');
        InsertData('IS-220', 'Hafnafjordur', 'HAFNAFJORDUR', 'IS', '', '');
        InsertData('IS-300', 'Akranes', 'AKRANES', 'IS', '', '');
        InsertData('IT-00100', 'ROMA RM', 'ROMA RM', 'IT', '', '');
        InsertData('IT-10100', 'TORINO TO', 'TORINO TO', 'IT', '', '');
        InsertData('IT-20100', 'MILANO MI', 'MILANO MI', 'IT', '', '');
        InsertData('IT-39100', 'BOLZANO BZ', 'BOLZANO BZ', 'IT', '', '');
        InsertData('IT-61100', 'SANTA VENERANDA PS', 'SANTA VENERANDA PS', 'IT', '', '');
        InsertData('IT-67067', 'PESCINA AQ', 'PESCINA AQ', 'IT', '', '');
        InsertData('KE-0 0100', 'Nairobi', 'NAIROBI', 'KE', '', '');
        InsertData('KE-0 1007', 'Kairi', 'KAIRI', 'KE', '', '');
        InsertData('KE-5 0413', 'Adungosi', 'ADUNGOSI', 'KE', '', '');
        InsertData('KE-6 0500', 'Marsabit', 'MARSABIT', 'KE', '', '');
        InsertData('KE-8 0100', 'Mombasa', 'MOMBASA', 'KE', '', '');
        InsertData('KE-8 0200', 'Malindi', 'MALINDI', 'KE', '', '');
        InsertData('L18 6SA', 'Liverpool', 'LIVERPOOL', 'GB', '', '');
        InsertData('LE16 7YH', 'Leicester', 'LEICESTER', 'GB', '', '');
        InsertData('LL6 5GB', 'Rhyl', 'RHYL', 'GB', '', '');
        InsertData('LN23 6GS', 'Lincoln', 'LINCOLN', 'GB', '', '');
        InsertData('LT-2600', 'Vilnius', 'VILNIUS', 'LT', '', '');
        InsertData('LT-2700', 'Vilnius', 'VILNIUS', 'LT', '', '');
        InsertData('LT-3000', 'Kaunas', 'KAUNAS', 'LT', '', '');
        InsertData('LT-3042', 'Kaunas', 'KAUNAS', 'LT', '', '');
        InsertData('LT-4600', 'Rudiskes', 'RUDISKES', 'LT', '', '');
        InsertData('LT-5800', 'Klaipeda', 'KLAIPEDA', 'LT', '', '');
        InsertData('LU3 4FY', 'Luton', 'LUTON', 'GB', '', '');
        InsertData('LV-1011', 'Riga', 'RIGA', 'LV', '', '');
        InsertData('LV-1039', 'Riga', 'RIGA', 'LV', '', '');
        InsertData('LV-3270', 'Dundaga', 'DUNDAGA', 'LV', '', '');
        InsertData('LV-3900', 'Bauska', 'BAUSKA', 'LV', '', '');
        InsertData('LV-5002', 'Ogre', 'OGRE', 'LV', '', '');
        InsertData('LV-5113', 'Koknese', 'KOKNESE', 'LV', '', '');
        InsertData('M22 5TG', 'Manchester', 'MANCHESTER', 'GB', '', '');
        InsertData('M61 2YG', 'Manchester', 'MANCHESTER', 'GB', '', '');
        InsertData('MA-10100', 'AGDAL-RABAT', 'AGDAL-RABAT', 'MA', '', '');
        InsertData('MA-10101', 'RIAD-RABAT', 'RIAD-RABAT', 'MA', '', '');
        InsertData('MA-12000', 'TEMARA', 'TEMARA', 'MA', '', '');
        InsertData('MA-20000', 'CASABLANCA', 'CASABLANCA', 'MA', '', '');
        InsertData('MA-20200', 'CASABLANCA', 'CASABLANCA', 'MA', '', '');
        InsertData('MA-20800', 'MOHAMMEDIA', 'MOHAMMEDIA', 'MA', '', '');
        InsertData('MA-90000', 'KASBAH TANGER', 'KASBAH TANGER', 'MA', '', '');
        InsertData('ME5 6RL', 'Maidstone', 'MAIDSTONE', 'GB', '', '');
        InsertData('MK21 7GG', 'Bletchley', 'BLETCHLEY', 'GB', '', '');
        InsertData('MK41 5AE', 'Bedford', 'BEDFORD', 'GB', '', '');
        InsertData('MO2 4RT', 'Manchester', 'MANCHESTER', 'GB', '', '');
        InsertData('MX-01030', 'Mexico City, DF', 'MEXICO CITY, DF', 'MX', '', '');
        InsertData('MX-06000', 'Mexico City, DF', 'MEXICO CITY, DF', 'MX', '', '');
        InsertData('MX-37500', 'Leon, Guanajuato', 'LEON, GUANAJUATO', 'MX', '', '');
        InsertData('MX-64640', 'Monterrey, Nuevo Leon', 'MONTERREY, NUEVO LEON', 'MX', '', '');
        InsertData('MX-78030', 'San Luis Potosi, San Luis', 'SAN LUIS POTOSI, SAN LUIS', 'MX', '', '');
        InsertData('MX-82100', 'Mazatlan, Sinaloa', 'MAZATLAN, SINALOA', 'MX', '', '');
        InsertData('MY-42000', 'PELABUHAN KLANG, Selangor', 'PELABUHAN KLANG, SELANGOR', 'MY', '', '');
        InsertData('MY-47400', 'PETALING JAYA, Selangor', 'PETALING JAYA, SELANGOR', 'MY', '', '');
        InsertData('MY-50450', 'AMPANG, Kuala Lumpur', 'AMPANG, KUALA LUMPUR', 'MY', '', '');
        InsertData('MY-57000', 'KUALA LUMPUR', 'KUALA LUMPUR', 'MY', '', '');
        InsertData('MY-88100', 'KOTA KINABALU, Sabah', 'KOTA KINABALU, SABAH', 'MY', '', '');
        InsertData('MY-93450', 'KUCHING, Sarawak', 'KUCHING, SARAWAK', 'MY', '', '');
        InsertData('MZ-00300', 'Maputo', 'MAPUTO', 'MZ', '', '');
        InsertData('N12 5XY', 'London', 'LONDON', 'GB', '', '');
        InsertData('N16 34Z', 'London', 'LONDON', 'GB', '', '');
        InsertData('NE21 3YG', 'Newcastle', 'NEWCASTLE', 'GB', '', '');
        InsertData('NG-300001', 'BENIN, Edo state', 'BENIN, EDO STATE', 'NG', '', '');
        InsertData('NG-900001', 'ABUJA', 'ABUJA', 'NG', '', '');
        InsertData('NG-930283', 'JOS, Plateau state', 'JOS, PLATEAU STATE', 'NG', '', '');
        InsertData('NG-931104', 'GHOH, Plateau state', 'GHOH, PLATEAU STATE', 'NG', '', '');
        InsertData('NL-1009 AG', 'Amsterdam', 'AMSTERDAM', 'NL', '', '');
        InsertData('NL-1530 JM', 'Zaandam', 'ZAANDAM', 'NL', '', '');
        InsertData('NL-5132 EE', 'Waalwijk', 'WAALWIJK', 'NL', '', '');
        InsertData('NL-6827 BP', 'Arnhem', 'ARNHEM', 'NL', '', '');
        InsertData('NL-7202 BP', 'Zutphen', 'ZUTPHEN', 'NL', '', '');
        InsertData('NL-7321 HE', 'Apeldoorn', 'APELDOORN', 'NL', '', '');
        InsertData('NO-0552', 'Oslo', 'OSLO', 'NO', '', '');
        InsertData('NO-0661', 'Oslo', 'OSLO', 'NO', '', '');
        InsertData('NO-1300', 'Sandvika', 'SANDVIKA', 'NO', '', '');
        InsertData('NO-1324', 'Lysaker', 'LYSAKER', 'NO', '', '');
        InsertData('NO-1344', 'Haslum', 'HASLUM', 'NO', '', '');
        InsertData('NO-1370', 'Asker', 'ASKER', 'NO', '', '');
        InsertData('NO-1400', 'Ski', 'SKI', 'NO', '', '');
        InsertData('NP10 8BE', 'Newport', 'NEWPORT', 'GB', '', '');
        InsertData('NP5 6GH', 'Newport', 'NEWPORT', 'GB', '', '');
        InsertData('NZ-1001', 'Auckland', 'AUCKLAND', 'NZ', '', '');
        InsertData('NZ-5473', 'Woodville', 'WOODVILLE', 'NZ', '', '');
        InsertData('NZ-5491', 'Dannevirke', 'DANNEVIRKE', 'NZ', '', '');
        InsertData('NZ-6001', 'Wellington', 'WELLINGTON', 'NZ', '', '');
        InsertData('NZ-7900', 'Hokitika', 'HOKITIKA', 'NZ', '', '');
        InsertData('NZ-8001', 'Christchurch', 'CHRISTCHURCH', 'NZ', '', '');
        InsertData('OX16 0UA', 'Cheddington', 'CHEDDINGTON', 'GB', '', '');
        InsertData('PE17 4RN', 'Cambridge', 'CAMBRIDGE', 'GB', '', '');
        InsertData('PE21 3TG', 'Peterborough', 'PETERBOROUGH', 'GB', '', '');
        InsertData('PE23 5IK', 'Kings Lynn', 'KINGS LYNN', 'GB', '', '');
        InsertData('PH-1000', 'Manila', 'MANILA', 'PH', '', '');
        InsertData('PH-1003', 'Santa Cruz, Manila', 'SANTA CRUZ, MANILA', 'PH', '', '');
        InsertData('PH-1012', 'Tondo, Manila', 'TONDO, MANILA', 'PH', '', '');
        InsertData('PH-1117', 'Capri, Quezon City', 'CAPRI, QUEZON CITY', 'PH', '', '');
        InsertData('PH-1440', 'Valenzuela', 'VALENZUELA', 'PH', '', '');
        InsertData('PH-7000', 'Zamboanga City', 'ZAMBOANGA CITY', 'PH', '', '');
        InsertData('PL 02-515', 'Warszawa', 'WARSZAWA', 'PL', '', '');
        InsertData('PL 11-430', 'Korsze', 'KORSZE', 'PL', '', '');
        InsertData('PL 14-510', 'Orneta', 'ORNETA', 'PL', '', '');
        InsertData('PL 15-660', 'Bialystok', 'BIALYSTOK', 'PL', '', '');
        InsertData('PL 45-418', 'Opole', 'OPOLE', 'PL', '', '');
        InsertData('PL 59-300', 'Lubin', 'LUBIN', 'PL', '', '');
        InsertData('PL14 5GB', 'Plymouth', 'PLYMOUTH', 'GB', '', '');
        InsertData('PO21 6HG', 'Southsea, Portsmouth', 'SOUTHSEA, PORTSMOUTH', 'GB', '', '');
        InsertData('PO7 2HI', 'Portsmouth', 'PORTSMOUTH', 'GB', '', '');
        InsertData('PT 1050-042', 'LISBOA', 'LISBOA', 'PT', '', '');
        InsertData('PT 1100-150', 'LISBOA', 'LISBOA', 'PT', '', '');
        InsertData('PT 3000-337', 'COIMBRA', 'COIMBRA', 'PT', '', '');
        InsertData('PT 4000-322', 'PORTO', 'PORTO', 'PT', '', '');
        InsertData('PT 9000-064', 'FUNCHAL', 'FUNCHAL', 'PT', '', '');
        InsertData('PT 9500-101', 'PONTA DELGADA', 'PONTA DELGADA', 'PT', '', '');
        InsertData('RG6 1WG', 'Reading', 'READING', 'GB', '', '');
        InsertData('RO-050724', 'Bucuresti', 'BUCURESTI', 'RO', '', '');
        InsertData('RO-050729', 'Bucuresti', 'BUCURESTI', 'RO', '', '');
        InsertData('RO-051511', 'Bucuresti', 'BUCURESTI', 'RO', '', '');
        InsertData('RO-200331', 'Craiova', 'CRAIOVA', 'RO', '', '');
        InsertData('RO-500209', 'Brasov', 'BRASOV', 'RO', '', '');
        InsertData('RO-550264', 'Sibiu', 'SIBIU', 'RO', '', '');
        InsertData('RS-11000', 'Beograd', 'BEOGRAD', 'RS', '', '');
        InsertData('RS-11001', 'Beograd', 'BEOGRAD', 'RS', '', '');
        InsertData('RS-19210', 'Bor', 'BOR', 'RS', '', '');
        InsertData('RS-21000', 'Novi Sad', 'NOVI SAD', 'RS', '', '');
        InsertData('RS-24000', 'Subotica', 'SUBOTICA', 'RS', '', '');
        InsertData('RS-34000', 'Kragujevac', 'KRAGUJEVAC', 'RS', '', '');
        InsertData('RU-103054', 'Moskva', 'MOSKVA', 'RU', '', '');
        InsertData('RU-109456', 'Moskva', 'MOSKVA', 'RU', '', '');
        InsertData('RU-197342', 'Sankt Petersburg', 'SANKT PETERSBURG', 'RU', '', '');
        InsertData('RU-443008', 'Samara', 'SAMARA', 'RU', '', '');
        InsertData('RU-603061', 'Nizhny Novgorod', 'NIZHNY NOVGOROD', 'RU', '', '');
        InsertData('RU-690001', 'Vladivostok', 'VLADIVOSTOK', 'RU', '', '');
        InsertData('SA1 2HS', 'Swansea', 'SWANSEA', 'GB', '', '');
        InsertData('SA3 7HI', 'Stratford', 'STRATFORD', 'GB', '', '');
        InsertData('SE1 0AX', 'London', 'LONDON', 'GB', '', '');
        InsertData('SE-114 32', 'Stockholm', 'STOCKHOLM', 'SE', '', '');
        InsertData('SE-302 50', 'Halmstad', 'HALMSTAD', 'SE', '', '');
        InsertData('SE-415 06', 'Goteborg', 'GOTEBORG', 'SE', '', '');
        InsertData('SE-521 03', 'Kinnared', 'KINNARED', 'SE', '', '');
        InsertData('SE-550 05', 'Jonkobing', 'JONKOBING', 'SE', '', '');
        InsertData('SE-600 03', 'Norrkobing', 'NORRKOBING', 'SE', '', '');
        InsertData('SE-852 33', 'Sundsvall', 'SUNDSVALL', 'SE', '', '');
        InsertData('SG-038988', 'Singapore', 'SINGAPORE', 'SG', '', '');
        InsertData('SI-1000', 'Ljubljana', 'LJUBLJANA', 'SI', '', '');
        InsertData('SI-2000', 'Maribor', 'MARIBOR', 'SI', '', '');
        InsertData('SI-3231', 'Grobelno', 'GROBELNO', 'SI', '', '');
        InsertData('SI-4502', 'Kranj', 'KRANJ', 'SI', '', '');
        InsertData('SI-6000', 'Koper', 'KOPER', 'SI', '', '');
        InsertData('SI-8283', 'Blanca', 'BLANCA', 'SI', '', '');
        InsertData('SK-026 01', 'Dolny Kubin', 'DOLNY KUBIN', 'SK', '', '');
        InsertData('SK-049 21', 'Betliar', 'BETLIAR', 'SK', '', '');
        InsertData('SK21 5DL', 'Macclesfield', 'MACCLESFIELD', 'GB', '', '');
        InsertData('SK-813 38', 'Bratislava', 'BRATISLAVA', 'SK', '', '');
        InsertData('SK-821 04', 'Bratislava', 'BRATISLAVA', 'SK', '', '');
        InsertData('SK-905 01', 'Senica', 'SENICA', 'SK', '', '');
        InsertData('SK-985 01', 'Kalinovo', 'KALINOVO', 'SK', '', '');
        InsertData('SZ-H100', 'Mbabane', 'MBABANE', 'SZ', '', '');
        InsertData('SZ-H101', 'Swazi Plaza', 'SWAZI PLAZA', 'SZ', '', '');
        InsertData('SZ-H108', 'Piggs Peak', 'PIGGS PEAK', 'SZ', '', '');
        InsertData('SZ-H200', 'Manzini', 'MANZINI', 'SZ', '', '');
        InsertData('SZ-L300', 'Siteki', 'SITEKI', 'SZ', '', '');
        InsertData('SZ-S400', 'Nhlangano', 'NHLANGANO', 'SZ', '', '');
        InsertData('TA3 4FD', 'Newquay', 'NEWQUAY', 'GB', '', '');
        InsertData('TH-10260', 'Bang Na, Bangkok', 'BANG NA, BANGKOK', 'TH', '', '');
        InsertData('TH-10500', 'Bang Rak, Bangkok', 'BANG RAK, BANGKOK', 'TH', '', '');
        InsertData('TH-10510', 'Khlong Samwa, Bangkok', 'KHLONG SAMWA, BANGKOK', 'TH', '', '');
        InsertData('TH-17120', 'Wat Sing, Chai Nat', 'WAT SING, CHAI NAT', 'TH', '', '');
        InsertData('TH-31260', 'Non Dindaeng, Buri Ram', 'NON DINDAENG, BURI RAM', 'TH', '', '');
        InsertData('TH-50120', 'San Pa Tong, Chiang Mai', 'SAN PA TONG, CHIANG MAI', 'TH', '', '');
        InsertData('TN-1002', 'Tunis Belvedere', 'TUNIS BELVEDERE', 'TN', '', '');
        InsertData('TN-1030', 'Tunis', 'TUNIS', 'TN', '', '');
        InsertData('TN-1111', 'Zaghouan', 'ZAGHOUAN', 'TN', '', '');
        InsertData('TN27 6YD', 'Ashford', 'ASHFORD', 'GB', '', '');
        InsertData('TN-3100', 'Kairouan', 'KAIROUAN', 'TN', '', '');
        InsertData('TN-8129', 'Ain Draham', 'AIN DRAHAM', 'TN', '', '');
        InsertData('TN-8170', 'Bou Salem', 'BOU SALEM', 'TN', '', '');
        InsertData('TQ17 8HB', 'Brixham', 'BRIXHAM', 'GB', '', '');
        InsertData('TR-06531', 'Ankara', 'ANKARA', 'TR', '', '');
        InsertData('TR-42020', 'Konya', 'KONYA', 'TR', '', '');
        InsertData('TR-45030', 'Manisa', 'MANISA', 'TR', '', '');
        InsertData('TR-80080', 'Istanbul', 'ISTANBUL', 'TR', '', '');
        InsertData('TR-81420', 'Kartal-Istanbul', 'KARTAL-ISTANBUL', 'TR', '', '');
        InsertData('TR-81700', 'Tuzla-Istanbul', 'TUZLA-ISTANBUL', 'TR', '', '');
        InsertData('TZ-DSM', 'Dar Es Salaam', 'DAR ES SALAAM', 'TZ', '', '');
        InsertData('UG-EBB', 'Entebbe', 'ENTEBBE', 'UG', '', '');
        InsertData('UG-KLA', 'Kampala', 'KAMPALA', 'UG', '', '');
        InsertData('US-AL 35242', 'Birmingham', 'BIRMINGHAM', 'US', '', '');
        InsertData('US-FL 37125', 'Miami', 'MIAMI', 'US', 'FL', '');
        InsertData('US-GA 31772', 'Atlanta', 'ATLANTA', 'US', 'GA', '');
        InsertData('US-IL 61236', 'Chicago', 'CHICAGO', 'US', '', '');
        InsertData('US-NY 11010', 'New York', 'NEW YORK', 'US', '', '');
        InsertData('US-SC 27136', 'Colombia', 'COLOMBIA', 'US', '', '');
        InsertData('W1 3AL', 'London', 'LONDON', 'GB', '', '');
        InsertData('W2 6BD', 'London', 'LONDON', 'GB', '', '');
        InsertData('W2 8HG', 'London', 'LONDON', 'GB', '', '');
        InsertData('WC1 2GS', 'West End Lane', 'WEST END LANE', 'GB', '', '');
        InsertData('WC1 3DG', 'London', 'LONDON', 'GB', '', '');
        InsertData('WD1 6YG', 'Watford', 'WATFORD', 'GB', '', '');
        InsertData('WD2 4RG', 'Watford', 'WATFORD', 'GB', '', '');
        InsertData('WD6 8UY', 'Borehamwood', 'BOREHAMWOOD', 'GB', '', '');
        InsertData('WD6 9HY', 'Borehamwood', 'BOREHAMWOOD', 'GB', '', '');
        InsertData('ZA-0001', 'Pretoria', 'PRETORIA', 'ZA', '', '');
        InsertData('ZA-0700', 'Pietersburg', 'PIETERSBURG', 'ZA', '', '');
        InsertData('ZA-2000', 'Johannesburg', 'JOHANNESBURG', 'ZA', '', '');
        InsertData('ZA-2500', 'Carletonville', 'CARLETONVILLE', 'ZA', '', '');
        InsertData('ZA-2940', 'Newcastle', 'NEWCASTLE', 'ZA', '', '');
        InsertData('ZA-3600', 'Durban', 'DURBAN', 'ZA', '', '');
        InsertData('ZA-3900', 'Richards Bay', 'RICHARDS BAY', 'ZA', '', '');
        InsertData('ZA-6000', 'Port Elizabeth', 'PORT ELIZABETH', 'ZA', '', '');
        InsertData('ZA-8000', 'Cape Town', 'CAPE TOWN', 'ZA', '', '');
        InsertData('ZA-9300', 'Bloemfontein', 'BLOEMFONTEIN', 'ZA', '', '');
    end;

    procedure InsertData(Code: Text; City: Text; "Search City": Text; "Country/Region Code": Text; County: Text; "Time Zone": Text)
    var
        PostCode: Record "Post Code";
    begin
        PostCode.Code := Code;
        PostCode.City := City;
        PostCode."Search City" := "Search City";
        PostCode."Country/Region Code" := "Country/Region Code";
        PostCode.County := County;
        PostCode."Time Zone" := "Time Zone";
        if PostCode.Insert(false) then;
    end;
}
