codeunit 10832 "Create ES VAT Statement Line"
{
    InherentEntitlements = X;
    InherentPermissions = X;

    trigger OnRun()
    var
        ContosoCoffeeDemoDataSetup: Record "Contoso Coffee Demo Data Setup";
    begin
        ContosoCoffeeDemoDataSetup.Get();

        if ContosoCoffeeDemoDataSetup."Company Type" = ContosoCoffeeDemoDataSetup."Company Type"::"Sales Tax" then
            exit;

        CreateVATStatementLine();
    end;

    local procedure CreateVATStatementLine()
    var
        CreateVATPostingGroups: Codeunit "Create VAT Posting Groups";
        CreateVATStatement: Codeunit "Create VAT Statement";
        CreateESVATPostingGroup: Codeunit "Create ES VAT Posting Groups";
    begin
        ContosoVatStatement.SetOverwriteData(true);
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), StatementNameLbl, 10000, '1010', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Sale, CreateVATPostingGroups.Domestic(), CreateESVATPostingGroup.VAT21(), '', Enum::"VAT Statement Line Amount Type"::Amount, 0, false, 1, SalesVAT21outgoingLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), StatementNameLbl, 20000, '1020', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Sale, CreateVATPostingGroups.Domestic(), CreateESVATPostingGroup.VAT7(), '', Enum::"VAT Statement Line Amount Type"::Amount, 0, false, 1, SalesVAT7outgoingLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), StatementNameLbl, 30000, '1050', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Purchase, CreateVATPostingGroups.EU(), CreateESVATPostingGroup.VAT21(), '', Enum::"VAT Statement Line Amount Type"::Amount, 1, false, 1, VAT21onEUPurchasesetcLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), StatementNameLbl, 40000, '1060', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Purchase, CreateVATPostingGroups.EU(), CreateESVATPostingGroup.VAT7(), '', Enum::"VAT Statement Line Amount Type"::Amount, 1, false, 1, VAT7onEUPurchasesetcLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), StatementNameLbl, 50000, '1030', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Sale, CreateVATPostingGroups.Domestic(), CreateESVATPostingGroup.VAT4(), '', Enum::"VAT Statement Line Amount Type"::Amount, 0, false, 1, SalesVAT4outgoingLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), StatementNameLbl, 60000, '1070', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Purchase, CreateVATPostingGroups.EU(), CreateESVATPostingGroup.VAT4(), '', Enum::"VAT Statement Line Amount Type"::Amount, 1, false, 1, VAT4onEUPurchasesetcLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), StatementNameLbl, 70000, '', Enum::"VAT Statement Line Type"::Description, Enum::"General Posting Type"::" ", '', '', '', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 0, SeparationLineLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), StatementNameLbl, 80000, '1099', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', '1010..1090', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 1, TotalLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), StatementNameLbl, 90000, '', Enum::"VAT Statement Line Type"::Description, Enum::"General Posting Type"::" ", '', '', '', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 0, '', '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), StatementNameLbl, 100000, '1110', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Purchase, CreateVATPostingGroups.Domestic(), CreateESVATPostingGroup.VAT21(), '', Enum::"VAT Statement Line Amount Type"::Amount, 0, false, 0, PurchaseVAT21DomesticLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), StatementNameLbl, 110000, '1120', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Purchase, CreateVATPostingGroups.Domestic(), CreateESVATPostingGroup.VAT7(), '', Enum::"VAT Statement Line Amount Type"::Amount, 0, false, 0, PurchaseVAT7DomesticLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), StatementNameLbl, 120000, '1150', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Purchase, CreateVATPostingGroups.EU(), CreateESVATPostingGroup.VAT21(), '', Enum::"VAT Statement Line Amount Type"::Amount, 0, false, 0, PurchaseVAT21EULbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), StatementNameLbl, 130000, '1160', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Purchase, CreateVATPostingGroups.EU(), CreateESVATPostingGroup.VAT7(), '', Enum::"VAT Statement Line Amount Type"::Amount, 0, false, 0, PurchaseVAT7EULbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), StatementNameLbl, 140000, '1130', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Purchase, CreateVATPostingGroups.Domestic(), CreateESVATPostingGroup.VAT4(), '', Enum::"VAT Statement Line Amount Type"::Amount, 0, false, 0, PurchaseVAT4DomesticLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), StatementNameLbl, 150000, '1170', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Purchase, CreateVATPostingGroups.EU(), CreateESVATPostingGroup.VAT4(), '', Enum::"VAT Statement Line Amount Type"::Amount, 0, false, 0, PurchaseVAT4EULbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), StatementNameLbl, 160000, '1179', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', '1110..1170', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 1, PurchaseVATingoingLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), StatementNameLbl, 170000, '', Enum::"VAT Statement Line Type"::Description, Enum::"General Posting Type"::" ", '', '', '', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 0, SeparationLineLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), StatementNameLbl, 180000, '1199', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', '1159|1189', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 1, TotalDeductionsLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), StatementNameLbl, 190000, '', Enum::"VAT Statement Line Type"::Description, Enum::"General Posting Type"::" ", '', '', '', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 0, SeparationLineLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), StatementNameLbl, 200000, '', Enum::"VAT Statement Line Type"::Description, Enum::"General Posting Type"::" ", '', '', '', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 0, '', '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), StatementNameLbl, 210000, '', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', '1099|1199', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 1, VATPayableLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), StatementNameLbl, 220000, '', Enum::"VAT Statement Line Type"::Description, Enum::"General Posting Type"::" ", '', '', '', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 0, SeparationLineLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), StatementNameLbl, 230000, '', Enum::"VAT Statement Line Type"::Description, Enum::"General Posting Type"::" ", '', '', '', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 0, '', '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), StatementNameLbl, 240000, '1210', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Purchase, CreateVATPostingGroups.EU(), CreateESVATPostingGroup.VAT21(), '', Enum::"VAT Statement Line Amount Type"::Base, 0, false, 0, ValueofEUPurchases21Lbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), StatementNameLbl, 250000, '1220', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Purchase, CreateVATPostingGroups.EU(), CreateESVATPostingGroup.VAT7(), '', Enum::"VAT Statement Line Amount Type"::Base, 0, false, 0, ValueofEUPurchases7Lbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), StatementNameLbl, 260000, '1230', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Purchase, CreateVATPostingGroups.EU(), CreateESVATPostingGroup.VAT4(), '', Enum::"VAT Statement Line Amount Type"::Base, 0, false, 0, ValueofEUPurchases4Lbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), StatementNameLbl, 270000, '', Enum::"VAT Statement Line Type"::Description, Enum::"General Posting Type"::" ", '', '', '', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 0, '', '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), StatementNameLbl, 280000, '1240', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Sale, CreateVATPostingGroups.EU(), CreateESVATPostingGroup.VAT21(), '', Enum::"VAT Statement Line Amount Type"::Base, 0, false, 1, ValueofEUSales21Lbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), StatementNameLbl, 290000, '1250', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Sale, CreateVATPostingGroups.EU(), CreateESVATPostingGroup.VAT7(), '', Enum::"VAT Statement Line Amount Type"::Base, 0, false, 1, ValueofEUSales7Lbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), StatementNameLbl, 300000, '1260', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Sale, CreateVATPostingGroups.EU(), CreateESVATPostingGroup.VAT4(), '', Enum::"VAT Statement Line Amount Type"::Base, 0, false, 1, ValueofEUSales4Lbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), StatementNameLbl, 310000, '', Enum::"VAT Statement Line Type"::Description, Enum::"General Posting Type"::" ", '', '', '', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 0, '', '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), StatementNameLbl, 320000, '1310', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Sale, CreateVATPostingGroups.Export(), CreateESVATPostingGroup.VAT21(), '', Enum::"VAT Statement Line Amount Type"::Base, 0, false, 0, NonVATliablesalesOverseasLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), StatementNameLbl, 330000, '1320', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Sale, CreateVATPostingGroups.Export(), CreateESVATPostingGroup.VAT7(), '', Enum::"VAT Statement Line Amount Type"::Base, 0, false, 0, NonVATliablesalesOverseasLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), StatementNameLbl, 340000, '1330', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Sale, CreateVATPostingGroups.Export(), CreateESVATPostingGroup.VAT4(), '', Enum::"VAT Statement Line Amount Type"::Base, 0, false, 0, NonVATliablesalesOverseasLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), StatementNameLbl, 350000, '', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', '1310..1330', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 1, NonVATliablesalesOverseasLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), StatementNameLbl, 360000, '1340', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Sale, CreateVATPostingGroups.Domestic(), CreateESVATPostingGroup.NOVAT(), '', Enum::"VAT Statement Line Amount Type"::Base, 0, false, 0, NonVATliablesalesDomesticLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), StatementNameLbl, 370000, '', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', '1340..1348', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 1, NonVATliablesalesDomesticLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement320Lbl, 380000, '10', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Sale, CreateVATPostingGroups.Domestic(), CreateESVATPostingGroup.VAT21(), '', Enum::"VAT Statement Line Amount Type"::Amount, 0, false, 1, AmountSalesVAT16outgoingLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement320Lbl, 390000, 'B010', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Sale, CreateVATPostingGroups.Domestic(), CreateESVATPostingGroup.VAT21(), '', Enum::"VAT Statement Line Amount Type"::Base, 0, false, 1, BaseSalesVAT16outgoingLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement320Lbl, 400000, '19', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', '10..18', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 1, TotalAmountSalesVAT16outgoingLbl, '');
        UpdateBoxValue(CreateVATStatement.VATTemplateName(), Statement320Lbl, 400000, '3');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement320Lbl, 410000, 'B019', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', 'B010..B018', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 1, TotalBaseSalesVAT16outgoingLbl, '');
        UpdateBoxValue(CreateVATStatement.VATTemplateName(), Statement320Lbl, 410000, '1');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement320Lbl, 420000, '1D', Enum::"VAT Statement Line Type"::Description, Enum::"General Posting Type"::" ", '', '', '', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 0, SixteenLbl, '');
        UpdateBoxValue(CreateVATStatement.VATTemplateName(), Statement320Lbl, 420000, '2');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement320Lbl, 430000, '20', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Sale, CreateVATPostingGroups.Domestic(), CreateESVATPostingGroup.VAT7(), '', Enum::"VAT Statement Line Amount Type"::Amount, 0, false, 1, AmountSalesVAT7outgoingLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement320Lbl, 440000, 'B020', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Sale, CreateVATPostingGroups.Domestic(), CreateESVATPostingGroup.VAT7(), '', Enum::"VAT Statement Line Amount Type"::Base, 0, false, 1, BaseSalesVAT7outgoingLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement320Lbl, 450000, '29', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', '20..28', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 1, TotalAmountSalesVAT7outgoingLbl, '');
        UpdateBoxValue(CreateVATStatement.VATTemplateName(), Statement320Lbl, 450000, '6');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement320Lbl, 460000, 'B029', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', 'B020..B028', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 1, TotalBaseSalesVAT7outgoingLbl, '');
        UpdateBoxValue(CreateVATStatement.VATTemplateName(), Statement320Lbl, 460000, '4');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement320Lbl, 470000, '2D', Enum::"VAT Statement Line Type"::Description, Enum::"General Posting Type"::" ", '', '', '', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 0, SevenLbl, '');
        UpdateBoxValue(CreateVATStatement.VATTemplateName(), Statement320Lbl, 470000, '5');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement320Lbl, 480000, '30', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Purchase, CreateVATPostingGroups.EU(), CreateESVATPostingGroup.VAT21(), '', Enum::"VAT Statement Line Amount Type"::Amount, 1, false, 1, AmountVAT16onEUPurchasesetcLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement320Lbl, 490000, 'B030', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Purchase, CreateVATPostingGroups.EU(), CreateESVATPostingGroup.VAT21(), '', Enum::"VAT Statement Line Amount Type"::Base, 1, false, 1, BaseVAT16onEUPurchasesetcLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement320Lbl, 500000, '39', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', '30..38', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 1, TotalAmountVAT16onEUPurchasesetcLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement320Lbl, 510000, 'B039', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', 'B030..B038', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 1, TotalBaseVAT16onEUPurchasesetcLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement320Lbl, 520000, '40', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Purchase, CreateVATPostingGroups.EU(), CreateESVATPostingGroup.VAT7(), '', Enum::"VAT Statement Line Amount Type"::Amount, 1, false, 1, AmountVAT7onEUPurchasesetcLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement320Lbl, 530000, 'B040', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Purchase, CreateVATPostingGroups.EU(), CreateESVATPostingGroup.VAT7(), '', Enum::"VAT Statement Line Amount Type"::Base, 1, false, 1, BaseVAT7onEUPurchasesetcLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement320Lbl, 540000, '49', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', '40..48', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 1, TotalAmountVAT7onEUPurchasesetcLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement320Lbl, 550000, 'B049', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', 'B040..B048', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 1, BaseAmountVAT7onEUPurchasesetcLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement320Lbl, 560000, '50', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', '39|49', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 1, TotalAmountVATEUPurchasesetcLbl, '');
        UpdateBoxValue(CreateVATStatement.VATTemplateName(), Statement320Lbl, 560000, '20');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement320Lbl, 570000, 'B050', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', 'B039|B049', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 1, TotalBaseVATEUPurchasesetcLbl, '');
        UpdateBoxValue(CreateVATStatement.VATTemplateName(), Statement320Lbl, 570000, '19');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement320Lbl, 580000, '', Enum::"VAT Statement Line Type"::Description, Enum::"General Posting Type"::" ", '', '', '', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 0, SeparationLineLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement320Lbl, 590000, '99', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', '19|29|50', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 1, TotalDuedVATAmountLbl, '');
        UpdateBoxValue(CreateVATStatement.VATTemplateName(), Statement320Lbl, 590000, '21');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement320Lbl, 600000, '', Enum::"VAT Statement Line Type"::Description, Enum::"General Posting Type"::" ", '', '', '', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 0, SeparationLineLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement320Lbl, 610000, '110', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Purchase, CreateVATPostingGroups.Domestic(), CreateESVATPostingGroup.VAT21(), '', Enum::"VAT Statement Line Amount Type"::Amount, 0, false, 1, AmountPurchaseVAT16Lbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement320Lbl, 620000, 'B110', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Purchase, CreateVATPostingGroups.Domestic(), CreateESVATPostingGroup.VAT21(), '', Enum::"VAT Statement Line Amount Type"::Base, 0, false, 0, BasePurchaseVAT16Lbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement320Lbl, 630000, '119', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', '110..118', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 1, TotalAmountPurchaseVAT16Lbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement320Lbl, 640000, 'B119', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', 'B110..B118', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 0, TotalBasePurchaseVAT16Lbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement320Lbl, 650000, '120', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Purchase, CreateVATPostingGroups.Domestic(), CreateESVATPostingGroup.VAT7(), '', Enum::"VAT Statement Line Amount Type"::Amount, 0, false, 1, AmountPurchaseVAT7Lbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement320Lbl, 660000, 'B120', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Purchase, CreateVATPostingGroups.Domestic(), CreateESVATPostingGroup.VAT7(), '', Enum::"VAT Statement Line Amount Type"::Base, 0, false, 0, BasePurchaseVAT7Lbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement320Lbl, 670000, '129', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', '120..128', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 1, TotalAmountPurchaseVAT7Lbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement320Lbl, 680000, 'B129', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', 'B120..B128', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 0, TotalBasePurchaseVAT7Lbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement320Lbl, 690000, '130', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', '119|129', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 1, TotalAmountPurchasesLbl, '');
        UpdateBoxValue(CreateVATStatement.VATTemplateName(), Statement320Lbl, 690000, '23');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement320Lbl, 700000, 'B130', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', 'B119|B129', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 0, TotalBasePurchasesLbl, '');
        UpdateBoxValue(CreateVATStatement.VATTemplateName(), Statement320Lbl, 700000, '22');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement320Lbl, 710000, '131', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Purchase, CreateVATPostingGroups.EU(), CreateESVATPostingGroup.VAT21(), '', Enum::"VAT Statement Line Amount Type"::Amount, 0, false, 1, BasePurchaseVAT7EULbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement320Lbl, 720000, 'B131', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Purchase, CreateVATPostingGroups.EU(), CreateESVATPostingGroup.VAT21(), '', Enum::"VAT Statement Line Amount Type"::Base, 0, false, 0, BasePurchaseVAT16EULbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement320Lbl, 730000, '139', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', '131..138', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 1, TotalAmountPurchaseVAT16EULbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement320Lbl, 740000, 'B139', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', 'B131..B138', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 0, TotalBasePurchaseVAT16EULbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement320Lbl, 750000, '140', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Purchase, CreateVATPostingGroups.EU(), CreateESVATPostingGroup.VAT7(), '', Enum::"VAT Statement Line Amount Type"::Amount, 0, false, 1, AmountPurchaseVAT7EULbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement320Lbl, 760000, 'B140', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Purchase, CreateVATPostingGroups.EU(), CreateESVATPostingGroup.VAT7(), '', Enum::"VAT Statement Line Amount Type"::Base, 0, false, 0, BasePurchaseVAT7EULbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement320Lbl, 770000, '149', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', '140..148', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 1, TotalAmountPurchaseVAT7EULbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement320Lbl, 780000, 'B149', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', 'B140..B148', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 0, TotalBasePurchaseVAT7EULbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement320Lbl, 790000, '170', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', '139|149', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 1, TotalAmountPurchasesEULbl, '');
        UpdateBoxValue(CreateVATStatement.VATTemplateName(), Statement320Lbl, 790000, '27');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement320Lbl, 800000, 'B170', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', 'B139|B149', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 0, TotalBasePurchasesUELbl, '');
        UpdateBoxValue(CreateVATStatement.VATTemplateName(), Statement320Lbl, 800000, '26');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement320Lbl, 810000, '', Enum::"VAT Statement Line Type"::Description, Enum::"General Posting Type"::" ", '', '', '', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 0, '', '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement320Lbl, 820000, '', Enum::"VAT Statement Line Type"::Description, Enum::"General Posting Type"::" ", '', '', '', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 0, SeparationLineLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement320Lbl, 830000, '199', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', '130|170', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 1, TotalDeductionsLbl, '');
        UpdateBoxValue(CreateVATStatement.VATTemplateName(), Statement320Lbl, 830000, '30');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement320Lbl, 840000, '', Enum::"VAT Statement Line Type"::Description, Enum::"General Posting Type"::" ", '', '', '', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 0, SeparationLineLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement320Lbl, 850000, '', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', '99|199', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 0, DifferenceLbl, '');
        UpdateBoxValue(CreateVATStatement.VATTemplateName(), Statement320Lbl, 850000, '31');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement320Lbl, 860000, '', Enum::"VAT Statement Line Type"::Description, Enum::"General Posting Type"::" ", '', '', '', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 0, SeparationLineLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement320Lbl, 870000, '', Enum::"VAT Statement Line Type"::Description, Enum::"General Posting Type"::" ", '', '', '', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 0, '', '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement320Lbl, 880000, '230', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Sale, CreateVATPostingGroups.EU(), CreateESVATPostingGroup.VAT21(), '', Enum::"VAT Statement Line Amount Type"::Base, 0, false, 1, ValueofEUSales21Lbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement320Lbl, 890000, '240', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Sale, CreateVATPostingGroups.EU(), CreateESVATPostingGroup.VAT7(), '', Enum::"VAT Statement Line Amount Type"::Base, 0, false, 1, ValueofEUSales7Lbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement320Lbl, 900000, '250', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', '230|240', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 1, ValueofEUSalesLbl, '');
        UpdateBoxValue(CreateVATStatement.VATTemplateName(), Statement320Lbl, 900000, '35');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement320Lbl, 910000, '310', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Sale, CreateVATPostingGroups.Export(), CreateESVATPostingGroup.VAT21(), '', Enum::"VAT Statement Line Amount Type"::Base, 0, false, 0, NonVATliablesalesOverseasLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement320Lbl, 920000, '311', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Sale, CreateVATPostingGroups.Export(), CreateESVATPostingGroup.VAT7(), '', Enum::"VAT Statement Line Amount Type"::Base, 0, false, 0, NonVATliablesalesOverseasLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement320Lbl, 930000, '319', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', '310|311', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 1, NonVATliablesalesOverseasLbl, '');
        UpdateBoxValue(CreateVATStatement.VATTemplateName(), Statement320Lbl, 930000, '36');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement320Lbl, 940000, '320', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Sale, CreateVATPostingGroups.Domestic(), CreateESVATPostingGroup.NOVAT(), '', Enum::"VAT Statement Line Amount Type"::Base, 0, false, 0, NonVATliablesalesDomesticLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement320Lbl, 950000, '329', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', '320..328', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 1, NonVATliablesalesDomesticLbl, '');
        UpdateBoxValue(CreateVATStatement.VATTemplateName(), Statement320Lbl, 950000, '37');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 960000, '10', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Sale, CreateVATPostingGroups.Domestic(), CreateESVATPostingGroup.VAT21(), '', Enum::"VAT Statement Line Amount Type"::Amount, 0, false, 1, AmountSalesVAT16outgoingLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 970000, 'B010', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Sale, CreateVATPostingGroups.Domestic(), CreateESVATPostingGroup.VAT21(), '', Enum::"VAT Statement Line Amount Type"::Base, 0, false, 1, BaseSalesVAT16outgoingLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 980000, '19', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', '10..18', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 1, TotalAmountSalesVAT16outgoingLbl, '');
        UpdateBoxValue(CreateVATStatement.VATTemplateName(), Statement392Lbl, 980000, '6');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 990000, 'B019', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', 'B010..B018', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 1, TotalBaseSalesVAT16outgoingLbl, '');
        UpdateBoxValue(CreateVATStatement.VATTemplateName(), Statement392Lbl, 990000, '5');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1000000, '1D', Enum::"VAT Statement Line Type"::Description, Enum::"General Posting Type"::" ", '', '', '', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 0, SixteenLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1010000, '20', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Sale, CreateVATPostingGroups.Domestic(), CreateESVATPostingGroup.VAT7(), '', Enum::"VAT Statement Line Amount Type"::Amount, 0, false, 1, AmountSalesVAT7outgoingLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1020000, 'B020', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Sale, CreateVATPostingGroups.Domestic(), CreateESVATPostingGroup.VAT7(), '', Enum::"VAT Statement Line Amount Type"::Base, 0, false, 1, BaseSalesVAT7outgoingLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1030000, '29', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', '20..28', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 1, TotalAmountSalesVAT7outgoingLbl, '');
        UpdateBoxValue(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1030000, '4');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1040000, 'B029', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', 'B020..B028', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 1, TotalBaseSalesVAT7outgoingLbl, '');
        UpdateBoxValue(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1040000, '3');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1050000, '2D', Enum::"VAT Statement Line Type"::Description, Enum::"General Posting Type"::" ", '', '', '', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 0, SevenLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1060000, '30', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Sale, CreateVATPostingGroups.Domestic(), CreateESVATPostingGroup.VAT4(), '', Enum::"VAT Statement Line Amount Type"::Amount, 0, false, 1, AmountSalesVAT4outgoingLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1070000, 'B030', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Sale, CreateVATPostingGroups.Domestic(), CreateESVATPostingGroup.VAT4(), '', Enum::"VAT Statement Line Amount Type"::Base, 0, false, 1, BaseSalesVAT4outgoingLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1080000, '39', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', '30..38', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 1, TotalAmountSalesVAT4outgoingLbl, '');
        UpdateBoxValue(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1080000, '2');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1090000, 'B039', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', 'B030..B038', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 1, TotalBaseSalesVAT4outgoingLbl, '');
        UpdateBoxValue(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1090000, '1');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1100000, '3D', Enum::"VAT Statement Line Type"::Description, Enum::"General Posting Type"::" ", '', '', '', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 0, FourLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1110000, '4D', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', '19|29|39', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 1, TotalAmountSalesVATLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1120000, '5D', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', 'B019|B029|B039', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 1, TotalBaseSalesVATLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1130000, '', Enum::"VAT Statement Line Type"::Description, Enum::"General Posting Type"::" ", '', '', '', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 0, SeparationLineLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1140000, '40', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Sale, CreateVATPostingGroups.EU(), CreateESVATPostingGroup.VAT21(), '', Enum::"VAT Statement Line Amount Type"::Amount, 0, false, 1, AmountVAT16onEUSalesetcLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1150000, 'B040', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Sale, CreateVATPostingGroups.EU(), CreateESVATPostingGroup.VAT21(), '', Enum::"VAT Statement Line Amount Type"::Base, 0, false, 1, BaseVAT16onEUSalesetcLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1160000, '49', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', '40..48', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 1, TotalAmountVAT16onEUSalesetcLbl, '');
        UpdateBoxValue(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1160000, '26');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1170000, 'B049', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', 'B040..B048', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 1, TotalBaseVAT16onEUSalesetcLbl, '');
        UpdateBoxValue(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1170000, '25');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1180000, '50', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Sale, CreateVATPostingGroups.EU(), CreateESVATPostingGroup.VAT7(), '', Enum::"VAT Statement Line Amount Type"::Amount, 0, false, 1, AmountVAT7onEUSalesetcLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1190000, 'B050', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Sale, CreateVATPostingGroups.EU(), CreateESVATPostingGroup.VAT7(), '', Enum::"VAT Statement Line Amount Type"::Base, 0, false, 1, BaseVAT7onEUSalesetcLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1200000, '59', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', '50..58', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 1, TotalAmountVAT7onEUSalesetcLbl, '');
        UpdateBoxValue(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1200000, '24');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1210000, 'B059', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', 'B050..B058', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 1, TotalBaseVAT7onEUSalesetcLbl, '');
        UpdateBoxValue(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1210000, '23');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1220000, '60', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Sale, CreateVATPostingGroups.EU(), CreateESVATPostingGroup.VAT4(), '', Enum::"VAT Statement Line Amount Type"::Amount, 0, false, 1, AmountVAT4onEUSalesetcLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1230000, 'B060', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Sale, CreateVATPostingGroups.EU(), CreateESVATPostingGroup.VAT4(), '', Enum::"VAT Statement Line Amount Type"::Base, 0, false, 1, BaseVAT4onEUSalesetcLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1240000, '69', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', '60..68', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 1, TotalAmountVAT4onEUSalesetcLbl, '');
        UpdateBoxValue(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1240000, '22');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1250000, 'B069', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', 'B060..B068', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 0, TotalBaseVAT4onEUSalesetcLbl, '');
        UpdateBoxValue(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1250000, '21');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1260000, '6D', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', '49|59|69', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 1, TotalAmountVATEUSalesLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1270000, '7D', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', 'B049|B059|B069', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 1, TotalBaseVATEUSalesLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1280000, '', Enum::"VAT Statement Line Type"::Description, Enum::"General Posting Type"::" ", '', '', '', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 0, SeparationLineLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1290000, '1T', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', '4D|6D', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 1, TotalDuedVATAmountLbl, '');
        UpdateBoxValue(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1290000, '34');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1300000, '1TB', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', '5D|7D', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 1, TotalDuedBaseVATLbl, '');
        UpdateBoxValue(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1300000, '33');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1310000, '', Enum::"VAT Statement Line Type"::Description, Enum::"General Posting Type"::" ", '', '', '', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 0, SeparationLineLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1320000, '110', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Purchase, CreateVATPostingGroups.Domestic(), CreateESVATPostingGroup.VAT21(), '', Enum::"VAT Statement Line Amount Type"::Amount, 0, false, 0, AmountPurchaseVAT16Lbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1330000, 'B110', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Purchase, CreateVATPostingGroups.Domestic(), CreateESVATPostingGroup.VAT21(), '', Enum::"VAT Statement Line Amount Type"::Base, 0, false, 0, BasePurchaseVAT16Lbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1340000, '119', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', '110..118', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 0, TotalAmountPurchaseVAT16Lbl, '');
        UpdateBoxValue(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1340000, '195');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1350000, 'B119', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', 'B110..B118', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 0, TotalBasePurchaseVAT16Lbl, '');
        UpdateBoxValue(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1350000, '194');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1360000, '120', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Purchase, CreateVATPostingGroups.Domestic(), CreateESVATPostingGroup.VAT7(), '', Enum::"VAT Statement Line Amount Type"::Amount, 0, false, 0, AmountPurchaseVAT7Lbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1370000, 'B120', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Purchase, CreateVATPostingGroups.Domestic(), CreateESVATPostingGroup.VAT7(), '', Enum::"VAT Statement Line Amount Type"::Base, 0, false, 0, BasePurchaseVAT7Lbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1380000, '129', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', '120..128', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 0, TotalAmountPurchaseVAT7Lbl, '');
        UpdateBoxValue(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1380000, '193');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1390000, 'B129', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', 'B120..B128', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 0, TotalBasePurchaseVAT7Lbl, '');
        UpdateBoxValue(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1390000, '192');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1400000, '130', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Purchase, CreateVATPostingGroups.Domestic(), CreateESVATPostingGroup.VAT4(), '', Enum::"VAT Statement Line Amount Type"::Amount, 0, false, 0, AmountPurchaseVAT4Lbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1410000, 'B130', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Purchase, CreateVATPostingGroups.Domestic(), CreateESVATPostingGroup.VAT4(), '', Enum::"VAT Statement Line Amount Type"::Base, 0, false, 0, BasePurchaseVAT4Lbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1420000, '139', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', '130..138', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 0, TotalAmountPurchaseVAT4Lbl, '');
        UpdateBoxValue(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1420000, '191');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1430000, 'B139', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', 'B130..B138', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 0, TotalBasePurchaseVAT4Lbl, '');
        UpdateBoxValue(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1430000, '190');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1440000, '8D', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', '119|129|139', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 0, TotalAmountPurchasesVATLbl, '');
        UpdateBoxValue(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1440000, '49');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1450000, '9D', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', 'B119|B129|B139', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 0, TotalBasePurchasesVATLbl, '');
        UpdateBoxValue(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1450000, '48');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1460000, '', Enum::"VAT Statement Line Type"::Description, Enum::"General Posting Type"::" ", '', '', '', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 0, SeparationLineLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1470000, '140', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Purchase, CreateVATPostingGroups.EU(), CreateESVATPostingGroup.VAT21(), '', Enum::"VAT Statement Line Amount Type"::Amount, 0, false, 0, AmountPurchaseVAT16EULbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1480000, 'B140', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Purchase, CreateVATPostingGroups.EU(), CreateESVATPostingGroup.VAT21(), '', Enum::"VAT Statement Line Amount Type"::Base, 0, false, 0, BasePurchaseVAT16EULbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1490000, '149', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', '140..148', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 0, TotalAmountPurchaseVAT16EULbl, '');
        UpdateBoxValue(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1490000, '219');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1500000, 'B149', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', 'B140..B148', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 0, TotalBasePurchaseVAT16EULbl, '');
        UpdateBoxValue(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1500000, '218');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1510000, '150', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::Purchase, CreateVATPostingGroups.EU(), CreateESVATPostingGroup.VAT7(), '', Enum::"VAT Statement Line Amount Type"::Amount, 0, false, 0, AmountPurchaseVAT7EULbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1520000, 'B150', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Purchase, CreateVATPostingGroups.EU(), CreateESVATPostingGroup.VAT7(), '', Enum::"VAT Statement Line Amount Type"::Base, 0, false, 0, BasePurchaseVAT7EULbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1530000, '159', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', '150..158', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 0, TotalAmountPurchaseVAT7EULbl, '');
        UpdateBoxValue(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1530000, '217');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1540000, 'B159', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', 'B150..B158', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 0, TotalBasePurchaseVAT7EULbl, '');
        UpdateBoxValue(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1540000, '216');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1550000, '160', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Purchase, CreateVATPostingGroups.EU(), CreateESVATPostingGroup.VAT4(), '', Enum::"VAT Statement Line Amount Type"::Amount, 0, false, 0, AmountPurchaseVAT4EULbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1560000, 'B160', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Purchase, CreateVATPostingGroups.EU(), CreateESVATPostingGroup.VAT4(), '', Enum::"VAT Statement Line Amount Type"::Base, 0, false, 0, BasePurchaseVAT4EULbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1570000, '169', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', '160..168', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 0, TotalAmountPurchaseVAT4EULbl, '');
        UpdateBoxValue(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1570000, '215');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1580000, 'B169', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', 'B160..B168', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 0, TotalBasePurchaseVAT4EULbl, '');
        UpdateBoxValue(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1580000, '214');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1590000, '10D', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', '149|159|169', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 0, TotalAmountPurchasesEULbl, '');
        UpdateBoxValue(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1590000, '57');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1600000, '11D', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', 'B149|B159|B169', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 0, TotalBasePurchasesUELbl, '');
        UpdateBoxValue(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1600000, '56');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1610000, '', Enum::"VAT Statement Line Type"::Description, Enum::"General Posting Type"::" ", '', '', '', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 0, '', '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1620000, '', Enum::"VAT Statement Line Type"::Description, Enum::"General Posting Type"::" ", '', '', '', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 0, SeparationLineLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1630000, '2T', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', '8D|10D', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 1, TotalDeductionsLbl, '');
        UpdateBoxValue(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1630000, '64');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1640000, '', Enum::"VAT Statement Line Type"::Description, Enum::"General Posting Type"::" ", '', '', '', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 0, SeparationLineLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1650000, '3T', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', '1T|2T', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 0, DifferenceLbl, '');
        UpdateBoxValue(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1650000, '65');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1660000, '', Enum::"VAT Statement Line Type"::Description, Enum::"General Posting Type"::" ", '', '', '', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 0, SeparationLineLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1670000, '', Enum::"VAT Statement Line Type"::Description, Enum::"General Posting Type"::" ", '', '', '', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 0, '', '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1680000, '230', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Sale, CreateVATPostingGroups.EU(), CreateESVATPostingGroup.VAT21(), '', Enum::"VAT Statement Line Amount Type"::Base, 0, false, 1, ValueofEUSales21Lbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1690000, '240', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Sale, CreateVATPostingGroups.EU(), CreateESVATPostingGroup.VAT7(), '', Enum::"VAT Statement Line Amount Type"::Base, 0, false, 1, ValueofEUSales7Lbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1700000, '250', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Sale, CreateVATPostingGroups.EU(), CreateESVATPostingGroup.VAT4(), '', Enum::"VAT Statement Line Amount Type"::Base, 0, false, 1, ValueofEUSales4Lbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1710000, '260', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', '230|240|250', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 1, TotalValueofEUSalesLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1720000, '310', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Sale, CreateVATPostingGroups.Export(), CreateESVATPostingGroup.VAT21(), '', Enum::"VAT Statement Line Amount Type"::Base, 0, false, 1, NonVATliablesalesOverseas16Lbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1730000, '311', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Sale, CreateVATPostingGroups.Export(), CreateESVATPostingGroup.VAT7(), '', Enum::"VAT Statement Line Amount Type"::Base, 0, false, 1, NonVATliablesalesOverseas7Lbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1740000, '312', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Sale, CreateVATPostingGroups.Export(), CreateESVATPostingGroup.VAT4(), '', Enum::"VAT Statement Line Amount Type"::Base, 0, false, 1, NonVATliablesalesOverseas4Lbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1750000, '319', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', '310|311|312', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 1, TotalNonVATliablesalesOverseasLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1760000, '320', Enum::"VAT Statement Line Type"::"VAT Entry Totaling", Enum::"General Posting Type"::Sale, CreateVATPostingGroups.Domestic(), CreateESVATPostingGroup.NOVAT(), '', Enum::"VAT Statement Line Amount Type"::Base, 0, false, 1, NonVATliablesalesDomesticLbl, '');
        ContosoVatStatement.InsertVatStatementLine(CreateVATStatement.VATTemplateName(), Statement392Lbl, 1770000, '329', Enum::"VAT Statement Line Type"::"Row Totaling", Enum::"General Posting Type"::" ", '', '', '320..328', Enum::"VAT Statement Line Amount Type"::" ", 0, true, 1, TotalNonVATliablesalesDomesticLbl, '');
        ContosoVatStatement.SetOverwriteData(false);
    end;

    local procedure UpdateBoxValue(StatementTemplateName: Code[10]; StatementName: Code[10]; StatementLineNo: Integer; StatementBox: Code[5])
    var
        VatStatementLine: Record "VAT Statement Line";
    begin
        if not VatStatementLine.Get(StatementTemplateName, StatementName, StatementLineNo) then
            exit;

        VatStatementLine.Validate(Box, StatementBox);
        VatStatementLine.Modify(true);
    end;

    var
        ContosoVatStatement: Codeunit "Contoso VAT Statement";
        StatementNameLbl: Label 'DEFAULT', MaxLength = 10;
        Statement320Lbl: Label 'STMT. 320', MaxLength = 10;
        Statement392Lbl: Label 'STMT. 392', MaxLength = 10;
        SalesVAT21outgoingLbl: Label 'Sales VAT 21 % (outgoing)', MaxLength = 100;
        SalesVAT7outgoingLbl: Label 'Sales VAT 7 % (outgoing)', MaxLength = 100;
        VAT21onEUPurchasesetcLbl: Label 'VAT 21 % % on EU Purchases etc.', MaxLength = 100;
        VAT7onEUPurchasesetcLbl: Label 'VAT 7 % % on EU Purchases etc.', MaxLength = 100;
        SalesVAT4outgoingLbl: Label 'Sales VAT 4 % (outgoing)', MaxLength = 100;
        VAT4onEUPurchasesetcLbl: Label 'VAT 4 % % on EU Purchases etc.', MaxLength = 100;
        SeparationLineLbl: Label '--------------------------------------------------', MaxLength = 100;
        TotalLbl: Label 'Total', MaxLength = 100;
        PurchaseVAT21DomesticLbl: Label 'Purchase VAT 21 % Domestic', MaxLength = 100;
        PurchaseVAT7DomesticLbl: Label 'Purchase VAT 7 % Domestic', MaxLength = 100;
        PurchaseVAT21EULbl: Label 'Purchase VAT 21 % EU', MaxLength = 100;
        PurchaseVAT7EULbl: Label 'Purchase VAT 7 % EU', MaxLength = 100;
        PurchaseVAT4DomesticLbl: Label 'Purchase VAT 4 % Domestic', MaxLength = 100;
        PurchaseVAT4EULbl: Label 'Purchase VAT 4 % EU', MaxLength = 100;
        PurchaseVATingoingLbl: Label 'Purchase VAT (ingoing)', MaxLength = 100;
        TotalDeductionsLbl: Label 'Total Deductions', MaxLength = 100;
        VATPayableLbl: Label 'VAT Payable', MaxLength = 100;
        ValueofEUPurchases21Lbl: Label 'Value of EU Purchases 21 %', MaxLength = 100;
        ValueofEUPurchases7Lbl: Label 'Value of EU Purchases 7 %', MaxLength = 100;
        ValueofEUPurchases4Lbl: Label 'Value of EU Purchases 4 %', MaxLength = 100;
        ValueofEUSales21Lbl: Label 'Value of EU Sales 21 %', MaxLength = 100;
        ValueofEUSales7Lbl: Label 'Value of EU Sales 7 %', MaxLength = 100;
        ValueofEUSales4Lbl: Label 'Value of EU Sales 4 %', MaxLength = 100;
        NonVATliablesalesOverseasLbl: Label 'Non-VAT liable sales, Overseas', MaxLength = 100;
        NonVATliablesalesDomesticLbl: Label 'Non-VAT liable sales, Domestic', MaxLength = 100;
        AmountSalesVAT16outgoingLbl: Label 'Amount Sales VAT 16 % (outgoing)', MaxLength = 100;
        BaseSalesVAT16outgoingLbl: Label 'Base Sales VAT 16 % (outgoing)', MaxLength = 100;
        TotalAmountSalesVAT16outgoingLbl: Label 'Total Amount Sales VAT 16 % (outgoing)', MaxLength = 100;
        TotalBaseSalesVAT16outgoingLbl: Label 'Total Base Sales VAT 16 % (outgoing)', MaxLength = 100;
        SixteenLbl: Label '16', MaxLength = 100;
        AmountSalesVAT7outgoingLbl: Label 'Amount Sales VAT 7 % (outgoing)', MaxLength = 100;
        BaseSalesVAT7outgoingLbl: Label 'Base Sales VAT 7 % (outgoing)', MaxLength = 100;
        TotalAmountSalesVAT7outgoingLbl: Label 'Total Amount Sales VAT 7 % (outgoing)', MaxLength = 100;
        TotalBaseSalesVAT7outgoingLbl: Label 'Total Base Sales VAT 7 % (outgoing)', MaxLength = 100;
        SevenLbl: Label '7', MaxLength = 100;
        AmountVAT16onEUPurchasesetcLbl: Label 'Amount VAT 16 % on EU Purchases etc.', MaxLength = 100;
        BaseVAT16onEUPurchasesetcLbl: Label 'Base VAT 16 % on EU Purchases etc.', MaxLength = 100;
        TotalAmountVAT16onEUPurchasesetcLbl: Label 'Total Amount VAT 16 % on EU Purchases etc.', MaxLength = 100;
        TotalBaseVAT16onEUPurchasesetcLbl: Label 'Total Base VAT 16 % on EU Purchases etc.', MaxLength = 100;
        AmountVAT7onEUPurchasesetcLbl: Label 'Amount VAT 7 % on EU Purchases etc.', MaxLength = 100;
        BaseVAT7onEUPurchasesetcLbl: Label 'Base VAT 7 % on EU Purchases etc.', MaxLength = 100;
        TotalAmountVAT7onEUPurchasesetcLbl: Label 'Total Amount VAT 7 % on EU Purchases etc.', MaxLength = 100;
        BaseAmountVAT7onEUPurchasesetcLbl: Label 'Base Amount VAT 7 % on EU Purchases etc.', MaxLength = 100;
        TotalAmountVATEUPurchasesetcLbl: Label 'Total Amount VAT EU Purchases etc.', MaxLength = 100;
        TotalBaseVATEUPurchasesetcLbl: Label 'Total Base VAT EU Purchases etc.', MaxLength = 100;
        TotalDuedVATAmountLbl: Label 'Total Dued VAT Amount', MaxLength = 100;
        AmountPurchaseVAT16Lbl: Label 'Amount Purchase VAT 16 %', MaxLength = 100;
        BasePurchaseVAT16Lbl: Label 'Base Purchase VAT 16 %', MaxLength = 100;
        TotalAmountPurchaseVAT16Lbl: Label 'Total Amount Purchase VAT 16 %', MaxLength = 100;
        TotalBasePurchaseVAT16Lbl: Label 'Total Base Purchase VAT 16 %', MaxLength = 100;
        AmountPurchaseVAT7Lbl: Label 'Amount Purchase VAT 7 %', MaxLength = 100;
        BasePurchaseVAT7Lbl: Label 'Base Purchase VAT 7 %', MaxLength = 100;
        TotalAmountPurchaseVAT7Lbl: Label 'Total Amount Purchase VAT 7 %', MaxLength = 100;
        TotalBasePurchaseVAT7Lbl: Label 'Total Base Purchase VAT 7 %', MaxLength = 100;
        TotalAmountPurchasesLbl: Label 'Total Amount Purchases', MaxLength = 100;
        TotalBasePurchasesLbl: Label 'Total Base Purchases', MaxLength = 100;
        BasePurchaseVAT7EULbl: Label 'Base Purchase VAT 7 % EU', MaxLength = 100;
        BasePurchaseVAT16EULbl: Label 'Base Purchase VAT 16 % EU', MaxLength = 100;
        TotalAmountPurchaseVAT16EULbl: Label 'Total Amount Purchase VAT 16 % EU', MaxLength = 100;
        TotalBasePurchaseVAT16EULbl: Label 'Total Base Purchase VAT 16 % EU', MaxLength = 100;
        AmountPurchaseVAT7EULbl: Label 'Amount Purchase VAT 7 % EU', MaxLength = 100;
        TotalAmountPurchaseVAT7EULbl: Label 'Total Amount Purchase VAT 7 % EU', MaxLength = 100;
        TotalBasePurchaseVAT7EULbl: Label 'Total Base Purchase VAT 7 % EU', MaxLength = 100;
        TotalAmountPurchasesEULbl: Label 'Total Amount Purchases EU', MaxLength = 100;
        TotalBasePurchasesUELbl: Label 'Total Base Purchases UE', MaxLength = 100;
        DifferenceLbl: Label 'Difference', MaxLength = 100;
        ValueofEUSalesLbl: Label 'Value of EU Sales', MaxLength = 100;
        AmountSalesVAT4outgoingLbl: Label 'Amount Sales VAT 4 % (outgoing)', MaxLength = 100;
        BaseSalesVAT4outgoingLbl: Label 'Base Sales VAT 4 % (outgoing)', MaxLength = 100;
        TotalAmountSalesVAT4outgoingLbl: Label 'Total Amount Sales VAT 4 % (outgoing)', MaxLength = 100;
        TotalBaseSalesVAT4outgoingLbl: Label 'Total Base Sales VAT 4 % (outgoing)', MaxLength = 100;
        FourLbl: Label '4', MaxLength = 100;
        TotalAmountSalesVATLbl: Label 'Total Amount Sales VAT', MaxLength = 100;
        TotalBaseSalesVATLbl: Label 'Total Base Sales VAT', MaxLength = 100;
        AmountVAT16onEUSalesetcLbl: Label 'Amount VAT 16 % on EU Sales etc.', MaxLength = 100;
        BaseVAT16onEUSalesetcLbl: Label 'Base VAT 16 % on EU Sales etc.', MaxLength = 100;
        TotalAmountVAT16onEUSalesetcLbl: Label 'Total Amount VAT 16 % on EU Sales etc.', MaxLength = 100;
        TotalBaseVAT16onEUSalesetcLbl: Label 'Total Base VAT 16 % on EU Sales etc.', MaxLength = 100;
        AmountVAT7onEUSalesetcLbl: Label 'Amount VAT 7 % on EU Sales etc.', MaxLength = 100;
        BaseVAT7onEUSalesetcLbl: Label 'Base VAT 7 % on EU Sales etc.', MaxLength = 100;
        TotalAmountVAT7onEUSalesetcLbl: Label 'Total Amount VAT 7 % on EU Sales etc.', MaxLength = 100;
        TotalBaseVAT7onEUSalesetcLbl: Label 'Total Base VAT 7 % on EU Sales etc.', MaxLength = 100;
        AmountVAT4onEUSalesetcLbl: Label 'Amount VAT 4 % on EU Sales etc.', MaxLength = 100;
        BaseVAT4onEUSalesetcLbl: Label 'Base VAT 4 % on EU Sales etc.', MaxLength = 100;
        TotalAmountVAT4onEUSalesetcLbl: Label 'Total Amount VAT 4 % on EU Sales etc.', MaxLength = 100;
        TotalBaseVAT4onEUSalesetcLbl: Label 'Total Base VAT 4 % on EU Sales etc.', MaxLength = 100;
        TotalAmountVATEUSalesLbl: Label 'Total Amount VAT EU Sales', MaxLength = 100;
        TotalBaseVATEUSalesLbl: Label 'Total Base VAT EU Sales', MaxLength = 100;
        TotalDuedBaseVATLbl: Label 'Total Dued Base VAT', MaxLength = 100;
        AmountPurchaseVAT4Lbl: Label 'Amount Purchase VAT 4 %', MaxLength = 100;
        BasePurchaseVAT4Lbl: Label 'Base Purchase VAT 4 %', MaxLength = 100;
        TotalAmountPurchaseVAT4Lbl: Label 'Total Amount Purchase VAT 4 %', MaxLength = 100;
        TotalBasePurchaseVAT4Lbl: Label 'Total Base Purchase VAT 4 %', MaxLength = 100;
        TotalAmountPurchasesVATLbl: Label 'Total Amount Purchases VAT', MaxLength = 100;
        TotalBasePurchasesVATLbl: Label 'Total Base Purchases VAT', MaxLength = 100;
        AmountPurchaseVAT16EULbl: Label 'Amount Purchase VAT 16 % EU', MaxLength = 100;
        AmountPurchaseVAT4EULbl: Label 'Amount Purchase VAT 4 % EU', MaxLength = 100;
        BasePurchaseVAT4EULbl: Label 'Base Purchase VAT 4 % EU', MaxLength = 100;
        TotalAmountPurchaseVAT4EULbl: Label 'Total Amount Purchase VAT 4 % EU', MaxLength = 100;
        TotalBasePurchaseVAT4EULbl: Label 'Total Base Purchase VAT 4 % EU', MaxLength = 100;
        TotalValueofEUSalesLbl: Label 'Total Value of EU Sales ', MaxLength = 100;
        NonVATliablesalesOverseas16Lbl: Label 'Non-VAT liable sales, Overseas 16%', MaxLength = 100;
        NonVATliablesalesOverseas7Lbl: Label 'Non-VAT liable sales, Overseas 7%', MaxLength = 100;
        NonVATliablesalesOverseas4Lbl: Label 'Non-VAT liable sales, Overseas 4%', MaxLength = 100;
        TotalNonVATliablesalesOverseasLbl: Label 'Total Non-VAT liable sales, Overseas', MaxLength = 100;
        TotalNonVATliablesalesDomesticLbl: Label 'Total Non-VAT liable sales, Domestic', MaxLength = 100;
}