codeunit 11125 "Create DE Data Export Record"
{
    InherentEntitlements = X;
    InherentPermissions = X;

    trigger OnRun()
    begin
        CreateDataExportRecordDefinition();
        CreateDataExportRecordSource();
        CreateDataExportRecordField();
        CreateDataExportTableRelation();
    end;

    local procedure CreateDataExportRecordDefinition()
    var
        CreateDEDataExport: Codeunit "Create DE Data Export";
        CreateDEDataExpRecType: Codeunit "Create DE Data Exp. Rec. Type";
        ContosoDEDigitalAudit: Codeunit "Contoso DE Digital Audit";
    begin
        ContosoDEDigitalAudit.InsertDataExportRecordDefinition(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode());
        ContosoDEDigitalAudit.InsertDataExportRecordDefinition(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData());
        ContosoDEDigitalAudit.InsertDataExportRecordDefinition(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData());
        ContosoDEDigitalAudit.InsertDataExportRecordDefinition(CreateDEDataExport.ItemData(), CreateDEDataExpRecType.ItemData());
    end;

    local procedure CreateDataExportRecordSource()
    var
        CreateDEDataExport: Codeunit "Create DE Data Export";
        CreateDEDataExpRecType: Codeunit "Create DE Data Exp. Rec. Type";
        ContosoDEDigitalAudit: Codeunit "Contoso DE Digital Audit";
    begin
        ContosoDEDigitalAudit.InsertDataExportRecordSource(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 10000, Database::"G/L Account", 0, 0, 0, 0, GL_AccountFileNameLbl);
        ContosoDEDigitalAudit.InsertDataExportRecordSource(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 20000, Database::"G/L Entry", 1, Database::"G/L Account", 10000, 4, GL_EntryFileNameLbl);
        ContosoDEDigitalAudit.InsertDataExportRecordSource(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 30000, Database::"Customer", 0, 0, 0, 0, CustomerFileNameLbl);
        ContosoDEDigitalAudit.InsertDataExportRecordSource(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 40000, Database::"Cust. Ledger Entry", 1, Database::"Customer", 30000, 4, Cust_LedgerFileNameLbl);
        ContosoDEDigitalAudit.InsertDataExportRecordSource(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 50000, Database::"Vendor", 0, 0, 0, 0, VendorFileNameLbl);
        ContosoDEDigitalAudit.InsertDataExportRecordSource(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 60000, Database::"Vendor Ledger Entry", 1, Database::"Vendor", 50000, 4, Vend_LedgerFileNameLbl);
        ContosoDEDigitalAudit.InsertDataExportRecordSource(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 70000, Database::"VAT Entry", 0, 0, 0, 4, VAT_EntryFileNameLbl);
        ContosoDEDigitalAudit.InsertDataExportRecordSource(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 10000, Database::"Fixed Asset", 0, 0, 0, 0, FixedAssetFileNameLbl);
        ContosoDEDigitalAudit.InsertDataExportRecordSource(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 20000, Database::"FA Ledger Entry", 1, Database::"Fixed Asset", 10000, 5, FALedgerEntryFileNameLbl);
        ContosoDEDigitalAudit.InsertDataExportRecordSource(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 30000, Database::"FA Depreciation Book", 1, Database::"Fixed Asset", 10000, 0, FADepreciationBookFileNameLbl);
        ContosoDEDigitalAudit.InsertDataExportRecordSource(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 40000, Database::"FA Posting Group", 0, 0, 0, 0, FAPostingGroupFileNameLbl);
        ContosoDEDigitalAudit.InsertDataExportRecordSource(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 10000, Database::"Country/Region", 0, 0, 0, 0, CountryRegionFileNameLbl);
        ContosoDEDigitalAudit.InsertDataExportRecordSource(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 20000, Database::"G/L Account", 0, 0, 0, 0, GLAccountFileNameLbl);
        ContosoDEDigitalAudit.InsertDataExportRecordSource(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 30000, Database::"G/L Entry", 1, Database::"G/L Account", 20000, 4, GLEntryFileNameLbl);
        ContosoDEDigitalAudit.InsertDataExportRecordSource(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 40000, Database::"Customer", 0, 0, 0, 0, CustomerFileNameLbl);
        ContosoDEDigitalAudit.InsertDataExportRecordSource(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 50000, Database::"Cust. Ledger Entry", 1, Database::"Customer", 40000, 4, CustLedgerEntryFileNameLbl);
        ContosoDEDigitalAudit.InsertDataExportRecordSource(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 60000, Database::"Detailed Cust. Ledg. Entry", 2, Database::"Cust. Ledger Entry", 50000, 4, DetailedCustLedgEntryFileNameLbl);
        ContosoDEDigitalAudit.InsertDataExportRecordSource(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 70000, Database::"Vendor", 0, 0, 0, 0, VendorFileNameLbl);
        ContosoDEDigitalAudit.InsertDataExportRecordSource(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 80000, Database::"Vendor Ledger Entry", 1, Database::"Vendor", 70000, 4, VendorLedgerEntryFileNameLbl);
        ContosoDEDigitalAudit.InsertDataExportRecordSource(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 90000, Database::"Detailed Vendor Ledg. Entry", 2, Database::"Vendor Ledger Entry", 80000, 4, DetailedVendorLedgEntryFileNameLbl);
        ContosoDEDigitalAudit.InsertDataExportRecordSource(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 100000, Database::"G/L Register", 0, 0, 0, 0, GLRegisterFileNameLbl);
        ContosoDEDigitalAudit.InsertDataExportRecordSource(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 110000, Database::"General Ledger Setup", 0, 0, 0, 0, GeneralLedgerSetupFileNameLbl);
        ContosoDEDigitalAudit.InsertDataExportRecordSource(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 120000, Database::"VAT Entry", 0, 0, 0, 4, VATEntryFileNameLbl);
        ContosoDEDigitalAudit.InsertDataExportRecordSource(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 130000, Database::"VAT Posting Setup", 0, 0, 0, 0, VATPostingSetupFileNameLbl);
        ContosoDEDigitalAudit.InsertDataExportRecordSource(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 140000, Database::"Dimension Value", 0, 0, 0, 0, DimensionValueFileNameLbl);
        ContosoDEDigitalAudit.InsertDataExportRecordSource(CreateDEDataExport.ItemData(), CreateDEDataExpRecType.ItemData(), 10000, Database::"Item", 0, 0, 0, 0, ItemFileNameLbl);
        ContosoDEDigitalAudit.InsertDataExportRecordSource(CreateDEDataExport.ItemData(), CreateDEDataExpRecType.ItemData(), 20000, Database::"Item Ledger Entry", 1, Database::"Item", 10000, 3, ItemLedgerEntryFileNameLbl);
        ContosoDEDigitalAudit.InsertDataExportRecordSource(CreateDEDataExport.ItemData(), CreateDEDataExpRecType.ItemData(), 30000, Database::"Sales Invoice Header", 0, 0, 0, 20, SalesInvoiceHeaderFileNameLbl);
        ContosoDEDigitalAudit.InsertDataExportRecordSource(CreateDEDataExport.ItemData(), CreateDEDataExpRecType.ItemData(), 40000, Database::"Sales Cr.Memo Header", 0, 0, 0, 20, SalesCrMemoHeaderFileNameLbl);
    end;

    local procedure CreateDataExportTableRelation()
    var
        CreateDEDataExport: Codeunit "Create DE Data Export";
        CreateDEDataExpRecType: Codeunit "Create DE Data Exp. Rec. Type";
        ContosoDEDigitalAudit: Codeunit "Contoso DE Digital Audit";
    begin
        ContosoDEDigitalAudit.InsertDataExportTableRelation(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), Database::"G/L Account", 1, Database::"G/L Entry", 3);
        ContosoDEDigitalAudit.InsertDataExportTableRelation(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), Database::"Customer", 1, Database::"Cust. Ledger Entry", 3);
        ContosoDEDigitalAudit.InsertDataExportTableRelation(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), Database::"Vendor", 1, Database::"Vendor Ledger Entry", 3);
        ContosoDEDigitalAudit.InsertDataExportTableRelation(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), Database::"Fixed Asset", 1, Database::"FA Ledger Entry", 3);
        ContosoDEDigitalAudit.InsertDataExportTableRelation(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), Database::"Fixed Asset", 1, Database::"FA Depreciation Book", 1);
        ContosoDEDigitalAudit.InsertDataExportTableRelation(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), Database::"G/L Account", 1, Database::"G/L Entry", 3);
        ContosoDEDigitalAudit.InsertDataExportTableRelation(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), Database::"Customer", 1, Database::"Cust. Ledger Entry", 3);
        ContosoDEDigitalAudit.InsertDataExportTableRelation(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), Database::"Cust. Ledger Entry", 1, Database::"Detailed Cust. Ledg. Entry", 2);
        ContosoDEDigitalAudit.InsertDataExportTableRelation(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), Database::"Vendor", 1, Database::"Vendor Ledger Entry", 3);
        ContosoDEDigitalAudit.InsertDataExportTableRelation(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), Database::"Vendor Ledger Entry", 1, Database::"Detailed Vendor Ledg. Entry", 2);
        ContosoDEDigitalAudit.InsertDataExportTableRelation(CreateDEDataExport.ItemData(), CreateDEDataExpRecType.ItemData(), Database::"Item", 1, Database::"Item Ledger Entry", 2);
    end;

    local procedure CreateDataExportRecordField()
    var
        CreateDEDataExport: Codeunit "Create DE Data Export";
        CreateDEDataExpRecType: Codeunit "Create DE Data Exp. Rec. Type";
        ContosoDEDigitalAudit: Codeunit "Contoso DE Digital Audit";
    begin
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 10000, Database::"G/L Account", 1, 10000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 10000, Database::"G/L Account", 2, 20000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 10000, Database::"G/L Account", 4, 30000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 10000, Database::"G/L Account", 10, 40000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 10000, Database::"G/L Account", 31, 50000, 2);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 10000, Database::"G/L Account", 32, 60000, 1);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 20000, Database::"G/L Entry", 1, 10000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 20000, Database::"G/L Entry", 3, 20000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 20000, Database::"G/L Entry", 4, 30000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 20000, Database::"G/L Entry", 5, 40000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 20000, Database::"G/L Entry", 6, 50000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 20000, Database::"G/L Entry", 7, 60000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 20000, Database::"G/L Entry", 17, 70000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 20000, Database::"G/L Entry", 52, 80000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 20000, Database::"G/L Entry", 53, 90000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 20000, Database::"G/L Entry", 54, 100000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 20000, Database::"G/L Entry", 56, 110000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 30000, Database::"Customer", 1, 10000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 30000, Database::"Customer", 2, 20000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 30000, Database::"Customer", 21, 30000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 30000, Database::"Customer", 59, 40000, 2);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 30000, Database::"Customer", 61, 50000, 1);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 40000, Database::"Cust. Ledger Entry", 1, 10000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 40000, Database::"Cust. Ledger Entry", 3, 20000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 40000, Database::"Cust. Ledger Entry", 4, 30000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 40000, Database::"Cust. Ledger Entry", 5, 40000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 40000, Database::"Cust. Ledger Entry", 6, 50000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 40000, Database::"Cust. Ledger Entry", 7, 60000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 40000, Database::"Cust. Ledger Entry", 11, 70000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 40000, Database::"Cust. Ledger Entry", 13, 80000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 40000, Database::"Cust. Ledger Entry", 14, 90000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 40000, Database::"Cust. Ledger Entry", 15, 100000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 40000, Database::"Cust. Ledger Entry", 16, 110000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 50000, Database::"Vendor", 1, 10000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 50000, Database::"Vendor", 2, 20000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 50000, Database::"Vendor", 21, 30000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 50000, Database::"Vendor", 59, 40000, 2);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 50000, Database::"Vendor", 61, 50000, 1);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 60000, Database::"Vendor Ledger Entry", 1, 10000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 60000, Database::"Vendor Ledger Entry", 3, 20000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 60000, Database::"Vendor Ledger Entry", 4, 30000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 60000, Database::"Vendor Ledger Entry", 5, 40000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 60000, Database::"Vendor Ledger Entry", 6, 50000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 60000, Database::"Vendor Ledger Entry", 7, 60000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 60000, Database::"Vendor Ledger Entry", 11, 70000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 60000, Database::"Vendor Ledger Entry", 13, 80000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 60000, Database::"Vendor Ledger Entry", 14, 90000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 60000, Database::"Vendor Ledger Entry", 15, 100000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 60000, Database::"Vendor Ledger Entry", 16, 110000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 70000, Database::"VAT Entry", 1, 10000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 70000, Database::"VAT Entry", 4, 20000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 70000, Database::"VAT Entry", 5, 30000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 70000, Database::"VAT Entry", 6, 40000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 70000, Database::"VAT Entry", 7, 50000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 70000, Database::"VAT Entry", 8, 60000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 70000, Database::"VAT Entry", 9, 70000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 70000, Database::"VAT Entry", 10, 80000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 70000, Database::"VAT Entry", 2, 90000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 70000, Database::"VAT Entry", 3, 100000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 70000, Database::"VAT Entry", 39, 110000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ExportData(), CreateDEDataExpRecType.RecordCode(), 70000, Database::"VAT Entry", 40, 120000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 10000, Database::"Fixed Asset", 1, 10000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 10000, Database::"Fixed Asset", 2, 20000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 10000, Database::"Fixed Asset", 4, 30000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 10000, Database::"Fixed Asset", 5, 40000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 10000, Database::"Fixed Asset", 11, 50000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 10000, Database::"Fixed Asset", 26, 60000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 20000, Database::"FA Ledger Entry", 3, 10000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 20000, Database::"FA Ledger Entry", 4, 20000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 20000, Database::"FA Ledger Entry", 5, 30000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 20000, Database::"FA Ledger Entry", 6, 40000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 20000, Database::"FA Ledger Entry", 7, 50000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 20000, Database::"FA Ledger Entry", 8, 60000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 20000, Database::"FA Ledger Entry", 9, 70000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 20000, Database::"FA Ledger Entry", 10, 80000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 20000, Database::"FA Ledger Entry", 11, 90000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 20000, Database::"FA Ledger Entry", 13, 100000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 20000, Database::"FA Ledger Entry", 14, 110000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 20000, Database::"FA Ledger Entry", 15, 120000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 20000, Database::"FA Ledger Entry", 16, 130000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 20000, Database::"FA Ledger Entry", 17, 140000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 20000, Database::"FA Ledger Entry", 18, 150000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 20000, Database::"FA Ledger Entry", 19, 160000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 20000, Database::"FA Ledger Entry", 20, 170000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 20000, Database::"FA Ledger Entry", 27, 180000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 20000, Database::"FA Ledger Entry", 33, 190000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 20000, Database::"FA Ledger Entry", 34, 200000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 20000, Database::"FA Ledger Entry", 35, 210000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 20000, Database::"FA Ledger Entry", 36, 220000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 20000, Database::"FA Ledger Entry", 37, 230000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 20000, Database::"FA Ledger Entry", 38, 240000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 20000, Database::"FA Ledger Entry", 53, 250000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 30000, Database::"FA Depreciation Book", 1, 10000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 30000, Database::"FA Depreciation Book", 2, 20000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 30000, Database::"FA Depreciation Book", 3, 30000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 30000, Database::"FA Depreciation Book", 4, 40000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 30000, Database::"FA Depreciation Book", 5, 50000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 30000, Database::"FA Depreciation Book", 6, 60000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 30000, Database::"FA Depreciation Book", 7, 70000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 30000, Database::"FA Depreciation Book", 8, 80000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 30000, Database::"FA Depreciation Book", 9, 90000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 30000, Database::"FA Depreciation Book", 11, 100000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 30000, Database::"FA Depreciation Book", 12, 110000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 30000, Database::"FA Depreciation Book", 13, 120000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 30000, Database::"FA Depreciation Book", 15, 130000, 2);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 30000, Database::"FA Depreciation Book", 16, 140000, 2);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 30000, Database::"FA Depreciation Book", 17, 150000, 2);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 30000, Database::"FA Depreciation Book", 18, 160000, 2);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 30000, Database::"FA Depreciation Book", 19, 170000, 2);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 30000, Database::"FA Depreciation Book", 20, 180000, 2);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 30000, Database::"FA Depreciation Book", 21, 190000, 2);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 30000, Database::"FA Depreciation Book", 22, 200000, 2);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 30000, Database::"FA Depreciation Book", 23, 210000, 2);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 30000, Database::"FA Depreciation Book", 24, 220000, 3);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 30000, Database::"FA Depreciation Book", 25, 230000, 2);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 30000, Database::"FA Depreciation Book", 26, 240000, 2);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 30000, Database::"FA Depreciation Book", 30, 250000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 30000, Database::"FA Depreciation Book", 31, 260000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 30000, Database::"FA Depreciation Book", 32, 270000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 30000, Database::"FA Depreciation Book", 55, 280000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 30000, Database::"FA Depreciation Book", 56, 290000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 30000, Database::"FA Depreciation Book", 57, 300000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 40000, Database::"FA Posting Group", 1, 10000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 40000, Database::"FA Posting Group", 2, 20000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 40000, Database::"FA Posting Group", 3, 30000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 40000, Database::"FA Posting Group", 4, 40000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 40000, Database::"FA Posting Group", 5, 50000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 40000, Database::"FA Posting Group", 6, 60000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 40000, Database::"FA Posting Group", 7, 70000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.FixedAssetData(), CreateDEDataExpRecType.FixedAssetData(), 40000, Database::"FA Posting Group", 9, 80000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 10000, Database::"Country/Region", 1, 10000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 10000, Database::"Country/Region", 2, 20000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 10000, Database::"Country/Region", 6, 30000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 20000, Database::"G/L Account", 1, 10000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 20000, Database::"G/L Account", 2, 20000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 20000, Database::"G/L Account", 4, 30000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 20000, Database::"G/L Account", 9, 40000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 20000, Database::"G/L Account", 14, 50000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 20000, Database::"G/L Account", 31, 60000, 2);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 20000, Database::"G/L Account", 32, 70000, 1);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 30000, Database::"G/L Entry", 1, 10000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 30000, Database::"G/L Entry", 3, 20000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 30000, Database::"G/L Entry", 4, 30000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 30000, Database::"G/L Entry", 5, 40000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 30000, Database::"G/L Entry", 6, 50000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 30000, Database::"G/L Entry", 7, 60000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 30000, Database::"G/L Entry", 10, 70000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 30000, Database::"G/L Entry", 17, 80000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 30000, Database::"G/L Entry", 23, 90000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 30000, Database::"G/L Entry", 24, 100000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 30000, Database::"G/L Entry", 27, 110000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 30000, Database::"G/L Entry", 29, 120000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 30000, Database::"G/L Entry", 43, 130000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 30000, Database::"G/L Entry", 48, 140000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 30000, Database::"G/L Entry", 51, 150000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 30000, Database::"G/L Entry", 52, 160000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 30000, Database::"G/L Entry", 53, 170000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 30000, Database::"G/L Entry", 54, 180000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 30000, Database::"G/L Entry", 55, 190000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 30000, Database::"G/L Entry", 56, 200000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 30000, Database::"G/L Entry", 57, 210000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 30000, Database::"G/L Entry", 58, 220000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 30000, Database::"G/L Entry", 64, 230000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 30000, Database::"G/L Entry", 65, 240000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 40000, Database::"Customer", 1, 10000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 40000, Database::"Customer", 2, 20000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 40000, Database::"Customer", 4, 30000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 40000, Database::"Customer", 5, 40000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 40000, Database::"Customer", 6, 50000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 40000, Database::"Customer", 7, 60000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 40000, Database::"Customer", 8, 70000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 40000, Database::"Customer", 9, 80000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 40000, Database::"Customer", 20, 90000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 40000, Database::"Customer", 21, 100000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 40000, Database::"Customer", 35, 110000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 40000, Database::"Customer", 45, 120000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 40000, Database::"Customer", 54, 130000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 40000, Database::"Customer", 61, 140000, 1);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 40000, Database::"Customer", 86, 150000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 40000, Database::"Customer", 91, 160000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 40000, Database::"Customer", 92, 170000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 40000, Database::"Customer", 99, 180000, 2);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 40000, Database::"Customer", 100, 190000, 2);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 40000, Database::"Customer", 102, 200000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 40000, Database::"Customer", 108, 210000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 50000, Database::"Cust. Ledger Entry", 1, 10000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 50000, Database::"Cust. Ledger Entry", 3, 20000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 50000, Database::"Cust. Ledger Entry", 4, 30000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 50000, Database::"Cust. Ledger Entry", 5, 40000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 50000, Database::"Cust. Ledger Entry", 6, 50000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 50000, Database::"Cust. Ledger Entry", 7, 60000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 50000, Database::"Cust. Ledger Entry", 16, 70000, 2);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 50000, Database::"Cust. Ledger Entry", 17, 80000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 50000, Database::"Cust. Ledger Entry", 23, 90000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 50000, Database::"Cust. Ledger Entry", 24, 100000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 50000, Database::"Cust. Ledger Entry", 27, 110000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 50000, Database::"Cust. Ledger Entry", 37, 120000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 50000, Database::"Cust. Ledger Entry", 45, 130000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 50000, Database::"Cust. Ledger Entry", 51, 140000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 50000, Database::"Cust. Ledger Entry", 52, 150000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 50000, Database::"Cust. Ledger Entry", 53, 160000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 50000, Database::"Cust. Ledger Entry", 60, 170000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 50000, Database::"Cust. Ledger Entry", 61, 180000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 50000, Database::"Cust. Ledger Entry", 62, 190000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 60000, Database::"Detailed Cust. Ledg. Entry", 1, 10000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 60000, Database::"Detailed Cust. Ledg. Entry", 2, 20000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 60000, Database::"Detailed Cust. Ledg. Entry", 3, 30000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 60000, Database::"Detailed Cust. Ledg. Entry", 4, 40000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 60000, Database::"Detailed Cust. Ledg. Entry", 5, 50000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 60000, Database::"Detailed Cust. Ledg. Entry", 7, 60000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 60000, Database::"Detailed Cust. Ledg. Entry", 8, 70000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 60000, Database::"Detailed Cust. Ledg. Entry", 9, 80000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 60000, Database::"Detailed Cust. Ledg. Entry", 35, 90000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 60000, Database::"Detailed Cust. Ledg. Entry", 36, 100000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 70000, Database::"Vendor", 1, 10000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 70000, Database::"Vendor", 2, 20000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 70000, Database::"Vendor", 4, 30000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 70000, Database::"Vendor", 5, 40000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 70000, Database::"Vendor", 6, 50000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 70000, Database::"Vendor", 7, 60000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 70000, Database::"Vendor", 8, 70000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 70000, Database::"Vendor", 9, 80000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 70000, Database::"Vendor", 21, 90000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 70000, Database::"Vendor", 35, 100000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 70000, Database::"Vendor", 45, 110000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 70000, Database::"Vendor", 54, 120000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 70000, Database::"Vendor", 61, 130000, 1);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 70000, Database::"Vendor", 86, 140000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 70000, Database::"Vendor", 91, 150000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 70000, Database::"Vendor", 92, 160000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 70000, Database::"Vendor", 99, 170000, 2);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 70000, Database::"Vendor", 100, 180000, 2);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 70000, Database::"Vendor", 102, 190000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 70000, Database::"Vendor", 108, 200000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 80000, Database::"Vendor Ledger Entry", 1, 10000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 80000, Database::"Vendor Ledger Entry", 3, 20000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 80000, Database::"Vendor Ledger Entry", 4, 30000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 80000, Database::"Vendor Ledger Entry", 5, 40000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 80000, Database::"Vendor Ledger Entry", 6, 50000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 80000, Database::"Vendor Ledger Entry", 7, 60000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 80000, Database::"Vendor Ledger Entry", 16, 70000, 2);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 80000, Database::"Vendor Ledger Entry", 17, 80000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 80000, Database::"Vendor Ledger Entry", 23, 90000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 80000, Database::"Vendor Ledger Entry", 24, 100000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 80000, Database::"Vendor Ledger Entry", 27, 110000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 80000, Database::"Vendor Ledger Entry", 37, 120000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 80000, Database::"Vendor Ledger Entry", 45, 130000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 80000, Database::"Vendor Ledger Entry", 51, 140000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 80000, Database::"Vendor Ledger Entry", 52, 150000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 80000, Database::"Vendor Ledger Entry", 53, 160000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 80000, Database::"Vendor Ledger Entry", 60, 170000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 80000, Database::"Vendor Ledger Entry", 61, 180000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 80000, Database::"Vendor Ledger Entry", 62, 190000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 90000, Database::"Detailed Vendor Ledg. Entry", 1, 10000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 90000, Database::"Detailed Vendor Ledg. Entry", 2, 20000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 90000, Database::"Detailed Vendor Ledg. Entry", 3, 30000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 90000, Database::"Detailed Vendor Ledg. Entry", 4, 40000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 90000, Database::"Detailed Vendor Ledg. Entry", 5, 50000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 90000, Database::"Detailed Vendor Ledg. Entry", 7, 60000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 90000, Database::"Detailed Vendor Ledg. Entry", 8, 70000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 90000, Database::"Detailed Vendor Ledg. Entry", 9, 80000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 90000, Database::"Detailed Vendor Ledg. Entry", 35, 90000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 90000, Database::"Detailed Vendor Ledg. Entry", 36, 100000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 100000, Database::"G/L Register", 2, 10000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 100000, Database::"G/L Register", 3, 20000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 100000, Database::"G/L Register", 4, 30000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 100000, Database::"G/L Register", 6, 40000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 110000, Database::"General Ledger Setup", 71, 10000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 120000, Database::"VAT Entry", 1, 10000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 120000, Database::"VAT Entry", 2, 20000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 120000, Database::"VAT Entry", 3, 30000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 120000, Database::"VAT Entry", 4, 40000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 120000, Database::"VAT Entry", 5, 50000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 120000, Database::"VAT Entry", 6, 60000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 120000, Database::"VAT Entry", 7, 70000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 120000, Database::"VAT Entry", 8, 80000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 120000, Database::"VAT Entry", 9, 90000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 120000, Database::"VAT Entry", 10, 100000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 120000, Database::"VAT Entry", 12, 110000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 120000, Database::"VAT Entry", 13, 120000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 120000, Database::"VAT Entry", 15, 130000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 120000, Database::"VAT Entry", 17, 140000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 120000, Database::"VAT Entry", 19, 150000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 120000, Database::"VAT Entry", 21, 160000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 120000, Database::"VAT Entry", 35, 170000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 120000, Database::"VAT Entry", 39, 180000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 120000, Database::"VAT Entry", 40, 190000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 120000, Database::"VAT Entry", 55, 200000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 130000, Database::"VAT Posting Setup", 1, 10000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 130000, Database::"VAT Posting Setup", 2, 20000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 130000, Database::"VAT Posting Setup", 3, 30000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 130000, Database::"VAT Posting Setup", 4, 40000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 130000, Database::"VAT Posting Setup", 7, 50000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 130000, Database::"VAT Posting Setup", 9, 60000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 130000, Database::"VAT Posting Setup", 11, 70000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 140000, Database::"Dimension Value", 1, 10000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 140000, Database::"Dimension Value", 2, 20000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 140000, Database::"Dimension Value", 3, 30000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 140000, Database::"Dimension Value", 4, 40000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 140000, Database::"Dimension Value", 5, 50000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 140000, Database::"Dimension Value", 7, 60000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 140000, Database::"Dimension Value", 8, 70000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.GLAccountData(), CreateDEDataExpRecType.GLAccountData(), 140000, Database::"Dimension Value", 9, 80000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ItemData(), CreateDEDataExpRecType.ItemData(), 10000, Database::"Item", 1, 10000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ItemData(), CreateDEDataExpRecType.ItemData(), 10000, Database::"Item", 3, 20000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ItemData(), CreateDEDataExpRecType.ItemData(), 10000, Database::"Item", 70, 30000, 2);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ItemData(), CreateDEDataExpRecType.ItemData(), 10000, Database::"Item", 90, 40000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ItemData(), CreateDEDataExpRecType.ItemData(), 10000, Database::"Item", 99, 50000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ItemData(), CreateDEDataExpRecType.ItemData(), 20000, Database::"Item Ledger Entry", 2, 10000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ItemData(), CreateDEDataExpRecType.ItemData(), 20000, Database::"Item Ledger Entry", 3, 20000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ItemData(), CreateDEDataExpRecType.ItemData(), 20000, Database::"Item Ledger Entry", 4, 30000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ItemData(), CreateDEDataExpRecType.ItemData(), 20000, Database::"Item Ledger Entry", 5, 40000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ItemData(), CreateDEDataExpRecType.ItemData(), 20000, Database::"Item Ledger Entry", 6, 50000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ItemData(), CreateDEDataExpRecType.ItemData(), 20000, Database::"Item Ledger Entry", 12, 60000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ItemData(), CreateDEDataExpRecType.ItemData(), 20000, Database::"Item Ledger Entry", 41, 70000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ItemData(), CreateDEDataExpRecType.ItemData(), 20000, Database::"Item Ledger Entry", 52, 80000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ItemData(), CreateDEDataExpRecType.ItemData(), 20000, Database::"Item Ledger Entry", 60, 90000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ItemData(), CreateDEDataExpRecType.ItemData(), 20000, Database::"Item Ledger Entry", 5816, 100000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ItemData(), CreateDEDataExpRecType.ItemData(), 30000, Database::"Sales Invoice Header", 3, 10000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ItemData(), CreateDEDataExpRecType.ItemData(), 30000, Database::"Sales Invoice Header", 2, 20000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ItemData(), CreateDEDataExpRecType.ItemData(), 30000, Database::"Sales Invoice Header", 4, 30000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ItemData(), CreateDEDataExpRecType.ItemData(), 30000, Database::"Sales Invoice Header", 5, 40000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ItemData(), CreateDEDataExpRecType.ItemData(), 30000, Database::"Sales Invoice Header", 20, 50000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ItemData(), CreateDEDataExpRecType.ItemData(), 30000, Database::"Sales Invoice Header", 27, 60000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ItemData(), CreateDEDataExpRecType.ItemData(), 30000, Database::"Sales Invoice Header", 60, 70000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ItemData(), CreateDEDataExpRecType.ItemData(), 30000, Database::"Sales Invoice Header", 61, 80000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ItemData(), CreateDEDataExpRecType.ItemData(), 30000, Database::"Sales Invoice Header", 70, 90000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ItemData(), CreateDEDataExpRecType.ItemData(), 30000, Database::"Sales Invoice Header", 78, 100000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ItemData(), CreateDEDataExpRecType.ItemData(), 30000, Database::"Sales Invoice Header", 87, 110000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ItemData(), CreateDEDataExpRecType.ItemData(), 30000, Database::"Sales Invoice Header", 93, 120000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ItemData(), CreateDEDataExpRecType.ItemData(), 40000, Database::"Sales Cr.Memo Header", 3, 10000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ItemData(), CreateDEDataExpRecType.ItemData(), 40000, Database::"Sales Cr.Memo Header", 2, 20000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ItemData(), CreateDEDataExpRecType.ItemData(), 40000, Database::"Sales Cr.Memo Header", 4, 30000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ItemData(), CreateDEDataExpRecType.ItemData(), 40000, Database::"Sales Cr.Memo Header", 5, 40000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ItemData(), CreateDEDataExpRecType.ItemData(), 40000, Database::"Sales Cr.Memo Header", 20, 50000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ItemData(), CreateDEDataExpRecType.ItemData(), 40000, Database::"Sales Cr.Memo Header", 27, 60000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ItemData(), CreateDEDataExpRecType.ItemData(), 40000, Database::"Sales Cr.Memo Header", 60, 70000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ItemData(), CreateDEDataExpRecType.ItemData(), 40000, Database::"Sales Cr.Memo Header", 61, 80000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ItemData(), CreateDEDataExpRecType.ItemData(), 40000, Database::"Sales Cr.Memo Header", 70, 90000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ItemData(), CreateDEDataExpRecType.ItemData(), 40000, Database::"Sales Cr.Memo Header", 78, 100000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ItemData(), CreateDEDataExpRecType.ItemData(), 40000, Database::"Sales Cr.Memo Header", 87, 110000, 0);
        ContosoDEDigitalAudit.InsertDataExportRecordField(CreateDEDataExport.ItemData(), CreateDEDataExpRecType.ItemData(), 40000, Database::"Sales Cr.Memo Header", 93, 120000, 0);
    end;


    var
        GL_AccountFileNameLbl: Label 'GL_Account.txt', MaxLength = 250;
        GL_EntryFileNameLbl: Label 'GL_Entry.txt', MaxLength = 250;
        CustomerFileNameLbl: Label 'Customer.txt', MaxLength = 250;
        Cust_LedgerFileNameLbl: Label 'Cust_Ledger.txt', MaxLength = 250;
        VendorFileNameLbl: Label 'Vendor.txt', MaxLength = 250;
        Vend_LedgerFileNameLbl: Label 'Vend_Ledger.txt', MaxLength = 250;
        VAT_EntryFileNameLbl: Label 'VAT_Entry.txt', MaxLength = 250;
        FixedAssetFileNameLbl: Label 'FixedAsset.txt', MaxLength = 250;
        FALedgerEntryFileNameLbl: Label 'FALedgerEntry.txt', MaxLength = 250;
        FADepreciationBookFileNameLbl: Label 'FADepreciationBook.txt', MaxLength = 250;
        FAPostingGroupFileNameLbl: Label 'FAPostingGroup.txt', MaxLength = 250;
        CountryRegionFileNameLbl: Label 'CountryRegion.txt', MaxLength = 250;
        GLAccountFileNameLbl: Label 'GLAccount.txt', MaxLength = 250;
        GLEntryFileNameLbl: Label 'GLEntry.txt', MaxLength = 250;
        CustLedgerEntryFileNameLbl: Label 'CustLedgerEntry.txt', MaxLength = 250;
        DetailedCustLedgEntryFileNameLbl: Label 'DetailedCustLedgEntry.txt', MaxLength = 250;
        VendorLedgerEntryFileNameLbl: Label 'VendorLedgerEntry.txt', MaxLength = 250;
        DetailedVendorLedgEntryFileNameLbl: Label 'DetailedVendorLedgEntry.txt', MaxLength = 250;
        GLRegisterFileNameLbl: Label 'GLRegister.txt', MaxLength = 250;
        GeneralLedgerSetupFileNameLbl: Label 'GeneralLedgerSetup.txt', MaxLength = 250;
        VATEntryFileNameLbl: Label 'VATEntry.txt', MaxLength = 250;
        VATPostingSetupFileNameLbl: Label 'VATPostingSetup.txt', MaxLength = 250;
        DimensionValueFileNameLbl: Label 'DimensionValue.txt', MaxLength = 250;
        ItemFileNameLbl: Label 'Item.txt', MaxLength = 250;
        ItemLedgerEntryFileNameLbl: Label 'ItemLedgerEntry.txt', MaxLength = 250;
        SalesInvoiceHeaderFileNameLbl: Label 'SalesInvoiceHeader.txt', MaxLength = 250;
        SalesCrMemoHeaderFileNameLbl: Label 'SalesCrMemoHeader.txt', MaxLength = 250;
}