codeunit 11145 "Create Post Code AT"
{
    InherentEntitlements = X;
    InherentPermissions = X;

    // TODO: MS
    // Discuss it
    // Maybe a service provide a better list of post codes?
    // This can be the same for now, then we convert to a list later.

    // Keep as it is for now
    // Wael

    trigger OnRun()
    var
        ContosoPostCodeDK: Codeunit "Contoso Post Code AT";
        CreateCountryRegion: Codeunit "Create Country/Region";
    begin
        ContosoPostCodeDK.InsertPostCode('0 0100', NairobiLbl, CreateCountryRegion.KE());
        ContosoPostCodeDK.InsertPostCode('0 1007', KairiLbl, CreateCountryRegion.KE());
        ContosoPostCodeDK.InsertPostCode('0001', PretoriaLbl, CreateCountryRegion.ZA());
        ContosoPostCodeDK.InsertPostCode('00100', HelsinkiLbl, CreateCountryRegion.FI());
        ContosoPostCodeDK.InsertPostCode('00100', ROMARMLbl, CreateCountryRegion.IT());
        ContosoPostCodeDK.InsertPostCode('00101', HelsinkiLbl, CreateCountryRegion.FI());
        ContosoPostCodeDK.InsertPostCode('00260', HelsinkiLbl, CreateCountryRegion.FI());
        ContosoPostCodeDK.InsertPostCode('00300', MaputoLbl, CreateCountryRegion.MZ());
        ContosoPostCodeDK.InsertPostCode('01030', MexicoCityDFLbl, CreateCountryRegion.MX());
        ContosoPostCodeDK.InsertPostCode('01800', KlaukkalaLbl, CreateCountryRegion.FI());
        ContosoPostCodeDK.InsertPostCode('02-515', WarszawaLbl, CreateCountryRegion.PL());
        ContosoPostCodeDK.InsertPostCode('026 01', DolnyKubinLbl, CreateCountryRegion.SK());
        ContosoPostCodeDK.InsertPostCode('03003', AlicanteLbl, CreateCountryRegion.ES());
        ContosoPostCodeDK.InsertPostCode('038988', SingaporeLbl, CreateCountryRegion.SG());
        ContosoPostCodeDK.InsertPostCode('049 21', BetliarLbl, CreateCountryRegion.SK());
        ContosoPostCodeDK.InsertPostCode('050724', BucurestiLbl, CreateCountryRegion.RO());
        ContosoPostCodeDK.InsertPostCode('050729', BucurestiLbl, CreateCountryRegion.RO());
        ContosoPostCodeDK.InsertPostCode('051511', BucurestiLbl, CreateCountryRegion.RO());
        ContosoPostCodeDK.InsertPostCode('05400', BARIKALbl, CreateCountryRegion.DZ());
        ContosoPostCodeDK.InsertPostCode('05400', JokelaLbl, CreateCountryRegion.FI());
        ContosoPostCodeDK.InsertPostCode('05428-002', SaoPauloSPLbl, CreateCountryRegion.BR());
        ContosoPostCodeDK.InsertPostCode('0552', OsloLbl, CreateCountryRegion.NO());
        ContosoPostCodeDK.InsertPostCode('06000', MexicoCityDFLbl, CreateCountryRegion.MX());
        ContosoPostCodeDK.InsertPostCode('06531', AnkaraLbl, CreateCountryRegion.TR());
        ContosoPostCodeDK.InsertPostCode('0661', OsloLbl, CreateCountryRegion.NO());
        ContosoPostCodeDK.InsertPostCode('0700', PietersburgLbl, CreateCountryRegion.ZA());
        ContosoPostCodeDK.InsertPostCode('07001', PalmaMallorcaLbl, CreateCountryRegion.ES());
        ContosoPostCodeDK.InsertPostCode('08010', BarcelonaLbl, CreateCountryRegion.ES());
        ContosoPostCodeDK.InsertPostCode('1000', LjubljanaLbl, CreateCountryRegion.SI());
        ContosoPostCodeDK.InsertPostCode('1000', ManilaLbl, CreateCountryRegion.PH());
        ContosoPostCodeDK.InsertPostCode('1000', SofiaLbl, CreateCountryRegion.BG());
        ContosoPostCodeDK.InsertPostCode('10000', ZagrebLbl, CreateCountryRegion.HR());
        ContosoPostCodeDK.InsertPostCode('10003', CaceresLbl, CreateCountryRegion.ES());
        ContosoPostCodeDK.InsertPostCode('1001', AucklandLbl, CreateCountryRegion.NZ());
        ContosoPostCodeDK.InsertPostCode('1002', TunisBelvedereLbl, CreateCountryRegion.TN());
        ContosoPostCodeDK.InsertPostCode('1003', SantaCruzManilaLbl, CreateCountryRegion.PH());
        ContosoPostCodeDK.InsertPostCode('1009 AG', AmsterdamLbl, CreateCountryRegion.NL());
        ContosoPostCodeDK.InsertPostCode('101', ReykjavikLbl, CreateCountryRegion.IS());
        ContosoPostCodeDK.InsertPostCode('1010', WienLbl, CreateCountryRegion.AT());
        ContosoPostCodeDK.InsertPostCode('10100', AGDALRABATLbl, CreateCountryRegion.MA());
        ContosoPostCodeDK.InsertPostCode('10100', TORINOTOLbl, CreateCountryRegion.IT());
        ContosoPostCodeDK.InsertPostCode('10101', RIADRABATLbl, CreateCountryRegion.MA());
        ContosoPostCodeDK.InsertPostCode('1011', RigaLbl, CreateCountryRegion.LV());
        ContosoPostCodeDK.InsertPostCode('1012', TondoManilaLbl, CreateCountryRegion.PH());
        ContosoPostCodeDK.InsertPostCode('10127', TallinnLbl, CreateCountryRegion.EE());
        ContosoPostCodeDK.InsertPostCode('10260', BangNaBangkokLbl, CreateCountryRegion.TH());
        ContosoPostCodeDK.InsertPostCode('1030', TunisLbl, CreateCountryRegion.TN());
        ContosoPostCodeDK.InsertPostCode('103054', MoskvaLbl, CreateCountryRegion.RU());
        ContosoPostCodeDK.InsertPostCode('10310', JakartaLbl, CreateCountryRegion.ID());
        ContosoPostCodeDK.InsertPostCode('1039', RigaLbl, CreateCountryRegion.LV());
        ContosoPostCodeDK.InsertPostCode('10440', JakartaLbl, CreateCountryRegion.ID());
        ContosoPostCodeDK.InsertPostCode('10500', BangRakBangkokLbl, CreateCountryRegion.TH());
        ContosoPostCodeDK.InsertPostCode('1050-042', LISBOALbl, CreateCountryRegion.PT());
        ContosoPostCodeDK.InsertPostCode('10510', KhlongSamwaBangkokLbl, CreateCountryRegion.TH());
        ContosoPostCodeDK.InsertPostCode('106 75', AthensLbl, CreateCountryRegion.EL());
        ContosoPostCodeDK.InsertPostCode('106 82', AthensLbl, CreateCountryRegion.EL());
        ContosoPostCodeDK.InsertPostCode('108', ReykjavikLbl, CreateCountryRegion.IS());
        ContosoPostCodeDK.InsertPostCode('109456', MoskvaLbl, CreateCountryRegion.RU());
        ContosoPostCodeDK.InsertPostCode('1100', WienLbl, CreateCountryRegion.AT());
        ContosoPostCodeDK.InsertPostCode('11000', BeogradLbl, CreateCountryRegion.RS());
        ContosoPostCodeDK.InsertPostCode('110002', DelhiLbl, CreateCountryRegion.IND());
        ContosoPostCodeDK.InsertPostCode('11001', BeogradLbl, CreateCountryRegion.RS());
        ContosoPostCodeDK.InsertPostCode('1100-150', LISBOALbl, CreateCountryRegion.PT());
        ContosoPostCodeDK.InsertPostCode('1107', BudapestLbl, CreateCountryRegion.HU());
        ContosoPostCodeDK.InsertPostCode('1111', ZaghouanLbl, CreateCountryRegion.TN());
        ContosoPostCodeDK.InsertPostCode('1117', CapriQuezonCityLbl, CreateCountryRegion.PH());
        ContosoPostCodeDK.InsertPostCode('112', ReykjavikLbl, CreateCountryRegion.IS());
        ContosoPostCodeDK.InsertPostCode('114 32', StockholmLbl, CreateCountryRegion.SE());
        ContosoPostCodeDK.InsertPostCode('11-430', KorszeLbl, CreateCountryRegion.PL());
        ContosoPostCodeDK.InsertPostCode('11470', JakartaLbl, CreateCountryRegion.ID());
        ContosoPostCodeDK.InsertPostCode('1161', BudapestLbl, CreateCountryRegion.HU());
        ContosoPostCodeDK.InsertPostCode('12000', TEMARALbl, CreateCountryRegion.MA());
        ContosoPostCodeDK.InsertPostCode('1204', BudapestLbl, CreateCountryRegion.HU());
        ContosoPostCodeDK.InsertPostCode('1230', WienLbl, CreateCountryRegion.AT());
        ContosoPostCodeDK.InsertPostCode('1300', SandvikaLbl, CreateCountryRegion.NO());
        ContosoPostCodeDK.InsertPostCode('1324', LysakerLbl, CreateCountryRegion.NO());
        ContosoPostCodeDK.InsertPostCode('1344', HaslumLbl, CreateCountryRegion.NO());
        ContosoPostCodeDK.InsertPostCode('1370', AskerLbl, CreateCountryRegion.NO());
        ContosoPostCodeDK.InsertPostCode('1400', SkiLbl, CreateCountryRegion.NO());
        ContosoPostCodeDK.InsertPostCode('1440', ValenzuelaLbl, CreateCountryRegion.PH());
        ContosoPostCodeDK.InsertPostCode('14-510', OrnetaLbl, CreateCountryRegion.PL());
        ContosoPostCodeDK.InsertPostCode('15156', TangerangLbl, CreateCountryRegion.ID());
        ContosoPostCodeDK.InsertPostCode('1530 JM', ZaandamLbl, CreateCountryRegion.NL());
        ContosoPostCodeDK.InsertPostCode('15-660', BialystokLbl, CreateCountryRegion.PL());
        ContosoPostCodeDK.InsertPostCode('16000', ALGIERSLbl, CreateCountryRegion.DZ());
        ContosoPostCodeDK.InsertPostCode('16012', ALGIERSLbl, CreateCountryRegion.DZ());
        ContosoPostCodeDK.InsertPostCode('16027', ALGIERSLbl, CreateCountryRegion.DZ());
        ContosoPostCodeDK.InsertPostCode('17120', WatSingChaiNatLbl, CreateCountryRegion.TH());
        ContosoPostCodeDK.InsertPostCode('185 40', PiraeusLbl, CreateCountryRegion.EL());
        ContosoPostCodeDK.InsertPostCode('1851', HumbeekLbl, CreateCountryRegion.BE());
        ContosoPostCodeDK.InsertPostCode('19210', BorLbl, CreateCountryRegion.RS());
        ContosoPostCodeDK.InsertPostCode('197342', SanktPetersburgLbl, CreateCountryRegion.RU());
        ContosoPostCodeDK.InsertPostCode('200', KopavogurLbl, CreateCountryRegion.IS());
        ContosoPostCodeDK.InsertPostCode('2000', JohannesburgLbl, CreateCountryRegion.ZA());
        ContosoPostCodeDK.InsertPostCode('2000', MariborLbl, CreateCountryRegion.SI());
        ContosoPostCodeDK.InsertPostCode('2000', SydneyNSWLbl, CreateCountryRegion.AU());
        ContosoPostCodeDK.InsertPostCode('20000', CASABLANCALbl, CreateCountryRegion.MA());
        ContosoPostCodeDK.InsertPostCode('20000', DubrovnikLbl, CreateCountryRegion.HR());
        ContosoPostCodeDK.InsertPostCode('200331', CraiovaLbl, CreateCountryRegion.RO());
        ContosoPostCodeDK.InsertPostCode('20097', HamburgLbl, CreateCountryRegion.DE());
        ContosoPostCodeDK.InsertPostCode('20100', MILANOMILbl, CreateCountryRegion.IT());
        ContosoPostCodeDK.InsertPostCode('20200', CASABLANCALbl, CreateCountryRegion.MA());
        ContosoPostCodeDK.InsertPostCode('2050', AntwerpenLbl, CreateCountryRegion.BE());
        ContosoPostCodeDK.InsertPostCode('20607', NarvaLbl, CreateCountryRegion.EE());
        ContosoPostCodeDK.InsertPostCode('20800', MOHAMMEDIALbl, CreateCountryRegion.MA());
        ContosoPostCodeDK.InsertPostCode('2100', CopenhagenLbl, CreateCountryRegion.DK());
        ContosoPostCodeDK.InsertPostCode('21000', MOSTAGANCULbl, CreateCountryRegion.DZ());
        ContosoPostCodeDK.InsertPostCode('21000', NoviSadLbl, CreateCountryRegion.RS());
        ContosoPostCodeDK.InsertPostCode('21000', SplitLbl, CreateCountryRegion.HR());
        ContosoPostCodeDK.InsertPostCode('220', HafnafjordurLbl, CreateCountryRegion.IS());
        ContosoPostCodeDK.InsertPostCode('2200', HerentalsLbl, CreateCountryRegion.BE());
        ContosoPostCodeDK.InsertPostCode('22000', SibenikLbl, CreateCountryRegion.HR());
        ContosoPostCodeDK.InsertPostCode('22291-040', RiodeJaneiroRJLbl, CreateCountryRegion.BR());
        ContosoPostCodeDK.InsertPostCode('22417', Hamburg36Lbl, CreateCountryRegion.DE());
        ContosoPostCodeDK.InsertPostCode('2355', WrNeudorfLbl, CreateCountryRegion.AT());
        ContosoPostCodeDK.InsertPostCode('24000', SuboticaLbl, CreateCountryRegion.RS());
        ContosoPostCodeDK.InsertPostCode('2405', HundsheimLbl, CreateCountryRegion.AT());
        ContosoPostCodeDK.InsertPostCode('2500', CarletonvilleLbl, CreateCountryRegion.ZA());
        ContosoPostCodeDK.InsertPostCode('2500', EsztergomLbl, CreateCountryRegion.HU());
        ContosoPostCodeDK.InsertPostCode('2500', KustendilLbl, CreateCountryRegion.BG());
        ContosoPostCodeDK.InsertPostCode('2500', WollongongNSWLbl, CreateCountryRegion.AU());
        ContosoPostCodeDK.InsertPostCode('2600', VilniusLbl, CreateCountryRegion.LT());
        ContosoPostCodeDK.InsertPostCode('2700', BlagoevgradLbl, CreateCountryRegion.BG());
        ContosoPostCodeDK.InsertPostCode('2700', VilniusLbl, CreateCountryRegion.LT());
        ContosoPostCodeDK.InsertPostCode('2800', MechelenLbl, CreateCountryRegion.BE());
        ContosoPostCodeDK.InsertPostCode('28003', MadridLbl, CreateCountryRegion.ES());
        ContosoPostCodeDK.InsertPostCode('2940', NewcastleLbl, CreateCountryRegion.ZA());
        ContosoPostCodeDK.InsertPostCode('2950', VedbaekLbl, CreateCountryRegion.DK());
        ContosoPostCodeDK.InsertPostCode('300', AkranesLbl, CreateCountryRegion.IS());
        ContosoPostCodeDK.InsertPostCode('3000', KaunasLbl, CreateCountryRegion.LT());
        ContosoPostCodeDK.InsertPostCode('3000', LeuvenLbl, CreateCountryRegion.BE());
        ContosoPostCodeDK.InsertPostCode('3000', MelbourneVICLbl, CreateCountryRegion.AU());
        ContosoPostCodeDK.InsertPostCode('300001', BENINEdostateLbl, CreateCountryRegion.NG());
        ContosoPostCodeDK.InsertPostCode('3000-337', COIMBRALbl, CreateCountryRegion.PT());
        ContosoPostCodeDK.InsertPostCode('302 50', HalmstadLbl, CreateCountryRegion.SE());
        ContosoPostCodeDK.InsertPostCode('3042', KaunasLbl, CreateCountryRegion.LT());
        ContosoPostCodeDK.InsertPostCode('3100', KairouanLbl, CreateCountryRegion.TN());
        ContosoPostCodeDK.InsertPostCode('3100', StPoltenLbl, CreateCountryRegion.AT());
        ContosoPostCodeDK.InsertPostCode('31260', NonDindaengBuriRamLbl, CreateCountryRegion.TH());
        ContosoPostCodeDK.InsertPostCode('3231', GrobelnoLbl, CreateCountryRegion.SI());
        ContosoPostCodeDK.InsertPostCode('3258', TarnaleleszLbl, CreateCountryRegion.HU());
        ContosoPostCodeDK.InsertPostCode('3270', DundagaLbl, CreateCountryRegion.LV());
        ContosoPostCodeDK.InsertPostCode('3325', NoszvajLbl, CreateCountryRegion.HU());
        ContosoPostCodeDK.InsertPostCode('34000', KragujevacLbl, CreateCountryRegion.RS());
        ContosoPostCodeDK.InsertPostCode('3600', DurbanLbl, CreateCountryRegion.ZA());
        ContosoPostCodeDK.InsertPostCode('36004', PontevedraLbl, CreateCountryRegion.ES());
        ContosoPostCodeDK.InsertPostCode('3601', DürnsteinLbl, CreateCountryRegion.AT());
        ContosoPostCodeDK.InsertPostCode('37001', SalamancaLbl, CreateCountryRegion.ES());
        ContosoPostCodeDK.InsertPostCode('37500', LeonGuanajuatoLbl, CreateCountryRegion.MX());
        ContosoPostCodeDK.InsertPostCode('3900', BauskaLbl, CreateCountryRegion.LV());
        ContosoPostCodeDK.InsertPostCode('3900', RichardsBayLbl, CreateCountryRegion.ZA());
        ContosoPostCodeDK.InsertPostCode('39100', BOLZANOBZLbl, CreateCountryRegion.IT());
        ContosoPostCodeDK.InsertPostCode('4000', BrisbaneQLDLbl, CreateCountryRegion.AU());
        ContosoPostCodeDK.InsertPostCode('4000', PlovdivLbl, CreateCountryRegion.BG());
        ContosoPostCodeDK.InsertPostCode('40000', KHENCHELbl, CreateCountryRegion.DZ());
        ContosoPostCodeDK.InsertPostCode('400001', MumbaiLbl, CreateCountryRegion.IND());
        ContosoPostCodeDK.InsertPostCode('4000-322', PORTOLbl, CreateCountryRegion.PT());
        ContosoPostCodeDK.InsertPostCode('40135', BandungLbl, CreateCountryRegion.ID());
        ContosoPostCodeDK.InsertPostCode('4040', LinzLbl, CreateCountryRegion.AT());
        ContosoPostCodeDK.InsertPostCode('40593', DusseldorfLbl, CreateCountryRegion.DE());
        ContosoPostCodeDK.InsertPostCode('41006', SevillaLbl, CreateCountryRegion.ES());
        ContosoPostCodeDK.InsertPostCode('4133', PrattelnLbl, CreateCountryRegion.CH());
        ContosoPostCodeDK.InsertPostCode('415 06', GoteborgLbl, CreateCountryRegion.SE());
        ContosoPostCodeDK.InsertPostCode('42000', PELABUHANKLANGSelangorLbl, CreateCountryRegion.MY());
        ContosoPostCodeDK.InsertPostCode('42020', KonyaLbl, CreateCountryRegion.TR());
        ContosoPostCodeDK.InsertPostCode('43000', BjelovarLbl, CreateCountryRegion.HR());
        ContosoPostCodeDK.InsertPostCode('440001', NagpurLbl, CreateCountryRegion.IND());
        ContosoPostCodeDK.InsertPostCode('443008', SamaraLbl, CreateCountryRegion.RU());
        ContosoPostCodeDK.InsertPostCode('44313', RakvereLbl, CreateCountryRegion.EE());
        ContosoPostCodeDK.InsertPostCode('44450', LACHAPELLEBASSEMERLbl, CreateCountryRegion.FR());
        ContosoPostCodeDK.InsertPostCode('4502', KranjLbl, CreateCountryRegion.SI());
        ContosoPostCodeDK.InsertPostCode('45030', ManisaLbl, CreateCountryRegion.TR());
        ContosoPostCodeDK.InsertPostCode('45109', TapaLbl, CreateCountryRegion.EE());
        ContosoPostCodeDK.InsertPostCode('45-418', OpoleLbl, CreateCountryRegion.PL());
        ContosoPostCodeDK.InsertPostCode('4600', KogeLbl, CreateCountryRegion.DK());
        ContosoPostCodeDK.InsertPostCode('4600', RudiskesLbl, CreateCountryRegion.LT());
        ContosoPostCodeDK.InsertPostCode('46007', ValenciaLbl, CreateCountryRegion.ES());
        ContosoPostCodeDK.InsertPostCode('47002', ValladolidLbl, CreateCountryRegion.ES());
        ContosoPostCodeDK.InsertPostCode('47400', PETALINGJAYASelangorLbl, CreateCountryRegion.MY());
        ContosoPostCodeDK.InsertPostCode('4810', GmundenLbl, CreateCountryRegion.AT());
        ContosoPostCodeDK.InsertPostCode('49603', MustveeLbl, CreateCountryRegion.EE());
        ContosoPostCodeDK.InsertPostCode('5 0413', AdungosiLbl, CreateCountryRegion.KE());
        ContosoPostCodeDK.InsertPostCode('5000', OdenseCLbl, CreateCountryRegion.DK());
        ContosoPostCodeDK.InsertPostCode('50001', ZaragozaLbl, CreateCountryRegion.ES());
        ContosoPostCodeDK.InsertPostCode('5002', OgreLbl, CreateCountryRegion.LV());
        ContosoPostCodeDK.InsertPostCode('500209', BrasovLbl, CreateCountryRegion.RO());
        ContosoPostCodeDK.InsertPostCode('50120', SanPaTongChiangMaiLbl, CreateCountryRegion.TH());
        ContosoPostCodeDK.InsertPostCode('5020', SalzburgLbl, CreateCountryRegion.AT());
        ContosoPostCodeDK.InsertPostCode('50450', AMPANGKualaLumpurLbl, CreateCountryRegion.MY());
        ContosoPostCodeDK.InsertPostCode('50670', CASSELLbl, CreateCountryRegion.FR());
        ContosoPostCodeDK.InsertPostCode('51021-040', RecifePELbl, CreateCountryRegion.BR());
        ContosoPostCodeDK.InsertPostCode('5113', KokneseLbl, CreateCountryRegion.LV());
        ContosoPostCodeDK.InsertPostCode('5132 EE', WaalwijkLbl, CreateCountryRegion.NL());
        ContosoPostCodeDK.InsertPostCode('521 03', KinnaredLbl, CreateCountryRegion.SE());
        ContosoPostCodeDK.InsertPostCode('52210', RovinjLbl, CreateCountryRegion.HR());
        ContosoPostCodeDK.InsertPostCode('546 35', ThessalonikiLbl, CreateCountryRegion.EL());
        ContosoPostCodeDK.InsertPostCode('5473', WoodvilleLbl, CreateCountryRegion.NZ());
        ContosoPostCodeDK.InsertPostCode('5491', DannevirkeLbl, CreateCountryRegion.NZ());
        ContosoPostCodeDK.InsertPostCode('550 05', JonkobingLbl, CreateCountryRegion.SE());
        ContosoPostCodeDK.InsertPostCode('550264', SibiuLbl, CreateCountryRegion.RO());
        ContosoPostCodeDK.InsertPostCode('560001', BengaluruLbl, CreateCountryRegion.IND());
        ContosoPostCodeDK.InsertPostCode('57000', KUALALUMPURLbl, CreateCountryRegion.MY());
        ContosoPostCodeDK.InsertPostCode('5730', MittersillLbl, CreateCountryRegion.AT());
        ContosoPostCodeDK.InsertPostCode('5800', KlaipedaLbl, CreateCountryRegion.LT());
        ContosoPostCodeDK.InsertPostCode('5800', NyborgLbl, CreateCountryRegion.DK());
        ContosoPostCodeDK.InsertPostCode('59-300', LubinLbl, CreateCountryRegion.PL());
        ContosoPostCodeDK.InsertPostCode('6 0500', MarsabitLbl, CreateCountryRegion.KE());
        ContosoPostCodeDK.InsertPostCode('600 03', NorrkobingLbl, CreateCountryRegion.SE());
        ContosoPostCodeDK.InsertPostCode('6000', KoperLbl, CreateCountryRegion.SI());
        ContosoPostCodeDK.InsertPostCode('6000', PortElizabethLbl, CreateCountryRegion.ZA());
        ContosoPostCodeDK.InsertPostCode('600001', ChennaiLbl, CreateCountryRegion.IND());
        ContosoPostCodeDK.InsertPostCode('6001', WellingtonLbl, CreateCountryRegion.NZ());
        ContosoPostCodeDK.InsertPostCode('6005', LuzernLbl, CreateCountryRegion.CH());
        ContosoPostCodeDK.InsertPostCode('60172', SurabayaLbl, CreateCountryRegion.ID());
        ContosoPostCodeDK.InsertPostCode('6020', InnsbruckLbl, CreateCountryRegion.AT());
        ContosoPostCodeDK.InsertPostCode('603061', NizhnyNovgorodLbl, CreateCountryRegion.RU());
        ContosoPostCodeDK.InsertPostCode('60320', FrankfurtMainLbl, CreateCountryRegion.DE());
        ContosoPostCodeDK.InsertPostCode('61100', SANTAVENERANDAPSLbl, CreateCountryRegion.IT());
        ContosoPostCodeDK.InsertPostCode('6343', RotkreuzLbl, CreateCountryRegion.CH());
        ContosoPostCodeDK.InsertPostCode('6405', ImmenseeLbl, CreateCountryRegion.CH());
        ContosoPostCodeDK.InsertPostCode('64640', MonterreyNuevoLeonLbl, CreateCountryRegion.MX());
        ContosoPostCodeDK.InsertPostCode('669 02', ZnojmoLbl, CreateCountryRegion.CZ());
        ContosoPostCodeDK.InsertPostCode('67067', PESCINAAQLbl, CreateCountryRegion.IT());
        ContosoPostCodeDK.InsertPostCode('678 01', BlanskoLbl, CreateCountryRegion.CZ());
        ContosoPostCodeDK.InsertPostCode('6800', PerthWALbl, CreateCountryRegion.AU());
        ContosoPostCodeDK.InsertPostCode('6827 BP', ArnhemLbl, CreateCountryRegion.NL());
        ContosoPostCodeDK.InsertPostCode('687 71', BojkoviceLbl, CreateCountryRegion.CZ());
        ContosoPostCodeDK.InsertPostCode('6900', BregenzLbl, CreateCountryRegion.AT());
        ContosoPostCodeDK.InsertPostCode('690001', VladivostokLbl, CreateCountryRegion.RU());
        ContosoPostCodeDK.InsertPostCode('696 42', VracovLbl, CreateCountryRegion.CZ());
        ContosoPostCodeDK.InsertPostCode('697 01', KyjovLbl, CreateCountryRegion.CZ());
        ContosoPostCodeDK.InsertPostCode('7000', EisenstadtLbl, CreateCountryRegion.AT());
        ContosoPostCodeDK.InsertPostCode('7000', ZamboangaCityLbl, CreateCountryRegion.PH());
        ContosoPostCodeDK.InsertPostCode('700001', KolkataLbl, CreateCountryRegion.IND());
        ContosoPostCodeDK.InsertPostCode('70710-926', BrasiliaDFLbl, CreateCountryRegion.BR());
        ContosoPostCodeDK.InsertPostCode('7178', MurdunnaTASLbl, CreateCountryRegion.AU());
        ContosoPostCodeDK.InsertPostCode('7202 BP', ZutphenLbl, CreateCountryRegion.NL());
        ContosoPostCodeDK.InsertPostCode('72800', EningenLbl, CreateCountryRegion.DE());
        ContosoPostCodeDK.InsertPostCode('731 33', ChaniaLbl, CreateCountryRegion.EL());
        ContosoPostCodeDK.InsertPostCode('7321 HE', ApeldoornLbl, CreateCountryRegion.NL());
        ContosoPostCodeDK.InsertPostCode('75000', PARISLbl, CreateCountryRegion.FR());
        ContosoPostCodeDK.InsertPostCode('76806', PaldiskiLbl, CreateCountryRegion.EE());
        ContosoPostCodeDK.InsertPostCode('77450', ESBLYLbl, CreateCountryRegion.FR());
        ContosoPostCodeDK.InsertPostCode('779 00', OlomouchLbl, CreateCountryRegion.CZ());
        ContosoPostCodeDK.InsertPostCode('78030', SanLuisPotosiSanLuisLbl, CreateCountryRegion.MX());
        ContosoPostCodeDK.InsertPostCode('78370', PLAISIRLbl, CreateCountryRegion.FR());
        ContosoPostCodeDK.InsertPostCode('7900', HokitikaLbl, CreateCountryRegion.NZ());
        ContosoPostCodeDK.InsertPostCode('8 0100', MombasaLbl, CreateCountryRegion.KE());
        ContosoPostCodeDK.InsertPostCode('8 0200', MalindiLbl, CreateCountryRegion.KE());
        ContosoPostCodeDK.InsertPostCode('8000', ArhusCLbl, CreateCountryRegion.DK());
        ContosoPostCodeDK.InsertPostCode('8000', CapeTownLbl, CreateCountryRegion.ZA());
        ContosoPostCodeDK.InsertPostCode('8001', ChristchurchLbl, CreateCountryRegion.NZ());
        ContosoPostCodeDK.InsertPostCode('80020-290', CuritibaPRLbl, CreateCountryRegion.BR());
        ContosoPostCodeDK.InsertPostCode('80080', IstanbulLbl, CreateCountryRegion.TR());
        ContosoPostCodeDK.InsertPostCode('8010', GrazLbl, CreateCountryRegion.AT());
        ContosoPostCodeDK.InsertPostCode('80807', MunchenLbl, CreateCountryRegion.DE());
        ContosoPostCodeDK.InsertPostCode('80997', MunchenLbl, CreateCountryRegion.DE());
        ContosoPostCodeDK.InsertPostCode('8129', AinDrahamLbl, CreateCountryRegion.TN());
        ContosoPostCodeDK.InsertPostCode('813 38', BratislavaLbl, CreateCountryRegion.SK());
        ContosoPostCodeDK.InsertPostCode('81420', KartalIstanbulLbl, CreateCountryRegion.TR());
        ContosoPostCodeDK.InsertPostCode('8152', GlattbruggLbl, CreateCountryRegion.CH());
        ContosoPostCodeDK.InsertPostCode('8170', BouSalemLbl, CreateCountryRegion.TN());
        ContosoPostCodeDK.InsertPostCode('81700', TuzlaIstanbulLbl, CreateCountryRegion.TR());
        ContosoPostCodeDK.InsertPostCode('8200', ArhusNLbl, CreateCountryRegion.DK());
        ContosoPostCodeDK.InsertPostCode('8200', SchaffhausenLbl, CreateCountryRegion.CH());
        ContosoPostCodeDK.InsertPostCode('821 04', BratislavaLbl, CreateCountryRegion.SK());
        ContosoPostCodeDK.InsertPostCode('82100', MazatlanSinaloaLbl, CreateCountryRegion.MX());
        ContosoPostCodeDK.InsertPostCode('8283', BlancaLbl, CreateCountryRegion.SI());
        ContosoPostCodeDK.InsertPostCode('83250', LALONDELESMAURESLbl, CreateCountryRegion.FR());
        ContosoPostCodeDK.InsertPostCode('8500', KortrijkLbl, CreateCountryRegion.BE());
        ContosoPostCodeDK.InsertPostCode('851 03', KolymbiaLbl, CreateCountryRegion.EL());
        ContosoPostCodeDK.InsertPostCode('852 33', SundsvallLbl, CreateCountryRegion.SE());
        ContosoPostCodeDK.InsertPostCode('86899', LandsbergamLechLbl, CreateCountryRegion.DE());
        ContosoPostCodeDK.InsertPostCode('8700', ElhovoLbl, CreateCountryRegion.BG());
        ContosoPostCodeDK.InsertPostCode('88100', KOTAKINABALUSabahLbl, CreateCountryRegion.MY());
        ContosoPostCodeDK.InsertPostCode('8850', MurauLbl, CreateCountryRegion.AT());
        ContosoPostCodeDK.InsertPostCode('88900', KuhmoLbl, CreateCountryRegion.FI());
        ContosoPostCodeDK.InsertPostCode('9000', AlborgLbl, CreateCountryRegion.DK());
        ContosoPostCodeDK.InsertPostCode('9000', VarnaLbl, CreateCountryRegion.BG());
        ContosoPostCodeDK.InsertPostCode('90000', KASBAHTANGERLbl, CreateCountryRegion.MA());
        ContosoPostCodeDK.InsertPostCode('900001', ABUJALbl, CreateCountryRegion.NG());
        ContosoPostCodeDK.InsertPostCode('9000-064', FUNCHALLbl, CreateCountryRegion.PT());
        ContosoPostCodeDK.InsertPostCode('9020', KlagenfurtLbl, CreateCountryRegion.AT());
        ContosoPostCodeDK.InsertPostCode('905 01', SenicaLbl, CreateCountryRegion.SK());
        ContosoPostCodeDK.InsertPostCode('9300', BloemfonteinLbl, CreateCountryRegion.ZA());
        ContosoPostCodeDK.InsertPostCode('930283', JOSPlateaustateLbl, CreateCountryRegion.NG());
        ContosoPostCodeDK.InsertPostCode('931104', GHOHPlateaustateLbl, CreateCountryRegion.NG());
        ContosoPostCodeDK.InsertPostCode('93450', KUCHINGSarawakLbl, CreateCountryRegion.MY());
        ContosoPostCodeDK.InsertPostCode('9500-101', PONTADELGADALbl, CreateCountryRegion.PT());
        ContosoPostCodeDK.InsertPostCode('985 01', KalinovoLbl, CreateCountryRegion.SK());
        ContosoPostCodeDK.InsertPostCode('9999', RosenstadtLbl, CreateCountryRegion.AT());
        ContosoPostCodeDK.InsertPostCode('AL 35242', BirminghamLbl, CreateCountryRegion.US());
        ContosoPostCodeDK.InsertPostCode('DSM', DarEsSalaamLbl, CreateCountryRegion.TZ());
        ContosoPostCodeDK.InsertPostCode('EBB', EntebbeLbl, CreateCountryRegion.UG());
        ContosoPostCodeDK.InsertPostCode('FL 37125', MiamiLbl, CreateCountryRegion.US());
        ContosoPostCodeDK.InsertPostCode('GA 31772', AtlantaLbl, CreateCountryRegion.US());
        ContosoPostCodeDK.InsertPostCode('H100', MbabaneLbl, CreateCountryRegion.SZ());
        ContosoPostCodeDK.InsertPostCode('H101', SwaziPlazaLbl, CreateCountryRegion.SZ());
        ContosoPostCodeDK.InsertPostCode('H108', PiggsPeakLbl, CreateCountryRegion.SZ());
        ContosoPostCodeDK.InsertPostCode('H200', ManziniLbl, CreateCountryRegion.SZ());
        ContosoPostCodeDK.InsertPostCode('IL 61236', ChicagoLbl, CreateCountryRegion.US());
        ContosoPostCodeDK.InsertPostCode('KLA', KampalaLbl, CreateCountryRegion.UG());
        ContosoPostCodeDK.InsertPostCode('L300', SitekiLbl, CreateCountryRegion.SZ());
        ContosoPostCodeDK.InsertPostCode('MB R0M 0N0', ElkhornLbl, CreateCountryRegion.CA());
        ContosoPostCodeDK.InsertPostCode('NY 11010', NewYorkLbl, CreateCountryRegion.US());
        ContosoPostCodeDK.InsertPostCode('ON L6J 3J3', OakvilleLbl, CreateCountryRegion.CA());
        ContosoPostCodeDK.InsertPostCode('ON M5E 1G5', TorontoLbl, CreateCountryRegion.CA());
        ContosoPostCodeDK.InsertPostCode('ON N6B 1V7', LondonLbl, CreateCountryRegion.CA());
        ContosoPostCodeDK.InsertPostCode('ON P7A 4K8', ThunderBayLbl, CreateCountryRegion.CA());
        ContosoPostCodeDK.InsertPostCode('ON P7B 5E2', ThunderBayLbl, CreateCountryRegion.CA());
        ContosoPostCodeDK.InsertPostCode('S400', NhlanganoLbl, CreateCountryRegion.SZ());
        ContosoPostCodeDK.InsertPostCode('SC 27136', ColombiaLbl, CreateCountryRegion.US());
        UpdatePostCodeCounty('FL 37125', MiamiLbl, 'FL');
        UpdatePostCodeCounty('GA 31772', AtlantaLbl, 'GA');
    end;

    local procedure UpdatePostCodeCounty(PostalCode: Code[20]; City: Text[30]; PostCodeCounty: Text[30])
    var
        PostCode: Record "Post Code";
    begin
        if not PostCode.Get(PostalCode, City) then
            exit;

        PostCode.Validate(County, PostCodeCounty);
        PostCode.Modify(true);
    end;

    var

        NairobiLbl: Label 'Nairobi', MaxLength = 30;
        KairiLbl: Label 'Kairi', MaxLength = 30;
        PretoriaLbl: Label 'Pretoria', MaxLength = 30;
        HelsinkiLbl: Label 'Helsinki', MaxLength = 30;
        ROMARMLbl: Label 'ROMA RM', MaxLength = 30;
        MaputoLbl: Label 'Maputo', MaxLength = 30;
        MexicoCityDFLbl: Label 'Mexico City, DF', MaxLength = 30;
        KlaukkalaLbl: Label 'Klaukkala', MaxLength = 30;
        WarszawaLbl: Label 'Warszawa', MaxLength = 30;
        DolnyKubinLbl: Label 'Dolny Kubin', MaxLength = 30;
        AlicanteLbl: Label 'Alicante', MaxLength = 30;
        SingaporeLbl: Label 'Singapore', MaxLength = 30;
        BetliarLbl: Label 'Betliar', MaxLength = 30;
        BucurestiLbl: Label 'Bucuresti', MaxLength = 30;
        BARIKALbl: Label 'BARIKA', MaxLength = 30;
        JokelaLbl: Label 'Jokela', MaxLength = 30;
        SaoPauloSPLbl: Label 'Sao Paulo SP', MaxLength = 30;
        OsloLbl: Label 'Oslo', MaxLength = 30;
        AnkaraLbl: Label 'Ankara', MaxLength = 30;
        PietersburgLbl: Label 'Pietersburg', MaxLength = 30;
        PalmaMallorcaLbl: Label 'Palma Mallorca', MaxLength = 30;
        BarcelonaLbl: Label 'Barcelona', MaxLength = 30;
        LjubljanaLbl: Label 'Ljubljana', MaxLength = 30;
        ManilaLbl: Label 'Manila', MaxLength = 30;
        SofiaLbl: Label 'Sofia', MaxLength = 30;
        ZagrebLbl: Label 'Zagreb', MaxLength = 30;
        CaceresLbl: Label 'Caceres', MaxLength = 30;
        AucklandLbl: Label 'Auckland', MaxLength = 30;
        TunisBelvedereLbl: Label 'Tunis Belvedere', MaxLength = 30;
        SantaCruzManilaLbl: Label 'Santa Cruz, Manila', MaxLength = 30;
        AmsterdamLbl: Label 'Amsterdam', MaxLength = 30;
        ReykjavikLbl: Label 'Reykjavik', MaxLength = 30;
        WienLbl: Label 'Wien', MaxLength = 30;
        AGDALRABATLbl: Label 'AGDAL-RABAT', MaxLength = 30;
        TORINOTOLbl: Label 'TORINO TO', MaxLength = 30;
        RIADRABATLbl: Label 'RIAD-RABAT', MaxLength = 30;
        RigaLbl: Label 'Riga', MaxLength = 30;
        TondoManilaLbl: Label 'Tondo, Manila', MaxLength = 30;
        TallinnLbl: Label 'Tallinn', MaxLength = 30;
        BangNaBangkokLbl: Label 'Bang Na, Bangkok', MaxLength = 30;
        TunisLbl: Label 'Tunis', MaxLength = 30;
        MoskvaLbl: Label 'Moskva', MaxLength = 30;
        JakartaLbl: Label 'Jakarta', MaxLength = 30;
        BangRakBangkokLbl: Label 'Bang Rak, Bangkok', MaxLength = 30;
        LISBOALbl: Label 'LISBOA', MaxLength = 30;
        KhlongSamwaBangkokLbl: Label 'Khlong Samwa, Bangkok', MaxLength = 30;
        AthensLbl: Label 'Athens', MaxLength = 30;
        BeogradLbl: Label 'Beograd', MaxLength = 30;
        DelhiLbl: Label 'Delhi', MaxLength = 30;
        BudapestLbl: Label 'Budapest', MaxLength = 30;
        ZaghouanLbl: Label 'Zaghouan', MaxLength = 30;
        CapriQuezonCityLbl: Label 'Capri, Quezon City', MaxLength = 30;
        StockholmLbl: Label 'Stockholm', MaxLength = 30;
        KorszeLbl: Label 'Korsze', MaxLength = 30;
        TEMARALbl: Label 'TEMARA', MaxLength = 30;
        SandvikaLbl: Label 'Sandvika', MaxLength = 30;
        LysakerLbl: Label 'Lysaker', MaxLength = 30;
        HaslumLbl: Label 'Haslum', MaxLength = 30;
        AskerLbl: Label 'Asker', MaxLength = 30;
        SkiLbl: Label 'Ski', MaxLength = 30;
        ValenzuelaLbl: Label 'Valenzuela', MaxLength = 30;
        OrnetaLbl: Label 'Orneta', MaxLength = 30;
        TangerangLbl: Label 'Tangerang', MaxLength = 30;
        ZaandamLbl: Label 'Zaandam', MaxLength = 30;
        BialystokLbl: Label 'Bialystok', MaxLength = 30;
        ALGIERSLbl: Label 'ALGIERS', MaxLength = 30;
        WatSingChaiNatLbl: Label 'Wat Sing, Chai Nat', MaxLength = 30;
        PiraeusLbl: Label 'Piraeus', MaxLength = 30;
        HumbeekLbl: Label 'Humbeek', MaxLength = 30;
        BorLbl: Label 'Bor', MaxLength = 30;
        SanktPetersburgLbl: Label 'Sankt Petersburg', MaxLength = 30;
        KopavogurLbl: Label 'Kopavogur', MaxLength = 30;
        JohannesburgLbl: Label 'Johannesburg', MaxLength = 30;
        MariborLbl: Label 'Maribor', MaxLength = 30;
        SydneyNSWLbl: Label 'Sydney, NSW', MaxLength = 30;
        CASABLANCALbl: Label 'CASABLANCA', MaxLength = 30;
        DubrovnikLbl: Label 'Dubrovnik', MaxLength = 30;
        CraiovaLbl: Label 'Craiova', MaxLength = 30;
        HamburgLbl: Label 'Hamburg', MaxLength = 30;
        MILANOMILbl: Label 'MILANO MI', MaxLength = 30;
        AntwerpenLbl: Label 'Antwerpen', MaxLength = 30;
        NarvaLbl: Label 'Narva', MaxLength = 30;
        MOHAMMEDIALbl: Label 'MOHAMMEDIA', MaxLength = 30;
        CopenhagenLbl: Label 'Copenhagen', MaxLength = 30;
        MOSTAGANCULbl: Label 'MOSTAGANCU', MaxLength = 30;
        NoviSadLbl: Label 'Novi Sad', MaxLength = 30;
        SplitLbl: Label 'Split', MaxLength = 30;
        HafnafjordurLbl: Label 'Hafnafjordur', MaxLength = 30;
        HerentalsLbl: Label 'Herentals', MaxLength = 30;
        SibenikLbl: Label 'Sibenik', MaxLength = 30;
        RiodeJaneiroRJLbl: Label 'Rio de Janeiro RJ', MaxLength = 30;
        Hamburg36Lbl: Label 'Hamburg 36', MaxLength = 30;
        WrNeudorfLbl: Label 'Wr. Neudorf', MaxLength = 30;
        SuboticaLbl: Label 'Subotica', MaxLength = 30;
        HundsheimLbl: Label 'Hundsheim', MaxLength = 30;
        CarletonvilleLbl: Label 'Carletonville', MaxLength = 30;
        EsztergomLbl: Label 'Esztergom', MaxLength = 30;
        KustendilLbl: Label 'Kustendil', MaxLength = 30;
        WollongongNSWLbl: Label 'Wollongong, NSW', MaxLength = 30;
        VilniusLbl: Label 'Vilnius', MaxLength = 30;
        BlagoevgradLbl: Label 'Blagoevgrad', MaxLength = 30;
        MechelenLbl: Label 'Mechelen', MaxLength = 30;
        MadridLbl: Label 'Madrid', MaxLength = 30;
        NewcastleLbl: Label 'Newcastle', MaxLength = 30;
        VedbaekLbl: Label 'Vedbaek', MaxLength = 30;
        AkranesLbl: Label 'Akranes', MaxLength = 30;
        KaunasLbl: Label 'Kaunas', MaxLength = 30;
        LeuvenLbl: Label 'Leuven', MaxLength = 30;
        MelbourneVICLbl: Label 'Melbourne, VIC', MaxLength = 30;
        BENINEdostateLbl: Label 'BENIN, Edo state', MaxLength = 30;
        COIMBRALbl: Label 'COIMBRA', MaxLength = 30;
        HalmstadLbl: Label 'Halmstad', MaxLength = 30;
        KairouanLbl: Label 'Kairouan', MaxLength = 30;
        StPoltenLbl: Label 'St. Pölten', MaxLength = 30;
        NonDindaengBuriRamLbl: Label 'Non Dindaeng, Buri Ram', MaxLength = 30;
        GrobelnoLbl: Label 'Grobelno', MaxLength = 30;
        TarnaleleszLbl: Label 'Tarnalelesz', MaxLength = 30;
        DundagaLbl: Label 'Dundaga', MaxLength = 30;
        NoszvajLbl: Label 'Noszvaj', MaxLength = 30;
        KragujevacLbl: Label 'Kragujevac', MaxLength = 30;
        DurbanLbl: Label 'Durban', MaxLength = 30;
        PontevedraLbl: Label 'Pontevedra', MaxLength = 30;
        DürnsteinLbl: Label 'Dürnstein  ', MaxLength = 30;
        SalamancaLbl: Label 'Salamanca', MaxLength = 30;
        LeonGuanajuatoLbl: Label 'Leon, Guanajuato', MaxLength = 30;
        BauskaLbl: Label 'Bauska', MaxLength = 30;
        RichardsBayLbl: Label 'Richards Bay', MaxLength = 30;
        BOLZANOBZLbl: Label 'BOLZANO BZ', MaxLength = 30;
        BrisbaneQLDLbl: Label 'Brisbane, QLD', MaxLength = 30;
        PlovdivLbl: Label 'Plovdiv', MaxLength = 30;
        KHENCHELbl: Label 'KHENCHE', MaxLength = 30;
        MumbaiLbl: Label 'Mumbai', MaxLength = 30;
        PORTOLbl: Label 'PORTO', MaxLength = 30;
        BandungLbl: Label 'Bandung', MaxLength = 30;
        LinzLbl: Label 'Linz', MaxLength = 30;
        DusseldorfLbl: Label 'Dusseldorf', MaxLength = 30;
        SevillaLbl: Label 'Sevilla', MaxLength = 30;
        PrattelnLbl: Label 'Pratteln', MaxLength = 30;
        GoteborgLbl: Label 'Goteborg', MaxLength = 30;
        PELABUHANKLANGSelangorLbl: Label 'PELABUHAN KLANG, Selangor', MaxLength = 30;
        KonyaLbl: Label 'Konya', MaxLength = 30;
        BjelovarLbl: Label 'Bjelovar', MaxLength = 30;
        NagpurLbl: Label 'Nagpur', MaxLength = 30;
        SamaraLbl: Label 'Samara', MaxLength = 30;
        RakvereLbl: Label 'Rakvere', MaxLength = 30;
        LACHAPELLEBASSEMERLbl: Label 'LA CHAPELLE BASSE MER', MaxLength = 30;
        KranjLbl: Label 'Kranj', MaxLength = 30;
        ManisaLbl: Label 'Manisa', MaxLength = 30;
        TapaLbl: Label 'Tapa', MaxLength = 30;
        OpoleLbl: Label 'Opole', MaxLength = 30;
        KogeLbl: Label 'Koge', MaxLength = 30;
        RudiskesLbl: Label 'Rudiskes', MaxLength = 30;
        ValenciaLbl: Label 'Valencia', MaxLength = 30;
        ValladolidLbl: Label 'Valladolid', MaxLength = 30;
        PETALINGJAYASelangorLbl: Label 'PETALING JAYA, Selangor', MaxLength = 30;
        GmundenLbl: Label 'Gmunden', MaxLength = 30;
        MustveeLbl: Label 'Mustvee', MaxLength = 30;
        AdungosiLbl: Label 'Adungosi', MaxLength = 30;
        OdenseCLbl: Label 'Odense C', MaxLength = 30;
        ZaragozaLbl: Label 'Zaragoza', MaxLength = 30;
        OgreLbl: Label 'Ogre', MaxLength = 30;
        BrasovLbl: Label 'Brasov', MaxLength = 30;
        SanPaTongChiangMaiLbl: Label 'San Pa Tong, Chiang Mai', MaxLength = 30;
        SalzburgLbl: Label 'Salzburg', MaxLength = 30;
        AMPANGKualaLumpurLbl: Label 'AMPANG, Kuala Lumpur', MaxLength = 30;
        CASSELLbl: Label 'CASSEL', MaxLength = 30;
        RecifePELbl: Label 'Recife PE', MaxLength = 30;
        KokneseLbl: Label 'Koknese', MaxLength = 30;
        WaalwijkLbl: Label 'Waalwijk', MaxLength = 30;
        KinnaredLbl: Label 'Kinnared', MaxLength = 30;
        RovinjLbl: Label 'Rovinj', MaxLength = 30;
        ThessalonikiLbl: Label 'Thessaloniki', MaxLength = 30;
        WoodvilleLbl: Label 'Woodville', MaxLength = 30;
        DannevirkeLbl: Label 'Dannevirke', MaxLength = 30;
        JonkobingLbl: Label 'Jonkobing', MaxLength = 30;
        SibiuLbl: Label 'Sibiu', MaxLength = 30;
        BengaluruLbl: Label 'Bengaluru', MaxLength = 30;
        KUALALUMPURLbl: Label 'KUALA LUMPUR', MaxLength = 30;
        MittersillLbl: Label 'Mittersill', MaxLength = 30;
        KlaipedaLbl: Label 'Klaipeda', MaxLength = 30;
        NyborgLbl: Label 'Nyborg', MaxLength = 30;
        LubinLbl: Label 'Lubin', MaxLength = 30;
        MarsabitLbl: Label 'Marsabit', MaxLength = 30;
        NorrkobingLbl: Label 'Norrkobing', MaxLength = 30;
        KoperLbl: Label 'Koper', MaxLength = 30;
        PortElizabethLbl: Label 'Port Elizabeth', MaxLength = 30;
        ChennaiLbl: Label 'Chennai', MaxLength = 30;
        WellingtonLbl: Label 'Wellington', MaxLength = 30;
        LuzernLbl: Label 'Luzern', MaxLength = 30;
        SurabayaLbl: Label 'Surabaya', MaxLength = 30;
        InnsbruckLbl: Label 'Innsbruck', MaxLength = 30;
        NizhnyNovgorodLbl: Label 'Nizhny Novgorod', MaxLength = 30;
        FrankfurtMainLbl: Label 'Frankfurt/Main', MaxLength = 30;
        SANTAVENERANDAPSLbl: Label 'SANTA VENERANDA PS', MaxLength = 30;
        RotkreuzLbl: Label 'Rotkreuz', MaxLength = 30;
        ImmenseeLbl: Label 'Immensee', MaxLength = 30;
        MonterreyNuevoLeonLbl: Label 'Monterrey, Nuevo Leon', MaxLength = 30;
        ZnojmoLbl: Label 'Znojmo', MaxLength = 30;
        PESCINAAQLbl: Label 'PESCINA AQ', MaxLength = 30;
        BlanskoLbl: Label 'Blansko', MaxLength = 30;
        PerthWALbl: Label 'Perth, WA', MaxLength = 30;
        ArnhemLbl: Label 'Arnhem', MaxLength = 30;
        BojkoviceLbl: Label 'Bojkovice', MaxLength = 30;
        BregenzLbl: Label 'Bregenz', MaxLength = 30;
        VladivostokLbl: Label 'Vladivostok', MaxLength = 30;
        VracovLbl: Label 'Vracov', MaxLength = 30;
        KyjovLbl: Label 'Kyjov', MaxLength = 30;
        EisenstadtLbl: Label 'Eisenstadt', MaxLength = 30;
        ZamboangaCityLbl: Label 'Zamboanga City', MaxLength = 30;
        KolkataLbl: Label 'Kolkata', MaxLength = 30;
        BrasiliaDFLbl: Label 'Brasilia DF', MaxLength = 30;
        MurdunnaTASLbl: Label 'Murdunna, TAS', MaxLength = 30;
        ZutphenLbl: Label 'Zutphen', MaxLength = 30;
        EningenLbl: Label 'Eningen', MaxLength = 30;
        ChaniaLbl: Label 'Chania', MaxLength = 30;
        ApeldoornLbl: Label 'Apeldoorn', MaxLength = 30;
        PARISLbl: Label 'PARIS', MaxLength = 30;
        PaldiskiLbl: Label 'Paldiski', MaxLength = 30;
        ESBLYLbl: Label 'ESBLY', MaxLength = 30;
        OlomouchLbl: Label 'Olomouch', MaxLength = 30;
        SanLuisPotosiSanLuisLbl: Label 'San Luis Potosi, San Luis', MaxLength = 30;
        PLAISIRLbl: Label 'PLAISIR', MaxLength = 30;
        HokitikaLbl: Label 'Hokitika', MaxLength = 30;
        MombasaLbl: Label 'Mombasa', MaxLength = 30;
        MalindiLbl: Label 'Malindi', MaxLength = 30;
        ArhusCLbl: Label 'Arhus C', MaxLength = 30;
        CapeTownLbl: Label 'Cape Town', MaxLength = 30;
        ChristchurchLbl: Label 'Christchurch', MaxLength = 30;
        CuritibaPRLbl: Label 'Curitiba PR', MaxLength = 30;
        IstanbulLbl: Label 'Istanbul', MaxLength = 30;
        GrazLbl: Label 'Graz', MaxLength = 30;
        MunchenLbl: Label 'Munchen', MaxLength = 30;
        AinDrahamLbl: Label 'Ain Draham', MaxLength = 30;
        BratislavaLbl: Label 'Bratislava', MaxLength = 30;
        KartalIstanbulLbl: Label 'Kartal-Istanbul', MaxLength = 30;
        GlattbruggLbl: Label 'Glattbrugg', MaxLength = 30;
        BouSalemLbl: Label 'Bou Salem', MaxLength = 30;
        TuzlaIstanbulLbl: Label 'Tuzla-Istanbul', MaxLength = 30;
        ArhusNLbl: Label 'Arhus N', MaxLength = 30;
        SchaffhausenLbl: Label 'Schaffhausen', MaxLength = 30;
        MazatlanSinaloaLbl: Label 'Mazatlan, Sinaloa', MaxLength = 30;
        BlancaLbl: Label 'Blanca', MaxLength = 30;
        LALONDELESMAURESLbl: Label 'LA LONDE LES MAURES', MaxLength = 30;
        KortrijkLbl: Label 'Kortrijk', MaxLength = 30;
        KolymbiaLbl: Label 'Kolymbia', MaxLength = 30;
        SundsvallLbl: Label 'Sundsvall', MaxLength = 30;
        LandsbergamLechLbl: Label 'Landsberg am Lech', MaxLength = 30;
        ElhovoLbl: Label 'Elhovo', MaxLength = 30;
        KOTAKINABALUSabahLbl: Label 'KOTA KINABALU, Sabah', MaxLength = 30;
        MurauLbl: Label 'Murau', MaxLength = 30;
        KuhmoLbl: Label 'Kuhmo', MaxLength = 30;
        AlborgLbl: Label 'Alborg', MaxLength = 30;
        VarnaLbl: Label 'Varna', MaxLength = 30;
        KASBAHTANGERLbl: Label 'KASBAH TANGER', MaxLength = 30;
        ABUJALbl: Label 'ABUJA', MaxLength = 30;
        FUNCHALLbl: Label 'FUNCHAL', MaxLength = 30;
        KlagenfurtLbl: Label 'Klagenfurt', MaxLength = 30;
        SenicaLbl: Label 'Senica', MaxLength = 30;
        BloemfonteinLbl: Label 'Bloemfontein', MaxLength = 30;
        JOSPlateaustateLbl: Label 'JOS, Plateau state', MaxLength = 30;
        GHOHPlateaustateLbl: Label 'GHOH, Plateau state', MaxLength = 30;
        KUCHINGSarawakLbl: Label 'KUCHING, Sarawak', MaxLength = 30;
        PONTADELGADALbl: Label 'PONTA DELGADA', MaxLength = 30;
        KalinovoLbl: Label 'Kalinovo', MaxLength = 30;
        RosenstadtLbl: Label 'Rosenstadt', MaxLength = 30;
        BirminghamLbl: Label 'Birmingham', MaxLength = 30;
        DarEsSalaamLbl: Label 'Dar Es Salaam', MaxLength = 30;
        EntebbeLbl: Label 'Entebbe', MaxLength = 30;
        MiamiLbl: Label 'Miami', MaxLength = 30;
        AtlantaLbl: Label 'Atlanta', MaxLength = 30;
        MbabaneLbl: Label 'Mbabane', MaxLength = 30;
        SwaziPlazaLbl: Label 'Swazi Plaza', MaxLength = 30;
        PiggsPeakLbl: Label 'Piggs Peak', MaxLength = 30;
        ManziniLbl: Label 'Manzini', MaxLength = 30;
        ChicagoLbl: Label 'Chicago', MaxLength = 30;
        KampalaLbl: Label 'Kampala', MaxLength = 30;
        SitekiLbl: Label 'Siteki', MaxLength = 30;
        ElkhornLbl: Label 'Elkhorn', MaxLength = 30;
        NewYorkLbl: Label 'New York', MaxLength = 30;
        OakvilleLbl: Label 'Oakville', MaxLength = 30;
        TorontoLbl: Label 'Toronto', MaxLength = 30;
        LondonLbl: Label 'London', MaxLength = 30;
        ThunderBayLbl: Label 'Thunder Bay', MaxLength = 30;
        NhlanganoLbl: Label 'Nhlangano', MaxLength = 30;
        ColombiaLbl: Label 'Colombia', MaxLength = 30;
}