permissionsetextension 14195 "D365 READ - Core Localization Pack for Czech" extends "D365 READ"
{
    Permissions = tabledata "Acc. Sched. Expr. Buffer CZL" = R,
                  tabledata "Acc. Schedule Extension CZL" = R,
                  tabledata "Acc. Schedule File Mapping CZL" = R,
                  tabledata "Acc. Schedule Result Col. CZL" = R,
                  tabledata "Acc. Schedule Result Hdr. CZL" = R,
                  tabledata "Acc. Schedule Result Hist. CZL" = R,
                  tabledata "Acc. Schedule Result Line CZL" = R,
                  tabledata "Acc. Schedule Result Value CZL" = R,
                  tabledata "Certificate Code CZL" = R,
                  tabledata "Commodity CZL" = R,
                  tabledata "Commodity Setup CZL" = R,
                  tabledata "Company Official CZL" = R,
                  tabledata "Constant Symbol CZL" = R,
                  tabledata "Document Footer CZL" = R,
                  tabledata "EET Business Premises CZL" = R,
                  tabledata "EET Cash Register CZL" = R,
                  tabledata "EET Entry CZL" = R,
                  tabledata "EET Entry Status Log CZL" = R,
                  tabledata "EET Service Setup CZL" = R,
                  tabledata "Excel Template CZL" = R,
                  tabledata "Intrastat Delivery Group CZL" = R,
                  tabledata "Invt. Movement Template CZL" = R,
                  tabledata "Reg. No. Service Config CZL" = R,
                  tabledata "Registration Log CZL" = R,
                  tabledata "Specific Movement CZL" = R,
                  tabledata "Statistic Indication CZL" = R,
                  tabledata "Statutory Reporting Setup CZL" = R,
                  tabledata "Stockkeeping Unit Template CZL" = R,
                  tabledata "Subst. Cust. Posting Group CZL" = R,
                  tabledata "Subst. Vend. Posting Group CZL" = R,
                  tabledata "Unrel. Payer Service Setup CZL" = R,
                  tabledata "Unreliable Payer Entry CZL" = R,
                  tabledata "User Setup Line CZL" = RIMD,
                  tabledata "VAT Attribute Code CZL" = R,
                  tabledata "VAT Ctrl. Report Buffer CZL" = R,
                  tabledata "VAT Ctrl. Report Ent. Link CZL" = R,
                  tabledata "VAT Ctrl. Report Header CZL" = R,
                  tabledata "VAT Ctrl. Report Line CZL" = R,
                  tabledata "VAT Ctrl. Report Section CZL" = R,
                  tabledata "VAT LCY Correction Buffer CZL" = R,
                  tabledata "VAT Period CZL" = R,
                  tabledata "VAT Statement Attachment CZL" = R,
                  tabledata "VAT Statement Comment Line CZL" = R,
                  tabledata "VIES Declaration Header CZL" = R,
                  tabledata "VIES Declaration Line CZL" = R;
}
