name: Create a new performance test app

on:
  workflow_dispatch:
    inputs:
      project:
        description: Project name if the repository is setup for multiple projects
        required: false
        default: '.'
      name:
        description: Name
        required: true
        default: '<YourAppName>.PerformanceTest'         
      publisher:
        description: Publisher
        required: true
      idrange:
        description: ID range
        required: true
        default: '50000..99999'  
      sampleCode:
        description: Include Sample code (Y/N)
        required: false
        default: 'Y'
      sampleSuite:
        description: Include Sample BCPT Suite (Y/N)
        required: false
        default: 'Y'
      directCommit:
        description: Direct COMMIT (Y/N)
        required: false
        default: 'N'

permissions:
  contents: write
  pull-requests: write

defaults:
  run:
    shell: PowerShell

jobs:
  Initialization:
    runs-on: [ self-hosted, 1ES.Pool=ALAppExtensions ]
    outputs:
      telemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Initialize the workflow
        id: init
        uses: microsoft/AL-Go-Actions/WorkflowInitialize@main
        with:
          eventId: "DO0102"

  Update:
    runs-on: [ self-hosted, 1ES.Pool=ALAppExtensions ]
    needs: [ Initialization ]

    steps:
      - name: Creating a new test app
        uses: microsoft/AL-Go-Actions/CreateApp@main
        with:
          parentTelemetryScopeJson: ${{ needs.Initialization.outputs.telemetryScopeJson }}
          project: ${{ github.event.inputs.project }}
          type: 'Performance Test App'
          publisher: ${{ github.event.inputs.publisher }}
          name: ${{ github.event.inputs.name }}
          idrange: ${{ github.event.inputs.idrange }}
          sampleCode: ${{ github.event.inputs.sampleCode }}
          sampleSuite: ${{ github.event.inputs.sampleSuite }}
          directCommit: ${{ github.event.inputs.directCommit }}

  PostProcess:
    if: always()
    runs-on: [ self-hosted, 1ES.Pool=ALAppExtensions ]
    needs: [ Initialization, Update ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Finalize the workflow
        id: PostProcess
        uses: microsoft/AL-Go-Actions/WorkflowPostProcess@main
        with:
          eventId: "DO0102"
          telemetryScopeJson: ${{ needs.Initialization.outputs.telemetryScopeJson }}
