name: PR Processing

on:
  pull_request_target:
    types: [labeled]
  issues:
    types: [labeled]

permissions:
  issues: write
  pull-requests: write

jobs:
  post-processing-comment:
    if: github.event.label.name == 'processing-PR'
    runs-on: ubuntu-latest

    steps:
    - name: Post comment
      uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7.1.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Processing this PR. The branch is now locked 🔒 Please don\'t push updates unless otherwise agreed.'
          })

  post-approved-comment:
    if: github.event.label.name == 'Approved'
    runs-on: ubuntu-latest

    steps:
    - name: Post comment
      uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7.1.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'This issue has been approved for contribution ✅ Thanks for contributing.'
          })
