name: Update Package Versions

on:
  workflow_dispatch:
  schedule:
    - cron: "55 03 * * 2" # Run at 03:55 UTC on Tuesday

defaults:
  run:
    shell: powershell

jobs:
  UpdatePackageVersions:
    if: github.repository_owner == 'microsoft'
    runs-on: windows-latest
    strategy:
      matrix:
        branch: ['main']
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ matrix.branch }}
      
      - name: Update Package Versions
        run: | 
          Build/Scripts/UpdatePackageVersions.ps1 -TargetBranch ${{ matrix.branch }} -Actor $env:GITHUB_ACTOR
        env:
          GITHUB_TOKEN: ${{ secrets.GHTOKENWORKFLOW }}
